### ISSUE TITLE
gpg-agent

### ISSUE THREAD

**Issue by beckend** [zimfw/zimfw#135]
Is there a gpg-agent plugin?

**Comment by Eriner** [comment]
Currently, no.

**Comment by Tuurlijk** [comment]
@beckend what should the plugin provide?

**Comment by beckend** [comment]
Something like:
```bash
# Add the following to your shell init to set up gpg-agent automatically for every shell
if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
    source ~/.gnupg/.gpg-agent-info
    export GPG_AGENT_INFO
else
    eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi
export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
```

**Comment by Tuurlijk** [comment]
I see. We'll need to adjust this a bit to also make it work for gpg v 2. This gives me: gpg-agent[xxx]: WARNING: "--write-env-file" is an obsolete option - it has no effect

Think we should use gpgconf in that case

**Comment by AtomicCoding** [comment]
Why not just use the [`oh-my-zsh` gpg-agent plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gpg-agent) or [this](https://github.com/axtl/gpg-agent.zsh)?

**Comment by Brottweiler** [comment]
You could probably use a plugin manager and do something like this `zplug "plugins/gpg-agent",   from:oh-my-zsh`, at least if you're using https://github.com/zplug/zplug

**Comment by AtomicCoding** [comment]
@ericbn @Eriner, can we close this now that #257 is merged?
