### ISSUE TITLE
Create a zim ASCII-art logo

### ISSUE THREAD

**Issue by ericbn** [zimfw/zimfw#183]
To also replace the current logo in the README.md. This is something I've thinking about for a while, and #182 just encouraged me more.

I was into ANSI and ASCII art in the '90s, so it would be really cool to get back to that...

I would keep the same "alien" drawing idea as in the current logo (just have a different lettering, because that serif font... 🙈)

@Eriner, what do you think?

**Comment by ericbn** [comment]
Some of the stuff I still have from back then:

![medusa add](https://cloud.githubusercontent.com/assets/4120606/26279949/3eeaf298-3d89-11e7-94f2-6672e56c1c98.png)
![st-medus diz](https://cloud.githubusercontent.com/assets/4120606/26280086/afaf4f12-3d8c-11e7-9348-9566b813ca4d.png)
![titles incoming](https://cloud.githubusercontent.com/assets/4120606/26279970/148cd736-3d8a-11e7-959d-f355fe424f9c.png)
![st-czdrv ans](https://cloud.githubusercontent.com/assets/4120606/26280006/b4520ab6-3d8a-11e7-8139-4909f3de69fd.png)
![st-shado diz](https://cloud.githubusercontent.com/assets/4120606/26280046/ed106cde-3d8b-11e7-8a0d-2273aea2f459.png)
![st-mmi ans](https://cloud.githubusercontent.com/assets/4120606/26280024/50f27b08-3d8b-11e7-82cf-33ad237b5dd4.png)

**Comment by Eriner** [comment]
Ha, I'm up for this. I'm even willing to change the logo entirely if someone can do something better than my 20 minutes spent in gimp. If anyone wants the source files for the logo design, I'd be happy to make them available as well. I have the files laying around here somewhere..

**Comment by jorvi** [comment]
Something like this?

<img width="247" alt="screen shot 2017-06-12 at 18 01 45" src="https://user-images.githubusercontent.com/6699838/27043065-3844fc3c-4f99-11e7-8880-4fca742414f9.png">

**Comment by ericbn** [comment]
I was thinking on something on these lines:

![artpacks txt](https://user-images.githubusercontent.com/4120606/34544709-de41816a-f0b5-11e7-8fb6-930b6d86a0f7.png)

![www acid org](https://user-images.githubusercontent.com/4120606/34544711-e11791d6-f0b5-11e7-831a-eae355a1607d.png)

**Comment by AtomicCoding** [comment]
I did some image editing with the logo and came to this:
![](https://i.imgur.com/9E6eCul.png)

**Comment by AtomicCoding** [comment]
@ericbn Ping

**Comment by ericbn** [comment]
@AtomicCoding, thanks for your effort. This is not something we need right now, as it was intended to be used with an install script we were working on.

I'll keep this on hold, and also keep the possibility open for other people to come up with their art.

**Comment by ericbn** [comment]
I'm playing with drawing a logo and came up with this simple one:

![screen shot 2018-05-27 at 18 13 07](https://user-images.githubusercontent.com/4120606/40591614-201577a0-61da-11e8-89a5-d83a8b451fc2.png)

**Comment by Brottweiler** [comment]
@ericbn *Knowing* it says Zim, I can't make it out to where it would spell "Zim"... just me or?

I guess I can kind of see the "m", but I can't see how it says "Z" at all.

**Comment by ericbn** [comment]
@Brottweiler, maybe if make it more flat:

![screen shot 2018-05-28 at 17 40 16](https://user-images.githubusercontent.com/4120606/40631132-0f8f66aa-629f-11e8-8911-37bd9b84368a.png)

**Comment by Brottweiler** [comment]
I really can't make out the Z, but that could just be me.

**Comment by Plloi** [comment]
@ericbn It's simple, I like it.

**Comment by ericbn** [comment]
It's been 20 years I don't do ASCII art anymore, so I'm rusted on that. Calling out the skilled designers and ASCII artists out there!  :- )

**Comment by ericbn** [comment]
Closing this in favor of #418. Thanks again @OneMohrTime for creating an amazing set of logos for Zim!

**Comment by ericbn** [comment]
I've ended up drawing the ASCIIart version of our beautiful logo designed by Derek (#418). Just wanted to leave it documented here. Derek's logo is so good that it's also a perfect fit for an ASCIIart version of it:

<img width="210" height="100" alt="ASCIIart logo" src="https://github.com/user-attachments/assets/579bff1a-d056-45b9-ac2d-d8c53add8a0d" />
