### ISSUE TITLE
 You're using zsh version 5.4.1, and versions < 5.2 are not supported. Update your zsh.

### ISSUE THREAD

**Issue by ckubrak** [zimfw/zimfw#249]
Hi,
I'm running zim in Ubuntu 16.04. Everything was fine until I run "sudo apt autoremove" to clear non needed packages.
Now, when I open a terimal I get:
```
/etc/zsh/zshrc:111: compinit: function definition file not found
/home/cristian/.zim/init.zsh:6: is-at-least: function definition file not found
ERROR: Zim didn't start. You're using zsh version 5.4.1, and versions < 5.2 are not supported. Update your zsh.

```

- gist of .zimrc:
https://gist.github.com/9365c7fd0e077422823218aa2bdc8234
- gist of .zshrc:
https://gist.github.com/61fb47054d703434e6f663b02b324773
- gist of /etc/zsh/zshrc
https://gist.github.com/b348b7fb748932429082d52f62b92b96
- gist of init.zsh
https://gist.github.com/6b06766ac58cd0cebad6de69c38f6760

Thanks!

**Comment by Plloi** [comment]
can you post your .zlogin?

**Comment by ckubrak** [comment]
.zlogin
https://gist.github.com/77616157d0b52ad378d3f412161ce5ec

**Comment by Plloi** [comment]
your zlogin is out of date, you should replace it with the template in the repo https://github.com/zimfw/zimfw/blob/master/templates/zlogin

**Comment by ckubrak** [comment]
@Plloi I just did it. Same error

**Comment by grahamgilbert** [comment]
I just performed a clean installation and also go this error.

**Comment by AtomicCoding** [comment]
You need to update your ZSH. Use your OS's package manager to install it.
MacOS (if you have homebrew):
`brew install zsh`
Most Linux Operating Systems:
`sudo apt-get update && sudo apt-get install zsh`
Comment at me if you need help.

**Comment by AtomicCoding** [comment]
Can this be closed?

**Comment by Plloi** [comment]
@ckubrak's installed version is supported, updating isn't the issue here.

@ckubrak can you post the out of `echo $FPATH`?

@grahamgilbert  Can you post your installed zsh version?

**Comment by AtomicCoding** [comment]
@Plloi @ckubrak I'm so sorry, I should of read it fully before commenting. Sorry!

**Comment by ckubrak** [comment]
@Plloi Right now I don't have access to that computer, I'll post it as soon as possible.

**Comment by AtomicCoding** [comment]
@ckubrak Can you also try removing the check code at the start of the Zim init script?
It's in `~/.zim/init.zsh` and it looks like:
```zsh
autoload -Uz is-at-least
if ! is-at-least 5.2; then
  print "ERROR: Zim didn't start. You're using zsh version ${ZSH_VERSION}, and versions < 5.2 are not supported. Update your zsh." >&2
  return 1
fi
```

**Comment by Eriner** [comment]
@ckubrak does PR #252 return an error like this?
```
/home/eriner/.zim/init.zsh:5: is-at-least: function definition file not found
```

**Comment by ckubrak** [comment]
@Eriner I'm still getting the same error.
@AtomicCoding Commenting those lines worked

**Comment by Eriner** [comment]
@ckubrak Yeah, that's because that functionality wasn't added until 5.4.2. You should re-install zsh. If you don't have `is-at-least` your environment is messed up. This is an issue specific to your environment.
