### ISSUE TITLE
Question : is it possible to load modules from multiple location ?

### ISSUE THREAD

**Issue by grzesuav** [zimfw/zimfw#251]
Description
-----------
I have system-wide installation of ZIM (in Arch linux), I wonder is it possible to extend module loading mechanism to include user specific location, for example `$HOME/.zim/modules` ?

I would like to add a new module and test it locally before I made contribution (maybe only I will be using this module so I don't have guarantee that it will be merged anyway). Besides of that it can be useful feature. I briefly looked at the ZIM source-code (but I am not fluent in zsh, just can write simple bash script) and it seems it only use `$ZIM_HOME` location to search for submodules.

I am aware that this need to be done carefully, considering configuration because I can image that if it will use the same `zmodules` list for both locations (built-in and user), it will involve making `search` mechanism smarter, to choose user source when there is no built-in module, but it will preserve ordering of modules loading easy.

Regards

**Comment by ericbn** [comment]
@grzesuav, zim loads all modules in `${ZIM_HOME}/modules/${^zmodules}(/FN)`, which means all non-empty subdirectories of `${ZIM_HOME}/modules` that are listed in the `zmodules` array. You can see that logic in the `${ZIM_HOME}/init.zsh` script.

We currently don't support having both a system-wide and a user-specific zim configuration at the same time.

**Comment by Plloi** [comment]
Not that it's the greatest way to handle it but you can add pathinfo to a module name e.g.: `../../../../home/user/.zim/modules/modulename`
Ugly but works.

**Comment by Eriner** [comment]
@grzesuav If you want a system-wide installation, then you need to only use and update the system-wide installation. This is my number one issue with system-wide installations; non-root users can't make modifications. Searching multiple file paths means opening more files than really necessary, and it's non-optimal.

Instead, why not drop a folder with a `.zim` repo and a `.zshrc` into `/etc/skel`, so it will be copied to each user's home folder when a user is created? If this isn't a use case (you're not going to be making multiple additional users), then you don't have a use-case for a system-wide zim install, and you probably are best served by copying your `.zim` add `.z*` files into the home directories of the users you use.

**Comment by grzesuav** [comment]
Thanks for response,

in arch-linux there is a rich repository with packages created by users, there is also `zsh-zim-git` package, preferred way to install packages it to do it this way. Just wanted to have both - system wide installation and ability to adjust it locally. I will try to keep it in user folder.


Regards

**Comment by Eriner** [comment]
@grzesuav the alternative is to keep `zsh-zim-git` installed, and also have a `.zim` folder in your home directory for the user you want to add functions to. This means you get a default of zim (where you source the global install) and in the user with custom functionality, you source a local install instead. Again, I think the right answer is to just do a per-user install, but that seems like a decent compromise and gives you the best of both worlds at the cost of having to do a `git pull` AND rebuild the `-git` package occasionally (as opposed to only having to upgrade one install).
