### ISSUE TITLE
No such module "meta" on zsh 5.2

### ISSUE THREAD

**Issue by antonshiryaev** [zimfw/zimfw#254]
Ubuntu 17.10 ships with zsh 5.2. When using my .zshrc from my Mac with zsh 5.4.1, I get the error `No such module "meta".`. I haven't noticed any deficiencies otherwise. `.zshrc` attached. The error doesn't occur on my Mac. There's some platform-specific stuff in there, but the message appears to be generated by Zim.
[zshrc.txt](https://github.com/zimfw/zimfw/files/1866748/zshrc.txt)

UPDATE: Weeded out almost all Mac stuff, still getting the message.

**Comment by Eriner** [comment]
There isn't a meta module anymore. Just remove this from `.zshrc`

**Comment by antonshiryaev** [comment]
Remove what?

**Comment by Plloi** [comment]
in your .zimrc remove meta from the zmodules array

**Comment by antonshiryaev** [comment]
That worked, thanks. Should I do it on macOS, too?

**Comment by Plloi** [comment]
Yep.
