### ISSUE TITLE
Fish-style history search doesn't work in vi mode

### ISSUE THREAD

**Issue by antonshiryaev** [zimfw/zimfw#258]
If I have `set -o vi` in `.zshrc`, it doesn't work. If I comment it out, vi mode is disabled, obviously, but it starts to work again.

**Comment by antonshiryaev** [comment]
[Same issue, apparently](https://github.com/robbyrussell/oh-my-zsh/issues/1479#issuecomment-42633554)

**Comment by AtomicCoding** [comment]
@Eriner @ericbn 
We could fix this with something like:
```zsh
if set -o | grep "vi                    on"; then
bindkey "something" history-substring-search-up
bindkey "something" history-substring-search-down
else
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
fi
```

**Comment by AtomicCoding** [comment]
@antonshiryaev 
Does it work if you paste,
```zsh
bindkey "^[" history-substring-search-up
bindkey "^]" history-substring-search-down
```
into zsh and then try using `Ctrl+[` instead of up and `Ctrl+]` instead of down?

**Comment by antonshiryaev** [comment]
In `.zshrc`, you mean. Moving `set -o vi` to the top of `.zshrc` and `history-substring-search` to the end of zmodules in `.zimrc` fixed it.

**Comment by antonshiryaev** [comment]
Adding things before code loading the framework is not something many people would normally do - perhaps it'd be a good idea to set the mode through .zimrc and say so in the readme?

**Comment by AtomicCoding** [comment]
@antonshiryaev PR? You can make your own changes to the README and zimrc or zshrc.
