### ISSUE TITLE
Completion for git alias branch delete (gbx)

### ISSUE THREAD

**Issue by sQVe** [zimfw/zimfw#265]
The current git aliases to delete a branch works correctly but the completions are broken, atleast for me. What's the reason for using `git-branch-delete-interactive` instead of `git branch --delete`?

I've changed this in my fork, https://github.com/sQVe/zim/commit/a66444372f7b542990066d3f5e75a65214956c85, and completions are then fixed.

Please let me know if I should push a quick PR!

**Comment by ericbn** [comment]
HI @sQVe. Thanks for your feedback on `git-branch-delete-interactive`. What it adds is a prompt to delete the remote branch too, in case there's a remote tracking branch associated with the branch you're deleting.

But we lose the completion, I didn't notice that. Good catch!

By adding a `modules/git/functions/_git-branch-delete-interactive` file with

    #compdef git-branch-delete-interactive

    _alternative \
        'branch-names::__git_ignore_line_inside_arguments __git_branch_names' \
        'remote-branch-names::__git_ignore_line_inside_arguments __git_remote_branch_names'

we can have completion for that (mind refreshing the completion cache). **But** that will only work after the git completion is loaded. Any idea on how to fix this?

Or I'll just go ahead and remove the `git-branch-delete-interactive` function altogether. I thought it was a nice addition... 😢

@Eriner, thoughts?

**Comment by ericbn** [comment]
Got this nice completion setup after spending a while in the very helpful #zsh chat:

```
#compdef git-branch-delete-interactive

compdef -e 'words[1]=(git branch); (( CURRENT++ )); service=git; _git' git-branch-delete-interactive
```

So this should be the `modules/git/functions/_git-branch-delete-interactive` contents.

Works for you?

**Comment by AtomicCoding** [comment]
@ericbn Looks good! 
Two Problems:
* Lists tags
* When not in a git repository, defaults to completing directory

Otherwise, it's great!
