### ISSUE TITLE
History file full of dupes

### ISSUE THREAD

**Issue by sQVe** [zimfw/zimfw#271]
System
----------

```
Zim commit ref:   5c64126
Zsh version:      zsh 5.5.1 (x86_64-unknown-linux-gnu)
System info:      Linux kodama 4.14.39-2-lts #1 SMP Sat May 5 19:07:21 CEST 2018 x86_64 GNU/Linux
```

https://github.com/sQVe/dotfiles/blob/master/zimrc
https://github.com/sQVe/dotfiles/blob/master/zshrc

Description
-----------

I was surprised by the size of my `.zhistory` file today and when opening it I noticed it was full of dupes. The `history` module sets `HIST_IGNORE_ALL_DUPS` but this seems to be ignored / not working for some reason.

I made this little test:

```
% rm .zhistory
% echo "1"
1
% echo "2"
2
% echo "1"
1
% cat .zhistory
: 1525810118:0;echo "1"
: 1525810122:0;echo "2"
: 1525810126:0;echo "1"
: 1525810128:0;cat .zhistory
```

Steps to reproduce
------------------
You should see it straight away when you open your `.zhistory` file.

**Comment by ericbn** [comment]
@sQVe, if you look at how many unique items you have in your `.zhistory` file, it should match the value of `${HISTSIZE}`.

**Comment by Plloi** [comment]
@sQVe Can you try removing `setopt HIST_SAVE_NO_DUPS` from the history module and see if that produces the behavior that you want.

**Comment by sQVe** [comment]
@ericbn Gotcha. I personally find it a bit backwards to only trim dupes at a specific limit as dupes add no real value, at least not for me. If this is the expected behavior and `zimfw` is fine with that implementation I suggest closing this issue.
