### ISSUE TITLE
Syntax highlighting bug when auto completing command triggering my OCD

### ISSUE THREAD

**Issue by lsunsi** [zimfw/zimfw#274]
```
% zmanage info                                                                                    ~
Zim commit ref:   3b7eeda
Zsh version:      zsh 5.5.1 (x86_64-apple-darwin17.5.0)
System info:      Darwin Mac.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
```

- gist of .zimrc: https://gist.github.com/lsunsi/ab4b55007dfb915cc41e90f5e5c55966
- gist of .zshrc: https://gist.github.com/lsunsi/f40afd41f692cc60e7f9f6d6d261eb74

Description
-----------
Syntax highlighting for known commands runs flawlessly, except when I auto complete with tab. 
It's a minor bug, but I'm reporting it because I've been a long time zim user and this seems new.
It might be my fault somehow (: 

Steps to reproduce
------------------
I literally formatted my Mac, installed zim and upon 5 minutes I realised it was off. Just auto complete any command.

Images or other information
---------------------------
`zmanage` turns white when pressing tab
![zim-bug-report](https://user-images.githubusercontent.com/6089867/40304877-ae5eb6ae-5cce-11e8-8f6e-f691ae853382.gif)

**Comment by ericbn** [comment]
Oi @lsunsi.

`syntax-highlighting` should be the last item in your zmodules array. See [this](https://github.com/zsh-users/zsh-syntax-highlighting#why-must-zsh-syntax-highlightingzsh-be-sourced-at-the-end-of-the-zshrc-file).

**Comment by AtomicCoding** [comment]
@ericbn I have the same issue, and that didn't fix it for me.

**Comment by ericbn** [comment]
@lsunsi, it could be changes to the upstream projects that brake something from the last time you used zim to now. I think we should update our `zimrc` template to reflect the current recommended order of loading these modules.

@AtomicCoding, you are right about history-substring-search. Moving it to after syntax-highlighting solved it for me. I'm using
```
zmodules=(archive autosuggestions directory environment git git-info history \
          input prompt ssh utility \
          completion syntax-highlighting history-substring-search)
```

Can you guys please try again having the last ones being `completion syntax-highlighting history-substring-search`? Also if you're using some other module that specifically depends on completion (like oh-my-zsh's osx) those should go after completion, of course.

**Comment by AtomicCoding** [comment]
@ericbn The issue randomly stopped for me. Even changing the orders back to the state earlier didn't reproduce the issue.
