### ISSUE TITLE
Changing cursor shape based on Vi mode stops Fish-like search from working

### ISSUE THREAD

**Issue by oscu0** [zimfw/zimfw#278]
My second bug report about Vi mode breaking history search, something must be very fragile there. zsh 5.5.1, macOS 10.13.5, latest zim, et cetera.

Code: 
```
function zle-keymap-select zle-line-init
{
    # change cursor shape in iTerm2
    case $KEYMAP in
        vicmd)      print -n -- "\E]50;CursorShape=0\C-G";;  # block cursor
        viins|main) print -n -- "\E]50;CursorShape=1\C-G";;  # line cursor
    esac
    zle reset-prompt
    zle -R
}

function zle-line-finish
{
    print -n -- "\E]50;CursorShape=0\C-G"  # block cursor
}

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select
```
Adding it, either before or after loading Zim, breaks history substring search.

**Comment by nunocastromartins** [comment]
I'm using the following, and history search seems to work fine:
```bash
# Switch cursor between beam and block depending on terminal Vim mode
BLOCK='\e[1 q'
BEAM='\e[5 q'

function zle-line-init zle-keymap-select {
  if [[ $KEYMAP == vicmd ]] || [[ $1 = 'block' ]]; then
    echo -ne $BLOCK
  elif [[ $KEYMAP == main ]] || [[ $KEYMAP == viins ]] ||
       [[ $KEYMAP = '' ]] || [[ $1 = 'beam' ]]; then
    echo -ne $BEAM
  fi
}

zle -N zle-line-init
zle -N zle-keymap-select

# Remove delay when switching Vim mode
export KEYTIMEOUT=1
```

**Comment by g6ai** [comment]
Is it possible to adopt https://github.com/jeffreytse/zsh-vi-mode?

**Comment by ericbn** [comment]
@g6ai, sure. You just need to add it to your .zimrc. Not sure if it should be the last zmodule -- to be safe, I prefer to load most modules at least before zsh-users/zsh-completions:
```
zmodule jeffreytse/zsh-vi-mode
```
Then you can remove the input module, which will not be needed anymore, and jeffreytse/zsh-vi-mode will take care of the key bindings:
```diff
-zmodule input
```
And you can also remove this from your .zshrc:
```diff
-bindkey -e
```
