### ISSUE TITLE
Wiki is outdated for "available modules"?

### ISSUE THREAD

**Issue by singularitti** [zimfw/zimfw#282]
Currently the wiki [modules](https://github.com/zimfw/zimfw/wiki/Modules) page does not list all the modules which can be found in `modules` folder. Are the modules not stable so they are not recommended to invoke, or is it just a case where the wiki needed to be updated?

**Comment by ericbn** [comment]
@singularitti, you're right. We're missing:
* autosuggestions: a wrapper to [zsh-users/zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions).
* custom: a template for a custom module, not something worth listing.
* debug: adds the trace-zim function.
* fasd: our own fork of [clvv/fasd](https://github.com/clvv/fasd) (until it's "abandoned")

**Comment by ericbn** [comment]
@singularitti, I plan to update the Wikis after the develop branch in promoted to master, to reflect the new changes there.

**Comment by singularitti** [comment]
Sorry, I am reopening it.
