### ISSUE TITLE
git add completion on parent dir not working

### ISSUE THREAD

**Issue by deadc0de6** [zimfw/zimfw#283]
```
Zim commit ref:   9039549
Zsh version:      zsh 5.5.1 (x86_64-debian-linux-gnu)
System info:      Debian x86_64 GNU/Linux
```

Description
-----------

When using `git add`, I noticed that the completion is only done on current dir and sub-dir but not on the parent dir. I'm not sure this is related to zim through. Any help would be appreciated!

Steps to reproduce
------------------

For example
```bash
$ mkdir testgit
$ cd testgit 
$ git init    
Initialized empty Git repository in /tmp/testgit/.git/
$ mkdir a
$ touch up a/b a/c
$ git add <TAB>
-- untracked file --
a  up
$ cd a
## At this point I would expect git add to also suggest ../up
$ git add <TAB>
-- untracked file --
b  c
```

Images or other information
---------------------------

zimrc
```
zmodules=(directory environment git git-info history input utility custom \
          syntax-highlighting history-substring-search prompt completion \
          autosuggestions)
zprompt_theme='pure'
ztermtitle='%n@%m:%~'
zdouble_dot_expand='true'
zhighlighters=(main brackets cursor)
```

zshrc
```
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh
setopt CLOBBER
autoload -Uz compinit
compinit
```

**Comment by Eriner** [comment]
I think everything here is working as intended. I'd be very irritated if git completion thought it was smarter than me and started completing for files up a directory. If I wanted that (to add files up the tree) without leaving the current directory, I'd type the `../` and then tab complete or run `git add $(git-root)` to add them all. Bash autocompletion also works this way.

**Comment by deadc0de6** [comment]
indeed doing `git add ../` and then tab does not complete, that's my point ...

**Comment by Eriner** [comment]
Ah, that wasn't clear. If you'd like to see changes in this regard, take a look here: `/usr/share/zsh/functions/Completion/Unix/_git` and hit up the zsh mailing list.

**Comment by deadc0de6** [comment]
thanks for the help, so you mean this a zsh issue (and not zim) and I should somehow hack into the zsh git completion to make it work?
Any reason this is not a default behavior?
