### ISSUE TITLE
How can I use this themes with zim?

### ISSUE THREAD

**Issue by karambaq** [zimfw/zimfw#285]
https://github.com/arialdomartini/oh-my-git-themes

**Comment by AtomicCoding** [comment]
3 steps:
1. Clone the repo to the prompt module external-themes directory (This just gives it a standard location and downloads the prompts)
`git clone https://github.com/arialdomartini/oh-my-git-themes.git ${ZIM_HOME}/modules/prompt/external-themes/oh-my-git`
2. Create the symlinks in the functions directory, this is where prompts are loaded from (symlinks are files that point to other files, this allows us to continually update the oh-my-git themes and not have to modify the files that point to them)
`ln -s ${ZIM_HOME}/modules/prompt/external-themes/oh-my-git/arialdo-granzestyle.zsh-theme ${ZIM_HOME}/modules/prompt/functions/prompt_granzestyle_setup && ln -s ${ZIM_HOME}/modules/prompt/external-themes/oh-my-git/arialdo-pathinline.zsh-theme  ${ZIM_HOME}/modules/prompt/functions/prompt_pathinline_setup && ln -s ${ZIM_HOME}/modules/prompt/external-themes/oh-my-git/oppa-lana-style.zsh-theme ${ZIM_HOME}/modules/prompt/functions/prompt_oppa-lana_setup`
3. To use them, simply modify the value of `zprompt_theme` in the `zimrc`, which is at `~/.zimrc`. For example to use the granzestyle theme, it would look something like `zprompt_theme='granzestyle'` and a similar pattern for the others.

If you come across any more problems, feel free to ask for help!

**Comment by AtomicCoding** [comment]
@karambaq Can you run `nano ${ZIM_HOME}/modules/prompt/external-themes/oh-my-git/arialdo-granzestyle.zsh-theme` and press the down arrow until you get to where it says `function custom_build_prompt {` and modify it to `function build_prompt {`?


And if you get text that looks something like `$(build_prompt)$fg_bold[green]` then try running `setopt PROMPT_SUBST`, and if it still doesn't work, then try `unsetopt PROMPT_PERCENT` and if it still doesn't work, then it may be a problem with the prompt, not the settings set.

**Comment by Piping** [comment]
@AtomicCoding It is better to add a `zmanage` command that automatically does these things. I will write one.

**Comment by karambaq** [comment]
any updates?
