### ISSUE TITLE
history-substring-search doesn't work with minimal prompt

### ISSUE THREAD

**Issue by ishitatsuyuki** [zimfw/zimfw#286]
In a terminal, run `zmanage info` and paste the output below:

```
Zim commit ref:   9039549
Zsh version:      zsh 5.5.1 (x86_64-debian-linux-gnu)
System info:      Linux kclc.tk 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux
```

- gist of .zimrc: https://gist.github.com/ishitatsuyuki/348c1bf1768b9c3733ad36ebf61d61d5
- paste of .zshrc:

```
#
# user configuration sourced by interactive shells
#

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

export EDITOR=nano
```

Description
-----------
history-substring-search doesn't work with minimal prompt. Pressing `up` while typing something in the line just show the last command.

Steps to reproduce
------------------

Use the attached zimrc or do `prompt minimal`.

**Comment by ericbn** [comment]
These are the problematic lines:
```
function zle-line-init zle-keymap-select {
  zle reset-prompt
  zle -R
}

...

  zle -N zle-line-init
  zle -N zle-keymap-select
```

This is setting line editor widgets, and they seem to be conflicting with zsh-history-substring-search.

**Comment by ericbn** [comment]
@ishitatsuyuki, just updated our history-substring-search module. Please update zim and check if it fixes the issue for you.

**Comment by antoineco** [comment]
@ericbn although the keys look good (see below) this change broke the substring search in the MacOS Terminal.
```
❯ cat
^[[A^[[B
```
