### ISSUE TITLE
Add souce script support in custom module

### ISSUE THREAD

**Issue by wweir** [zimfw/zimfw#289]
Some tools have it own zsh support script, just like [git-extras](https://github.com/tj/git-extras/blob/master/etc/git-extras-completion.zsh) or [kubctl](https://github.com/kubernetes/kubernetes/tree/master/cmd/kubectl).
But I am not able to find a graceful way to add these scripts into zim custom module.

How about add source script support in custom/init.zsh?

**Comment by wweir** [comment]
It turns out to be not so necessary since adding these to mine `.zshrc`
``` shell
kubectl() {
	command kubectl $*
	if [[ -z $KUBECTL_COMPLETE ]]; then
		source <(command kubectl completion zsh)
		KUBECTL_COMPLETE=1
	fi
}
git(){
	command git $*
	if [[ -z $GIT_EXTRAS ]]; then
		if [[ "$OSTYPE" =~ "darwin" ]]; then
			COMPLETION=$(ls /usr/local/Cellar/git-extras/*/share/git-extras/git-extras-completion.zsh 2>/dev/null)
			if [[ ! -z $COMPLETION ]]; then
				source $COMPLETION
			fi
			unset COMPLETION
			GIT_EXTRAS=1
		fi
	fi
}
```

**Comment by AtomicCoding** [comment]
There's also the functions directory in any module, it runs the shell scripts in there whenever you type the file name as a command.

**Comment by wweir** [comment]
@AtomicCoding This means, I should run that shell script (in function way) before I using the command just like `git` `kubectl`. The user experience may be a bit poor.

**Comment by ericbn** [comment]
I cannot see the zsh support in the kubectl link you posted above.

For git-extras, I see [installation instructions using zplugin](https://github.com/tj/git-extras/blob/master/Installation.md#installing-as-zsh-plugin) and looks like it does not even support other less complex zsh plugin managers. @wweir, for this specific case of git-extras, I suggest you contribute with a PR to their project, adding a `init.zsh` (or `git-extras.zsh`, or `git-extras.plugin.zsh`) script that would initialize it as a zsh module.

**Comment by wweir** [comment]
@ericbn Sorry, `kubectl` completion script is generated by `kubectl`. It can be load by this command `source <(kubectl completion zsh)`
