### ISSUE TITLE
zssh module not working

### ISSUE THREAD

**Issue by shadez95** [zimfw/zimfw#290]
```
Zim commit ref:   
Zsh version:      zsh 5.5.1 (x86_64-unknown-linux-gnu)
System info:      Linux dixon-ManjaroDesktop 4.14.57-1-MANJARO #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC 2018 x86_64 GNU/Linux
```

- gist of .zimrc: https://gist.github.com/shadez95/8dd135d29bfec31610c970ed49d14634
- gist of .zshrc: https://gist.github.com/shadez95/3776f54a3c556543ab61c097402c00ed

Description
-----------
zssh module is not working. I have enabled the plugin and on start up, ssh-agent is not running.

FYI: This is my first time installing and using zsh so maybe I'm just a noob and haven't configured this properly.

Steps to reproduce
------------------
Start zsh improved

Images or other information
---------------------------
No other information

**Comment by AtomicCoding** [comment]
@shadez95 
* In order to enable modules, you need to add them to the `zmodules` array in the `zimrc`, so for example, the ssh module:
```
zmodules=(directory environment git git-info history input utility custom \
          prompt completion syntax-highlighting history-substring-search )
```
becomes
```
zmodules=(directory environment git git-info history input utility custom \
          prompt completion ssh syntax-highlighting history-substring-search )
```
* Along with that, it doesn't seem like your `zshrc` contains the neccessary code to start Zim, it should look like:
```
#
# User configuration sourced by interactive shells
#

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

export EDITOR=/usr/bin/nano
export VISUAL="nano"

# Krusader Configuration
export PATH=$PATH:/bin/kdiff3:/bin/kompare:/bin/thunderbird:/bin/krename:/bin/md5sum

# Go Configuration
export GOPATH=$HOME/workspace/go
export PATH=$PATH:$GOPATH/bin
```
not
```
export EDITOR=/usr/bin/nano
export VISUAL="nano"

# Krusader Configuration
export PATH=$PATH:/bin/kdiff3:/bin/kompare:/bin/thunderbird:/bin/krename:/bin/md5sum

# Go Configuration
export GOPATH=$HOME/workspace/go
export PATH=$PATH:$GOPATH/bin
```

**Comment by shadez95** [comment]
sorry for late reply, but I see what I did wrong and now it's working. Thank you very much for your help.
