### ISSUE TITLE
history-substring-search is broken with some terminals

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [zimfw/zimfw#293]
```
Zim commit ref:   fe2cb6b
Zsh version:      zsh 5.6.2 (x86_64-pc-linux-gnu)
System info:      Linux arch-tower 4.18.0-bcachefs #1 SMP PREEMPT Sun Sep 9 03:31:56 EDT 2018 x86_64 GNU/Linux
```

gists:
https://gist.github.com/DerVerruckteFuchs/78b28d3b6990a83a4347afc57d7762ea

After using `zmanage update`, the history-substring-search module no longer works with some terminals. Pressing up and down on the keyboard gives default history scrolling behavior between the most recently used commands. It's as if history-substring-search was never enabled for them. It doesn't work with termite or kitty. However, urxvt seems to not have any issues and history-substring-search works as expected.

Steps to reproduce
Use termite or kitty, update zim with `zmanage update`, then attempt to use history-substring search.

Images or other information
When updating I noticed the most recent commit changed how the keybinding was done:
https://github.com/zimfw/zimfw/commit/fe2cb6b9f5d3364c64079fbb833e0a7f6f5d545b. I commented out the new stuff in `~/.zim/modules/history-substring-search/init.zsh` and put back the replaced lines and history-substring-search works again with termite and kitty.

**Comment by Eriner** [comment]
run `zmanage clean-cache && zmanage build-cache` and, after closing and re-opening your terminal, is the issue still present?

**Comment by Eriner** [comment]
See: https://github.com/zimfw/zimfw/issues/286

**Comment by DerVerruckteFuchs** [comment]
I found out what the issue is. Termite and kitty seem to use a different keybinding for the up and down arrow keys. In urxvt the keybinding for up and down is `^[[A` and `^[[B` respectively. In kitty and termite up and down is ` ^[OA` and `^[OB` respectively. Editing the  keybinds in `~/.zim/modules/history-substring-search/init.zsh` with the ones kitty and termite use allows everything to work fine for kitty and termite, but it predictably does not work with urxvt.

**Comment by DerVerruckteFuchs** [comment]
I added some new keybindings in my `~/.zshrc`:
````
# change keybinds for kitty and termite
bindkey '^[OA'  history-substring-search-up
bindkey '^[OB'  history-substring-search-down
````
This let's me use history-substring-search in kitty and termite without changing `~/.zim/modules/history-substring-search/init.zsh`. I also tested adding the keybinds into the same `init.zsh` file, and it seems to work just fine.

**Comment by ericbn** [comment]
@DerVerruckteFuchs, just updated our history-substring-search module. Sorry for breaking this in the previous commit.
