### ISSUE TITLE
history-substring-search broken

### ISSUE THREAD

**Issue by antoineco** [zimfw/zimfw#295]
Environment Info
----------------
```
Zim commit ref:   fe2cb6b
Zsh version:      zsh 5.6.2 (x86_64-apple-darwin17.7.0)
System info:      Darwin WDFM34057164A 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

Description
-----------
History substring search does not work anymore after the changes from fe2cb6b9f5d3364c64079fbb833e0a7f6f5d545b.

Steps to Reproduce
------------------
1. Clone zim
2. Make sure `.zwc` files are deleted
3. Open a new terminal
4. Start typing a command from the history
5. Press Up

Zsh cycles through the history commands in order instead of jumping to the latest command containing the substring.

Images or other Information
---------------------------
I'm using `zinput_mode='vi'` but also tried with the `emacs` input mode.

My terminal emulator (macOS Terminal) reports `$terminfo[kcuu1]` and `$terminfo[kcud1]` as `^[OA` and `^[OB`.

Reverting the commit solves the issue for me.

**Comment by antoineco** [comment]
Re-opens #286

**Comment by ericbn** [comment]
@antoineco, just updated our history-substring-search module. Sorry for breaking this in the previous commit.

**Comment by antoineco** [comment]
No problem, thanks for the reactivity! I would never have thought such a simple thing could get so hairy :)
