### ISSUE TITLE
zstyle and zim

### ISSUE THREAD

**Issue by PierreMarchand20** [zimfw/zimfw#301]
Disclaimer: I have a really hard time to understand how everything works with zsh and I come from prezto.

I already posted an issue on the autosuggestion repos in the zimfw organisation, but for some reasons, there is also an autosuggestion module here. Are they the same ? anyway, the issue trackers are not

I would like to change the style of autosuggestion. In zpreztorc, there is a line to do it
zstyle ':prezto:module:autosuggestions:color' found 'fg=241'

But with zim, I do not know how to use the command `ztyle` with autosuggestion. Actually, it seems that I cannot use `zstyle` with any module coming from zim. For example, it is written that I could change some options from the git-info module using `zstyle` but it does not work either 

When I write zstyle in command line and search for autocompletion with tabulation, it only finds completion, vcs_info and zftp. Is there something to configure to be able to use it with zim ?

<img width="272" alt="capture d ecran 2018-10-10 a 13 07 00" src="https://user-images.githubusercontent.com/15056323/46732308-6c0c4a80-cc8d-11e8-8a82-6eacc9c3e2e8.png">

**Comment by ericbn** [comment]
@PierreMarchand20, add this to your `~/.zimrc` file:
```
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'
```
zim uses the zsh-autosuggestions module, and you can configure it as described here: https://github.com/zsh-users/zsh-autosuggestions#configuration

**Comment by PierreMarchand20** [comment]
Thank you for your answer ! Actually, I tried as you said but it does not work. Here's my .zimrc
```
#################
# CORE SETTINGS #
#################

#
# Zim settings
#

# Select what modules you would like enabled.
# The second line of modules may depend on options set by modules in the first
# line. These dependencies are noted on the respective module's README.md.
zmodules=(autosuggestions directory environment git git-info history input utility custom \
          prompt completion syntax-highlighting history-substring-search )


###################
# MODULE SETTINGS #
###################

#
# Autosuggestion
#

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'

#
# Prompt
#

# Set your desired prompt here
zprompt_theme='pure'

#
# Completion
#

# Set an optional host-specific filename for the completion cache file. If none
# is provided, the default '.zcompdump' is used.
#zcompdump_file=".zcompdump-${HOST}-${ZSH_VERSION}"

#
# Utility
#

# Uncomment to enable spelling correction prompt for commands. See:
# http://zsh.sourceforge.net/Doc/Release/Options.html#Input_002fOutput
#setopt CORRECT

# Set custom spelling correction prompt
#SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '

#
# Environment
#

# Set the string below to the desired terminal title format string.
# The terminal title is redrawn upon directory change, however, variables like 
# ${PWD} are only evaluated once. Use prompt expansion strings for dynamic data:
#   http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Simple-Prompt-Escapes
# The example below uses the following format: 'username@host:/current/directory'
ztermtitle='%n@%m:%~'

#
# Input
#

# Set to vi or emacs
zinput_mode='emacs'

# Uncomment to enable double-dot expansion. This appends '../' to your input for
# each '.' you type after an initial '..'
#zdouble_dot_expand='true'

#
# Syntax-Highlighting
#

# This determines what highlighters will be used with the syntax-highlighting module.
# Documentation of the highlighters can be found here:
#   https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
# For (u)rxvt, termite and gnome-terminal users,
# removing the 'cursor' highlighter will fix the disappearing cursor problem
zhighlighters=(main brackets cursor)


#
# SSH
#

# Load these ssh identities with the ssh module
#zssh_ids=(id_rsa)


#
# Pacman
#

# Set (optional) pacman front-end.
#zpacman_frontend='powerpill'

# Load any helper scripts as defined here
#zpacman_helper=(aur)
```

**Comment by PierreMarchand20** [comment]
Since it did not work, I thought we had to use zstyle in the `.zimrc` file instead

**Comment by ericbn** [comment]
@PierreMarchand20, my bad. Actually zsh-autosuggestions obliges users to set the configuration *after* the plugin is sourced, not before. In zim this means you'll have to set the configuration in `~/.zshrc` after zim is initialized.

I'm suggesting a upstream fix in for this in https://github.com/zsh-users/zsh-autosuggestions/pull/378

**Comment by PierreMarchand20** [comment]
Ok thanks ! And just out of curiosity, why can't we use zstyle as in prezto ? Be aware that the documentation of the git-info module in zim mentions using zstyle, which does not work either. Do you want me to open another issue about that ?
