### ISSUE TITLE
archive multiple files

### ISSUE THREAD

**Issue by Konfekt** [zimfw/zimfw#306]
Regarding 

https://github.com/zimfw/zimfw/blob/60b0910f6def220f1b115e3934088a6a21b538da/modules/archive/functions/archive#L1

it could be useful to be able to compress files instead of a single directory, have a look at

https://github.com/robbyrussell/oh-my-zsh/pull/6846/files

for a possible approach.

**Comment by ericbn** [comment]
Good idea, @Konfekt. I can work on it, or I'll be happy to look at a PR with this change if you're willing to do it.
