### ISSUE TITLE
prompt: prepend _ to functions

### ISSUE THREAD

**Issue by Konfekt** [zimfw/zimfw#307]
Typing`pro<tab>` in `zsh` gives as possible options all functions of all prompts in the theme and prompt module. How about prepending those with `_` to avoid cluttering the user's command completion options? After all, they are probably meant to be used internally.

**Comment by ericbn** [comment]
The `prompt_x_setup`, `prompt_x_help` and `prompt_x_preview` functions are used by zsh's `promptinit`. You're right about the others: they're only used internally.

We have a zstyle configuration in out completion module that ignores functions starting with `prompt_`, as well as functions starting with `_`: https://github.com/zimfw/zimfw/blob/35c5daf791b295b007ab09a69324a132a225da59/modules/completion/init.zsh#L74

<img width="570" alt="screen shot 2018-11-03 at 15 35 25" src="https://user-images.githubusercontent.com/4120606/47957201-85986d80-df7f-11e8-91ff-9241249137ac.png">

**Comment by Konfekt** [comment]
Thanks for the hint about completions. Now I have

zmodules=(directory environment history input git-info prompt completion)

but still

![image](https://user-images.githubusercontent.com/7195553/47958404-dc1aa180-dfa9-11e8-93b8-95b6972f35c6.png)

**Comment by ericbn** [comment]
Cannot reproduce this or #309, which you also reported. Maybe you have something else going on with your setup.

**Comment by Konfekt** [comment]
Thank you, this one has been hunted down: it was the line
```sh
# Ignore completion functions for commands you don't have:
zstyle ':completion::(^approximate*):*:functions' ignored-patterns '_*'
```
