### ISSUE TITLE
question: where to set fpath

### ISSUE THREAD

**Issue by Konfekt** [zimfw/zimfw#309]
To add custom completions, `fpath` has to be set to include the path of the custom completions. This would not have any effect without calling `compint` after setting `fpath` anywhere in `.zlogin` or `.zshrc`. However, `.zprofile` works, as it is loaded BEFORE `.zshrc`. How come, and where would be the most appropriate spot to add a path to`fpath` ?

**Comment by Konfekt** [comment]
Note that setting `fpath` in `.zshenv` (even `.zprofile` which is meant for login shells) does not seem appropriate to me, as it is for non-interactive shells, and completion is a feature useful primarily in interactive shells.

**Comment by ericbn** [comment]
You can add your custom completions path to `fpath` in the `.zshrc` file, but you'll have to do it before the line that sources the zim init script.

If you have zim's completion module enabled, this module will call compinit. So after zim init script is done executing, compinit will already have been called. And that is why changing `fpath` after zim is sourced will have no effect in the completions.

**Comment by Konfekt** [comment]
I entirely agree with your reasoning, but putting
```sh
fpath+=("$ZDOTDIR/completions")

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh
```
into `.zshrc` does NOT source the completions, whereas putting the first line into `.zprofile` does so, inexplicably.

**Comment by Konfekt** [comment]
Yes, now I did. Do I have to close all open shells? Or just open a new one after `zmanage clean-cache`? Everything works as expected, except that necessarily the `fpath` has to be set in `.zprofile` and not in `.zshrc` before `[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh`.

**Comment by ericbn** [comment]
Cannot reproduce your issue.

How I tested locally:
1. Added a file called `_foo` in `/tmp/functions` with these contents:
    ```
    #compdef foo

    service=git; _git
    ```
2. Added this to my `~/.zshrc` before the sourcing of Zim:
    ```
    fpath+=(/tmp/functions)
    foo() { git }
    ```
3. Cleared my completion cache and started a new shell session.
4. Changed to a git repo directory and typed `foo -`<kbd>Tab</kbd>. Got the git completion!
    <img width="743" alt="screen shot 2018-11-20 at 16 32 46" src="https://user-images.githubusercontent.com/4120606/48805192-b6e59d00-ece4-11e8-85c7-8e977218251b.png">

**Comment by Konfekt** [comment]
With 

- `/etc/zshenv` empty,
- `/etc/zshrc` being the default of OpenSUSE 15,
- `/etc/zprofile` empty,
- `/etc/zlogin` non-existent,
- `.zprofile` empty, 
- `.zlogin` reading
```
# Initialize zim
[[ -s ${ZIM_HOME}/login_init.zsh ]] && source ${ZIM_HOME}/login_init.zsh
```
- `.zhsenv` reading
```
ZDOTDIR="$XDG_CONFIG_HOME"/sh/zsh
```
- `.zshrc` reading
```
fpath+=("$ZDOTDIR/zsh.d/completions.d")
# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh
```
there is no completion for the commands in fpath.

**Comment by Konfekt** [comment]
Yes, for example https://raw.githubusercontent.com/pimutils/khal/master/misc/__khal

**Comment by ericbn** [comment]
@Konfekt, is this still an issue?

**Comment by Konfekt** [comment]
Yes, moving 

```sh
fpath+=("$ZDOTDIR/zsh.d/completions.d")
```

from `.zlogin` to `.zshrc` before

```sh
# Initialize modules
if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  # Update static initialization script if it's outdated, before sourcing it
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh
```
 
and hitting `<tab>` after `khal l` completes to a directory name starting with `l` instead of `list`.

**Comment by Konfekt** [comment]
Has the `zmanage` command changed its name? `zmanage clean-cache` gives `command not found`.

**Comment by ericbn** [comment]
@Konfekt, check the [Changelog here](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md). You might also want to double check the `.z*` files templates at https://github.com/zimfw/install/tree/master/src/templates in comparison with your own files.

I still don't see where Zim could be related to your fpath issue.

> `.zhsenv` reading

Is the file really named `.zhsenv` or was it a typo here? It should be called `.zshenv`

**Comment by Konfekt** [comment]
> Is the file really named .zhsenv or was it a typo here? It should be called .zshenv

A typo. It is `.zshenv`. 

The `zmanage` tool was removed, but no hint is given to clean the cache now. 

It is unrelated to Zim now. 

Just the observation that `fpath` needs to be set in `.zshenv` or `.zprofile` for the completions to work, but these do not seem appropriate to me, as it is for non-interactive shells, and completion is a feature useful in interactive shells.

It is only curious that this happens over here. Perhaps updating from `zsh 5.6` resolves this.

**Comment by ericbn** [comment]
I kind of regret now that I renamed zmanage to zimfw in the new release. We had an [almost one year open discussion](https://github.com/zimfw/zimfw/pull/323) on the new release, and it seemed a good or at least harmless idea back then, or it went unnoticed...

**Comment by Konfekt** [comment]
You shouldn't. It is important to know that this command is part of the zimfw, and its new name couldn't be more telling. In any event, running `zimfw clean` did (somewhat expectedly) not resolve the issue.

**Comment by Konfekt** [comment]
Well, above I wrote that `/etc/zshrc` was empty when the issue was filed, but now it can be traced back to 

```sh
autoload -U compinit
compinit
```

being in it on openSUSE 15.1.

**Comment by ericbn** [comment]
Maybe we could have a `zimfw doctor` action that reports known issues like the one you just found out (completion module is enabled and compinit in being called somewhere else, in this case).
