### ISSUE TITLE
input module: bad set of key/value pairs for associative array

### ISSUE THREAD

**Issue by Brottweiler** [zimfw/zimfw#310]
```bash
Zim commit ref:   60b0910
Zsh version:      zsh 5.6.2 (x86_64-pc-linux-gnu)
System info:      Linux noname 4.18.17-2-ck-haswell #1 SMP PREEMPT Sun Nov 4 14:41:32 EST 2018 x86_64 GNU/Linux
```

- gist of .zimrc: [zimrc](https://gist.github.com/60ddbe18f59fdeb1dd049e40992c57f1#file-zimrc)
- gist of .zshrc: [zshrc](https://gist.github.com/60ddbe18f59fdeb1dd049e40992c57f1#file-zshrc)

Description
-----------
This error message shows up when I run [simple terminal](https://st.suckless.org/) (st) terminal emulator, but not when I use [Termite](https://github.com/thestinger/termite). I noticed this because I started using st today.

```bash
/home/brott/.zim/modules/input/init.zsh:14: bad set of key/value pairs for associative array
```

I'm not sure why it shows up in st and not other emulators.

Steps to reproduce
------------------
Run st with zim installed and input module enabled, which it should be by default.

**Comment by Plloi** [comment]
depending on how you installed st you might not have terminfo entries. see here: https://git.suckless.org/st/file/FAQ.html#l5

**Comment by Brottweiler** [comment]
Oh, interesting. For the record:

```bash
/usr/share/terminfo/s/st
/usr/share/terminfo/s/st-0.6
/usr/share/terminfo/s/st-0.7
/usr/share/terminfo/s/st-16color
/usr/share/terminfo/s/st-256color
/usr/share/terminfo/s/st-direct
/usr/share/terminfo/s/st52
/usr/share/terminfo/s/st52-color
/usr/share/terminfo/s/st52-m
/usr/share/terminfo/s/st52-old
/usr/share/terminfo/s/stterm
/usr/share/terminfo/s/stterm-16color
/usr/share/terminfo/s/stterm-256color
/usr/share/terminfo/s/stv52
/usr/share/terminfo/s/stv52pc
```

Then I have this in `config.h`
```c
/* default TERM value */
char *termname = "st-256color";
```

I am using Arch and installed st from AUR, so I didn't do any `make install`.
