### ISSUE TITLE
[git] Convert one-liner functions to aliases and longer ones to git subcommands

### ISSUE THREAD

**Issue by kiryph** [zimfw/zimfw#314]
I would like to use the shell functions from the git module as `$ g <subcommand>` (with the alias `g` for `git`) and not, e.g. `$ git-dir`.

The one liners (e.g. `git-dir`, `git-root`) could actually be converted to git aliases if I am not mistaken.
I am not sure how zimfw could register them.

Others would have to be converted to proper shell scripts which git can find and call. Git officially supports custom subcommmands.
This is documented under https://github.com/git/git/blob/master/Documentation/howto/new-command.txt and there are many google results for `git own subcommand`.

However, doing this right might be a little bit more than simply converting them to standalone shell scripts: setting up completion and also a manpage describing the command would be great.

I guess https://github.com/tj/git-extras could be considered as an example.

What are the thoughts of others?

**Comment by ericbn** [comment]
The one-liners are `git-branch-current` and `git-root` and I agree with making them aliases instead. Not sure if we can convert `git-dir` to a one-liner too. Maybe if we give up making it always print the absolute path. Or if we use `--absolute-git-dir`, but that's only available starting from git v2.13.0.

You have a good point with using git subcommands. Our "motto" in Zim is to look for the simpler and faster solutions. The only function we have using completion is `git-branch-delete-interactive`. If setting up its completion would be easier in case it were a git subcommand, for example, that would already be a con of using subcommands.

@kiryph, do you want to give this a try and submit separate PRs for the aliases and the subcommands?
