### ISSUE TITLE
request:agnoster+fish style short prompt

### ISSUE THREAD

**Issue by myfreess** [zimfw/zimfw#317]

**Comment by ericbn** [comment]
The `eriner` theme looks like agnoster. You can even configure it to use the same colors with:

    zprompt_theme='eriner black blue'

I've ported agnoster to Zim here: https://github.com/ericbn/agnoster/blob/master/prompt_agnoster_setup

**Comment by myfreess** [comment]
Not only agnoster,but also want prompt like fish-shell,the directory info very short @ericbn

**Comment by ericbn** [comment]
@myfreess, can you please elaborate "also want prompt like fish-shell" and "the directory info very short"?

"like fish-shell" in exactly which of its behaviors?

Which "the directory"? Which "the directory info"?

"very short" compared to what?

[The best way](https://github.com/zimfw/zimfw/pull/79) [to contribute](https://github.com/zimfw/zimfw/pull/81) [is creating](https://github.com/zimfw/zimfw/pull/84) [a Pull Request](https://github.com/zimfw/zimfw/pull/89) [with what](https://github.com/zimfw/zimfw/pull/90) [you would like](https://github.com/zimfw/zimfw/pull/101) [to have](https://github.com/zimfw/zimfw/pull/104). Mainly if you're not good with words.

**Comment by ericbn** [comment]
We have a function called `short_pwd` in our `prompt` module that will give you your "fish simple prompt". Most of our Zim prompt themes use it, including the `eriner` theme I mentioned before. Check https://github.com/zimfw/zimfw/wiki/Themes for the list of available Zim themes.

Again, use this in your `.zimrc` to have what you're asking for:

    zprompt_theme='eriner black blue'

Then start a new shell session.

<img width="360" alt="screen shot 2018-12-24 at 09 29 19" src="https://user-images.githubusercontent.com/4120606/50401707-a189e580-075e-11e9-88b6-6aeaa521b62b.png">
