### ISSUE TITLE
Highlight conflict between autosuggestions and syntax-highlighting modules

### ISSUE THREAD

**Issue by gzrjzcx** [zimfw/zimfw#321]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
Zim commit ref:   1ab110c
Zsh version:      zsh 5.3 (x86_64-apple-darwin18.0)
System info:      Darwin Zous-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```
- gist of .zimrc:
- gist of .zshrc:

Description
-----------
When I enable both autosuggestions and syntax-highlighting modules together, the commands are highlighted not correctly. It always only have the letter after the current cursor position is highlighted, in fact, the correct result is all of the suggested contents(untyped but suggested letters) are highlighted (in my situation, I use dark green to highlight).

If I only enable the autosuggestions, all of the suggested contents are highlighted correctly. It looks like that the auto-suggested contents are re-highlighted by the syntax-highlight? 
How can I control which module is executed firstly?

Steps to reproduce
------------------

Images or other information
---------------------------

![2018-12-31 5 47 26](https://user-images.githubusercontent.com/33338567/50565196-30c96700-0d24-11e9-9d4b-51db1505c640.png)
As you can see, only letter 'S' was highlighted correctly, I guess that maybe other letters are re-highlighted by the syntax-highlight module, but how can I solve it? Thanks

**Comment by Brottweiler** [comment]
I have both those modules enabled and nothing seems highlighted for me 
![image](https://user-images.githubusercontent.com/1613137/50565295-a7b72d80-0d2d-11e9-9c3b-86cb00582a3e.png)

**Comment by gzrjzcx** [comment]
After I canceled the cursor syntax-highlighter option, it works for me now!
<img width="672" alt="2018-12-31 5 58 05" src="https://user-images.githubusercontent.com/33338567/50565328-a550d580-0d25-11e9-8c04-5bda37d8a833.png">

**Comment by gzrjzcx** [comment]
> I have both those modules enabled and nothing seems highlighted for me
> ![image](https://user-images.githubusercontent.com/1613137/50565295-a7b72d80-0d2d-11e9-9c3b-86cb00582a3e.png)
> 
> Oh, and if I remove the ending so it thinks it's a command it gets highlighted correctly
> ![image](https://user-images.githubusercontent.com/1613137/50565308-dc2ae980-0d2d-11e9-94e1-aa771084c9a0.png)

I don't know, but I have found the solution! Thx~

**Comment by gzrjzcx** [comment]
> > I have both those modules enabled and nothing seems highlighted for me
> > ![image](https://user-images.githubusercontent.com/1613137/50565295-a7b72d80-0d2d-11e9-9c3b-86cb00582a3e.png)
> > Oh, and if I remove the ending so it thinks it's a command it gets highlighted correctly
> > ![image](https://user-images.githubusercontent.com/1613137/50565308-dc2ae980-0d2d-11e9-94e1-aa771084c9a0.png)
> 
> I don't know, but I have found the solution! Thx~

Maybe you only change the highlight colour?

**Comment by ericbn** [comment]
@Brottweiler, what you show in your screenshot is expected. An assignment gets [no highlighting by default](https://github.com/zsh-users/zsh-syntax-highlighting/blob/1e34c4aa0bcbdde5173aab15600784edf0a212fd/highlighters/main/main-highlighter.zsh#L58). An incomplete command gets is made [red and bold by default](https://github.com/zsh-users/zsh-syntax-highlighting/blob/1e34c4aa0bcbdde5173aab15600784edf0a212fd/highlighters/main/main-highlighter.zsh#L33).
