### ISSUE TITLE
Feature: Add spaceship-prompt

### ISSUE THREAD

**Issue by shizonic** [zimfw/zimfw#324]
Please add a new external prompt:
https://github.com/denysdovhan/spaceship-prompt

**Comment by ericbn** [comment]
@shizonic, you can use the new develop branch of Zim to easily add any external modules to your installation. See #323 and see https://github.com/zimfw/zimfw/tree/develop 

Let me know if you can figure out how to configure it with the existing documentation there.

**Comment by shizonic** [comment]
@ericbn Thx this looks awesome. I will go into it and make a PR once I found a solution.

Great work btw!

**Comment by Plloi** [comment]
@shizonic  the point of thew plugin system is to make it so users can more easily add new plugins to their local install while keeping the base zimfw repo lean and mean. i don't use spaceship so if it's acting wonky i won't notice, but i was able to add it in seconds under the new system, and it (seemed, to me) to work fine. No porting needed.

**Comment by shizonic** [comment]
@Plloi Thanks. Couldn't try it yet but looks promising. Where  did you customize the prompt? Inside zimrc?

**Comment by Plloi** [comment]
FYI the dev branch moves zims config to ztyles
Yeah, in zimrc add spaceship to the modules to the zim modules zstyle.

Add a zstyle for the spaceship module:
`zstyle ':zim:module' spaceship 'url' 'denysdovhan/spaceship-prompt'`

run `zimfw install`

Set the prompt

restart shell

**Comment by shizonic** [comment]
Thx. Did recognize this already.

I guess you missunderstood (or I asked wrong) but I know how to install. I was talking about customization using options provided by the prompt: https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/Options.md.

**Comment by Plloi** [comment]
I'll take the misunderstood on that one. Looks like spaceship's configuration is all done with env vars so you should be able to load lem from wherever makes the most sense to you. Beting that it's loading it with zim I would put them in the zimrc, but that's me

**Comment by shizonic** [comment]
Thanks once again. I'll gonna try it and report. You helped me a lot ! :)

**Comment by ericbn** [comment]
I'm glad to see it was straightforward to figure out how to configure it with the provided examples and documentation.

About extra configuration for each plugin/prompt sourced, there are basically two variations:
1. some you must configure **after** they are sourced,
2. some others you can configure **before** they are sourced (some you can do either before or after, and for those I prefer doing before too)

For Zim this means:
1. must configure **after**: it must be in the `.zshrc` after Zim is sourced.
2. can configure **before**: can be in the `.zshrc` before Zim is sourced, or in the `.zimrc`. This is because internally the `.zimrc` is sourced before the modules are sourced.

---

More thoughts on this for the new develop version:

There's a discussion in #288 about not having a `.zimrc` file, and having everything in the `.zshrc`.

I think there's a good point to this idea, since it would be clearer where to do the plugins/themes configurations in terms of **after** or **before** as there would be only one place to do it -- the `.zshrc` file -- and then in relation to the line where Zim is sourced.

On the other hand, the new Zim implementation sources the `.zimrc` before `zimfw install` or `zimfw update`, so you can enable/disable modules and then install/update them in the same shell session. I'm thinking a good balance here could be having only the `':zim' modules` and `':zim:module' <module>` zstyles in the `.zimrc` and all the rest in the `.zshrc` file.

Thoughts? @Eriner, what do you think?

**Comment by shizonic** [comment]
@ericbn Thx. I'll switch to https://github.com/zimfw/zimfw/pull/288 ...

**Comment by shizonic** [comment]
If I set my prompt theme to space and reload my shell I get
```
Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.
```
If I list the available prompts "spaceship" is missing:
```
prompt -l
Currently available prompt themes:
adam1 adam2 bart bigfade clint default elite2 elite fade fire off oliver pws redhat restore suse walters zefram
```
But actually the prompt get's loaded! I am on the spaceship prompt.
Relevant parts from .zimrc:
```
# Select what modules you would like enabled. Modules are sourced in the order given.
zstyle ':zim' modules \
    directory environment git git-info history input utility ssh \
    spaceship prompt \
    zsh-completions completion zsh-autosuggestions zsh-syntax-highlighting history-substring-search

# Modules setup configuration.
# See ...
zstyle ':zim:module' zsh-completions 'url' 'zsh-users/zsh-completions'
zstyle ':zim:module' zsh-autosuggestions 'url' 'zsh-users/zsh-autosuggestions'
zstyle ':zim:module' zsh-syntax-highlighting 'url' 'zsh-users/zsh-syntax-highlighting'
zstyle ':zim:module' spaceship 'url' 'denysdovhan/spaceship-prompt'
```
... and ...
```
#
# prompt
#

# Set your desired prompt theme.
zstyle ':zim:prompt' theme 'spaceship'
```
... and my .zshrc to configure space prompt ...
```
#
# User configuration sourced by interactive shells
#

# Define Zim location
ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start Zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  ruby          # Ruby section
  elixir        # Elixir section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  haskell       # Haskell Stack section
  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  venv          # virtualenv section
  conda         # conda virtualenv section
  pyenv         # Pyenv section
  dotnet        # .NET section
  ember         # Ember.js section
  kubecontext   # Kubectl context section
  terraform     # Terraform workspace section
  exec_time     # Execution time
  line_sep      # Line break
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
 )
```
What did I miss? Any suggestions?

**Comment by Plloi** [comment]
did you run `zimfw install` after adding spaceship to your .zimrc?

**Comment by shizonic** [comment]
@Plloi Of course.

**Comment by ericbn** [comment]
@shizonic, see https://github.com/zimfw/zimfw/blob/develop/README.md#prompt-theme

denysdovhan/spaceship-prompt does not have a prompt_spaceship_setup file, but a spaceship.zsh file instead. So it works like item 2 in the docs, not like item 1. I should probably make this clearer as a comment in the zimrc template.

**Comment by ericbn** [comment]
@shizonic, right. The prompt module and it's specific configuration are not needed in this case.

Actually most themes out there will not be supported by our prompt theme. Mostly because most people are still coding for Zsh as it was 10 years ago...

**Comment by shizonic** [comment]
@ericbn Thank you so much. I'll gonna try it asap but unfortunately I got heavy flu and are just sleeping the whole day. Will report after I testet it.

In the meanwhile another question:
I have a zshrc.d directory where I have my additional zsh configs.Should I source the **before** or **after** zimfw gets sourced inside zshrc? I guess after...

**Comment by denysdovhan** [comment]
Hi folks, I'm creator of Spaceship ZSH 👋 

We have a PR which adds instructions to install Spaceship ZSH along with zim: https://github.com/denysdovhan/spaceship-prompt/pull/602

Could anyone take a look and help us improve this instruction? Seems like you're migrating to zstyle configs, right?
