### ISSUE TITLE
Prompt customization

### ISSUE THREAD

**Issue by WyRe** [zimfw/zimfw#327]
I just want to ask if is there an easy way (like config parameters) to modify the prompt themes. In the other hand ... should I modify code [in here](https://github.com/zimfw/zimfw/tree/master/modules/prompt) to customize my prompt? 

Which one would be the most appropriate way to customize the prompt?

**Comment by PatTheMav** [comment]
Good question - @ericbn, I've just pushed an update to https://github.com/PatTheMav/minimal2 (the "standalone" variant) adding `zstyle` configuration support. Is that _roughly_ the way you'd like this to work for zim plugins as well?

(I also did some `zstyle` related changes to https://github.com/PatTheMav/zimfw-extras so I'd appreciate to have some guidance on this).

**Comment by ericbn** [comment]
@PatTheMav, using zstyle or environment variables is up to your linking. The new Zim modules use zstyle. I still find prompts can take extra advantage of environment variables, and most (if not all) prompts implemented out there use them for configuration (including subnixr's minimal).

At this point you're probably thinking "WTF".  :- )  Do as you prefer. And use your good sense. I think developing a good coding style is also about that. I'm trying to use what makes the code cleaner, and not making up rules just for the sake of it.

Using zstyle has the advantage of the zstyle command offering nice options to check if option is set, if it's a "truthy" boolean, converting to string, to array, etc. Also zstyle offers ways of "contextualizing" the options. All nice things the average module can use, also because we usually have many modules enabled at the same time.

Environment variables have the advantage of just needing a `${VAR}` to be read, which is something nice to use in prompts, where you can refer to them directly instead of having to read all in local variables. You can have a simpler code that does things like `PS1='%F{${PROMPT_COLOR}}%#%f` and that's it, for example. Also no need for "contextualizing" prompt options, as we only have one prompt enabled at a time.

**Comment by ericbn** [comment]
Hola @WyRe. My comment above is mainly regarding changes we're doing in the develop branch on Zim. Be aware that big (and we believe good) changes are coming, but don't worry about them for you current needs of customizing one of the Zim prompt themes.

You pointed to the right place where the prompt theme implementations are. Some prompts are already customizable:
* [magicmace](https://github.com/zimfw/zimfw/blob/master/modules/prompt/themes/magicmace.zsh-theme) takes environment variables.
* [minimal](https://github.com/zimfw/zimfw/blob/master/modules/prompt/themes/minimal.zsh-theme) also takes environment variables.
* [eriner](https://github.com/zimfw/zimfw/blob/master/modules/prompt/themes/eriner.zsh-theme) takes prompt options. You can do like `zprompt_theme='eriner black blue'`
* [steeef](https://github.com/zimfw/zimfw/blob/master/modules/prompt/themes/steeef.zsh-theme) also takes prompt options.

If these are not good enough for you, you can either propose changes to the themes to make them more customizable, or you can create your own personal changes and keep them.
 
(The minimal theme is being renamed to s1ck94 in Zim's develop branch, and @PatTheMav is taking care of the new minimal prompt.)

**Comment by WyRe** [comment]
Hi @ericbn. Thank you for your answer. 

But now I'm wondering what will happen if I modify those files in my cloned repo when I try to pull your changes. Maybe is not a good idea modify those files locally, right?

**Comment by PatTheMav** [comment]
@WyRe As @ericbn mentioned `zim` is currently in a transitioning period that will make this topic a whole lot easier.

With current `zim` the easiest way might be to clone the original prompt somewhere to your liking, apply the changes, then symlink the prompt's folder into the `zim` module's folder under a new name.

As the original module should never contain any changes to your new folder name, any `git pull` will ignore your symlink and you can freely play around with your own prompt (that's how I made minimal2/minimal work).

If I'm not mistaken, on the develop branch you should be able to do something similar, just install your custom prompt as a "local" module. Or you clone the prompts repo into your account, then add that one as a module to your `zim` config.

My advice would be to (carefully!) switch to the develop branch and get things going there.

**Comment by PatTheMav** [comment]
> @PatTheMav, using zstyle or environment variables is up to your linking. The new Zim modules use zstyle. I still find prompts can take extra advantage of environment variables, and most (if not all) prompts implemented out there use them for configuration (including subnixr's minimal).
> 
> At this point you're probably thinking "WTF". :- ) Do as you prefer. And use your good sense. I think developing a good coding style is also about that. I'm trying to use what makes the code cleaner, and not making up rules just for the sake of it.
> 
> Using zstyle has the advantage of the zstyle command offering nice options to check if option is set, if it's a "truthy" boolean, converting to string, to array, etc. Also zstyle offers ways of "contextualizing" the options. All nice things the average module can use, also because we usually have many modules enabled at the same time.
> 
> Environment variables have the advantage of just needing a `${VAR}` to be read, which is something nice to use in prompts, where you can refer to them directly instead of having to read all in local variables. You can have a simpler code that does things like `PS1='%F{${PROMPT_COLOR}}%#%f` and that's it, for example. Also no need for "contextualizing" prompt options, as we only have one prompt enabled at a time.

@ericbn Yeah, environment variables seem to be the "accepted" way to do it, even though `zstyle` feels more `zsh`-ish. I also hate polluting the `ENV`, but that ship has sailed decades ago it seems. 😂 Also this means that there's still some contextualization (as prompts do not use commonly agreed ENV names).

Supporting both "works", but the code looks unnecessarily messy, so I'll probably revert/clean up my changes. I have a few ideas how to "unify" prompt configs using `zstyle`, none of them elegant enough to my liking though.

**Comment by ericbn** [comment]
@PatTheMav, I did similar experiments as you but, with env variables vs. parameters (`"%{@}"`), using one, the other, or a combination of both, and at the end just using env variables gave me a much simpler code I was happier with. I generalized that experience to the idea that env variables vs. zstyle would yield the same results...  :- )

I also hate polluting the env, but even so I ended up convinced that env variables fit prompt code's well.

**Comment by ericbn** [comment]
@WyRe, not sure if your doubts were completely answered.

> Maybe is not a good idea modify those files locally, right?
>
> I mean, ... should I make a fork? or something like this?

The develop branch of Zim solves the questions above in two ways:

* ZIM_HOME is not a git repo anymore. So you can add it to your dotfiles repo or manage it the way you prefer. Also you can use "local" modules, and they'll work fine and not interfere with other modules or Zim itself. By "local" module I mean (for a custom prompt theme for example):

      mkcd ${ZIM_HOME}/modules/my-prompt
      vi my-prompt.zsh-theme

* Each module, if not "local", is managed as an independent git repo. So first you can pick a much wider selection of modules out there, including [prompt themes](https://github.com/unixorn/awesome-zsh-plugins/blob/master/README.md#themes). Also you can create your own module repo (for a custom prompt theme for example):

      mkcd ${ZIM_HOME}/modules/my-prompt
      vi my-prompt.zsh-theme
      git init
      gia .
      gcm "First commit"
      gRa origin git@github.com:WyRe/my-prompt.git
      gpc

   You can even update your repo from another place, and use `zimfw update` to have Zim update it for you in the current Zim installation.

**Comment by ericbn** [comment]
@WyRe, muy buena decisión de aguardar la nueva versión.  :- )

**Comment by ericbn** [comment]
@WyRe, FYI Zim 1.0.0 is out.

**Comment by WyRe** [comment]
@ericbn I'm using [this package](https://aur.archlinux.org/packages/zsh-zim-git/) which I guess is building the last changes every time I reinstall it :blush:

**Comment by ericbn** [comment]
@ishitatsuyuki, are you the maintainer of the aur package?

> Since the upstream doesn't like zimfw getting packaged for global installation, and porting seems to be harder with the latest template changes, I'm going to stop maintaining this package. Contributions are still welcome.

Zim is just a "self-upgradable" single file now. And it expects to be in the root of ZIM_HOME. The latest release can always be downloaded from https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh or https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh.gz. And the templates moved to https://github.com/zimfw/install/tree/master/src/templates. Not sure how all this impacts the distribution, but just wanted to give you a heads up.

**Comment by ericbn** [comment]
Maybe it makes more sense to install Zim with the instructions under our README.md now: https://github.com/zimfw/zimfw/blob/master/README.md#installation

**Comment by WyRe** [comment]
@ericbn but I prefer a system wide/global installation :thinking:

**Comment by ishitatsuyuki** [comment]
@ericbn Thanks for the heads up. The primary issue for packaging is that the framework expects ZIM_HOME to be writable (in order to install modules), which mostly defeats the purpose of using a package manager (think: `sudo pip install`).

I think this is a reasonable move though, along with the monolithic management script.

**Comment by ericbn** [comment]
@WyRe, the changes in the new version should not prevent you from having a system-wide installation. See #368, where the discussion about the aur package continues.
