### ISSUE TITLE
Feature: fzf module

### ISSUE THREAD

**Issue by rjcoelho** [zimfw/zimfw#330]
https://github.com/junegunn/fzf is a command-line fuzzy finder. Check https://github.com/gpanders/fzf-prezto

**Comment by axsk** [comment]
I manually installed fzf and sourced its zsh keybindings.
But when I try to use its ** tab completion feature, it seems some other part of zsh-completion / zim is interrupting it. Can I somehow disable the default ** completion?

**Comment by Plloi** [comment]
@axsk  if you're on the current zim master you can remove completion from the zmodules array in ~/.zimrc and restart your terminal

**Comment by PatTheMav** [comment]
@ericbn I guess this can be closed with the plugin system in place?
