### ISSUE TITLE
[theme] Consider including Powerlevel10k theme

### ISSUE THREAD

**Issue by lnicola** [zimfw/zimfw#335]
https://github.com/romkatv/powerlevel10k

**Comment by p1g30n** [comment]
@lnicola The install instructions here work for me with with powerlevel10k as well when edited correspondingly: https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#option-9-install-for-zim

**Comment by ericbn** [comment]
@lnicola, [as I've mentioned before](https://github.com/zimfw/zimfw/issues/324#issuecomment-453327455), you can use the new develop branch of Zim to easily add any external modules to your installation. See #323 and see https://github.com/zimfw/zimfw/tree/develop

If you don't want to use Zim's bleeding edge code, I second @p1g30n's suggestion.

And these are my thoughts about adding a new prompt theme to Zim's master branch. [As](https://github.com/zimfw/zimfw/pull/253#issuecomment-378261784) [I've](https://github.com/zimfw/zimfw/pull/233#issuecomment-355859662) [stated](https://github.com/zimfw/zimfw/pull/192#issuecomment-308272617) [before](https://github.com/zimfw/zimfw/pull/192#issuecomment-331748148):

> I still think that the themes that come with zim, alongside our git-info module, provide a good basis for users to customize their own themes, and that we should not include variations of the already existing themes to our repo.

**Comment by lnicola** [comment]
Got it, thanks.

The main thing of interest to me in that theme was `[gitstatusd](https://github.com/romkatv/gitstatus)`, which could be useful for all of Zim's themes, but I suppose that's a different story. Would you consider adding support for it? I don't know enough about ZSH to make a PR.
