### ISSUE TITLE
cannot input `//` in script command.

### ISSUE THREAD

**Issue by kmahyyg** [zimfw/zimfw#340]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
Zim commit ref:   3fdccce
Zsh version:      zsh 5.7.1 (x86_64-debian-linux-gnu)
System info:      Linux tryharder 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-1kali1 (2019-08-19) x86_64 GNU/Linux
```

- gist of .zimrc:

Default one

- gist of .zshrc:

Default one

Description
-----------

Check the photo below.

Images or other information
---------------------------

![image](https://user-images.githubusercontent.com/16604643/63517218-23662480-c521-11e9-8e55-45659ed6c29f.png)

Bash or Another User's ZSH without any config is working.

How to get rid of this error?

I tried `'//10.10'` `"//10.10"` `\/\/10.10` , please help me.

**Comment by Plloi** [comment]
...have you tried simply `//10.10.10.63` ?

**Comment by kmahyyg** [comment]
Of course, but not work. Same notice.

**Comment by Plloi** [comment]
I figured, but since you didn't call it out i had to ask.

**Comment by Plloi** [comment]
what happen it you run: `echo //10.10.10.63` ?

**Comment by kmahyyg** [comment]
![image](https://user-images.githubusercontent.com/16604643/64484049-6de4e200-d23f-11e9-8119-5feaa59a317a.png)


seems no problem. Maybe I need to reproduce it using the same program call?

**Comment by Plloi** [comment]
Just trying to narrow down where the issue would be... if it was  zim/zsh i would have expected that to fail too...
