### ISSUE TITLE
my .zprofile is not  being loaded, and configuration for su not loaded

### ISSUE THREAD

**Issue by kronikpillow** [zimfw/zimfw#342]
hi there, first time using this framework, wanted to try it out ... so first I notice it doesn't come with a .zprofile, so I linked my symlinked .profile to .zprofile ... and it's still not being sourced after a reboot ... what could I be doing wrong?

another thing, when i su to my root user, the configuration is not being loaded at all, even thou I have symlinked the main user config files to the root user directory

any tips on what I might be doing wrong?

and a qestion, is this framework extensible? aka can i install modules from other frameworks here?

**Comment by Plloi** [comment]
what's not being loaded? zim? if so, what steps did you take to install it?

also it would help use help you if you could please provide the following information:

- In a terminal, run `zmanage info` and provide the output
- gist of .zimrc
- gist of .zshrc



As for for extensionability, you can add other frameworks modules, but it is a fairly manual process, there is progress being made on the development branch to simplify this process.

**Comment by ericbn** [comment]
@kronikpillow, can we close this?

**Comment by kronikpillow** [comment]
yes yes, I forgot totally about this :)
