### ISSUE TITLE
enable pure theme will produce two conda base env name on prompt

### ISSUE THREAD

**Issue by yetangye** [zimfw/zimfw#346]
```
Zim commit ref:   954f53d
Zsh version:      zsh 5.5.1 (x86_64-redhat-linux-gnu)
System info:      Linux srv-db 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Description
-----------
My server installed miniconda3,
After installed zsh and zim, on default theme steeef, zsh works fine,
it also show the default conda env name base.
But when I change theme to pure in .zimrc, zsh prompt became below:
the name "base" showed two times.

```
~ hero@srv-db
(base) base ❯ 
```

**Comment by ericbn** [comment]
Pure is an external theme. You might want to upgrade it to the latest version:
```
cd ${ZIM_HOME}/modules/prompt/external-themes/pure
git fetch --all --prune
git checkout master
git merge
```
If issue persist, report it upstream: https://github.com/sindresorhus/pure

**Comment by yetangye** [comment]
I operated as your instructions, but still this problem still exist.

OK, I will try to contact pure to resolve this problem.

**Comment by yetangye** [comment]
Resolved as https://github.com/sindresorhus/pure/issues/515

**Comment by lnicola** [comment]
@yetangye can you close this, then?
