### ISSUE TITLE
Can I use other zsh plugins?

### ISSUE THREAD

**Issue by BrianGilbert** [zimfw/zimfw#350]
for example:

- https://github.com/supercrabtree/k

**Comment by BrianGilbert** [comment]
All good, I figured out how to do this based on the packaged autosuggestions module

**Comment by BrianGilbert** [comment]
In case anyone else wants to know how


To create plugins from existing zsh plugins:

Create folder a `~/.zim/modules` with plugin name, create `external` subfolder inside it. Copy contents of plugin to external folder, then create an `init.zsh` file in the parent something like this.

```
#
# Directory listings for zsh with git features.
#
# Make directory listings more readable, adding a bit of color and some git 
# status information on files and directories.
#

# source script
source ${0:h}/external/k.plugin.zsh || return 1
```

**Comment by ericbn** [comment]
@BrianGilbert, this is much easier now with Zim 1.0.0.
