### ISSUE TITLE
zsh compinit: insecure directories and files

### ISSUE THREAD

**Issue by kronikpillow** [zimfw/zimfw#352]
I have installed the develop branch of zimfw, but now when i su, it gives me the following output:
zsh compinit: insecure directories and files, run compaudit for list.
Ignore insecure directories and files and continue [y] or abort compinit [n]?

--------

I have googled about it to try to find the solution, but everything that I found didn't work for me

I will also note that suggested commands like zmanage info and everything else that the preset template here for opening issues asks for is non existent in the develop branch vesion ....

**Comment by ericbn** [comment]
@kronikpillow, thanks for reporting this!

I'll make sure I update the GitHub templates on Jan 7, when develop will be merged to master.

@rafifos, you reported the same compinit issue [before](https://github.com/zimfw/zimfw/pull/323#issuecomment-565831864). Did you find a fix for it?

What strikes me is that the master and develop branch have the same `compinit -C` call:

* master:
   ```
   autoload -Uz compinit && compinit -C -d "${ZDOTDIR:-${HOME}}/${zcompdump_file:-.zcompdump}"
   ```
* develop:
  ```
  local zdumpfile
  zstyle -s ':zim:completion' dumpfile 'zdumpfile' || zdumpfile="${ZDOTDIR:-${HOME}}/.zcompdump"
  autoload -Uz compinit && compinit -C -d ${zdumpfile}
   ```

And as I mentioned [before](https://github.com/zimfw/zimfw/pull/323#issuecomment-565857592), `compinit -C` skips these security checks.

@kronikpillow, what's different about your superuser Zsh configuration? And what's the output you get when you call `compaudit` with the superuser?

**Comment by kronikpillow** [comment]
looks like the problem was a second compinit call in my .zshrc

`autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Include hidden files in autocomplete:
_comp_options+=(globdots)

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char
`

when I changed it to 
`
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit`

it stopped doing that ... which is strange, this is on the master branch, on the development branch it doesn't allow me to do so ... 

ok wait, let me reverify this :)

**Comment by kronikpillow** [comment]
ok, it was a problem in my .zshrc with a second compinit call ... I basically copied my old .zshrc in to zimfw's .zshrc and forgot to remove the 2nd compnit call :)

1 question, why is the ssh module removed from the development branch?

**Comment by ericbn** [comment]
@kronikpillow, [develop branch](https://github.com/zimfw/install/blob/059e86f/src/templates/zimrc) has the same default modules as the [master branch](https://github.com/zimfw/zimfw/blob/de8027f/templates/zimrc#L12-L13), with these changes:

* environment module contains code that was previously in directory and history
* new termtitle module with code that was previously in environment
* each prompt has it own separate module, and the prompt module was removed
* zsh-users/zsh-autosuggestions is enabled by default

**Comment by ericbn** [comment]
And the develop branch gets the Zim modules from https://github.com/zimfw

`ssh` is there.

**Comment by kronikpillow** [comment]
hm ....

kronikpillow at susanoo in ~/.config/zsh/.zim/modules
$ ls -la
total 56K
drwxr-xr-x 14 kronikpillow wheel 4,0K jan  5 19:54 .
drwxr-xr-x  4 kronikpillow wheel 4,0K jan  5 19:54 ..
drwxr-xr-x  3 kronikpillow wheel 4,0K jan  5 18:31 completion
drwxr-xr-x  3 kronikpillow wheel 4,0K jan  5 18:31 environment
drwxr-xr-x  4 kronikpillow wheel 4,0K jan  5 18:31 git
drwxr-xr-x  4 kronikpillow wheel 4,0K jan  5 18:31 git-info
drwxr-xr-x  3 kronikpillow wheel 4,0K jan  5 18:31 input
drwxr-xr-x  3 kronikpillow wheel 4,0K jan  5 18:31 steeef
drwxr-xr-x  3 kronikpillow wheel 4,0K jan  5 18:31 termtitle
drwxr-xr-x  4 kronikpillow wheel 4,0K jan  5 18:31 utility
drwxr-xr-x  7 kronikpillow wheel 4,0K jan  5 18:31 zsh-autosuggestions
drwxr-xr-x  5 kronikpillow wheel 4,0K jan  5 18:31 zsh-completions
drwxr-xr-x  3 kronikpillow wheel 4,0K jan  5 18:31 zsh-history-substring-search
drwxr-xr-x  7 kronikpillow wheel 4,0K jan  5 18:31 zsh-syntax-highlighting

**Comment by ericbn** [comment]
Please read the whole https://github.com/zimfw/zimfw/blob/a9ebc4b59fd9003cb61165b6c67e7278610ea398/README.md#usage on how to enable and install new modules. Let me know the documentation is not clear enough.

**Comment by rafifos** [comment]
@ericbn It was probably some weird WSL stuff, it fixed itself after resetting the distro.

**Comment by ericbn** [comment]
@kronikpillow, can we close this?

**Comment by kronikpillow** [comment]
yes ty  ^^

**Comment by kronikpillow** [comment]
ahh, i'v ran in to this problem again and I reread the thread, and realized i didn't answer a question that was asked here which is what is different about my superuser configuration ... the difference is in my /etc/passwd file
my superuser is setup like the following

root:x:0:0::/home/kronikpillow:/bin/zsh

**Comment by ericbn** [comment]
Oh got it @kronikpillow. So not anything we can fix or improve on Zim's side. Looks like yours is an edge case.

**Comment by kronikpillow** [comment]
Naah all good man, love zimfw, it works very nicely, the problem was that compinit was being called twice, realized it after investigating how zimfw initializes, i had a 2nd compinit in my zshrc and after I removed it from my .zshrc problem is gone

**Comment by kronikpillow** [comment]
Wish you had more modules thou, its a very fast and flexible framework, much better then thw rest, and even thou we can install modules from other frameworks, the coding there vs coding here is mmm.. Well theres a reason its tge fastest, but is it really faster then zinit's turbo mode?
