### ISSUE TITLE
git-info broken after update

### ISSUE THREAD

**Issue by spankme** [zimfw/zimfw#359]
```
Zim version:  1.0.0 (previous commit is edee218)
ZIM_HOME:     /Users/me/.zim
Zsh version:  5.7.1
System info:  Darwin me-mac.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov 9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
```

- gist of .zimrc: https://gist.github.com/spankme/1584ce7c26d4e7dda6265e589201687a
- gist of .zshrc: https://gist.github.com/spankme/13f3302d3b8d1e05bbb6927c95531502

Description
-----------
After upgrading ZIM to latest version, the git-info module functionality is broken and doesn't display any information about current Git repository in any module.

Steps to reproduce
------------------
Upgrade to latest ZIM/zimfw version, install the modules, use latest documented configuration, `cd` into a Git repository, observe no information displayed in the shell prompt.

**Comment by ericbn** [comment]
I cannot reproduce this issue. Maybe there's something else specific to your setup?

<img width="561" alt="Screen Shot 2020-01-08 at 11 00 25" src="https://user-images.githubusercontent.com/4120606/71994159-43fbf600-3206-11ea-9cc3-bb5d6657fa41.png">

**Comment by spankme** [comment]
@ericbn I can confirm that doing a clean install of zimfw actually makes things work again, so either you're right about my setup, either the upgrade path doesn't work as it should. However, I'm happy that it works, so I'll close this issue.

**Comment by ericbn** [comment]
@spankme, for the upgrade path, you probably want to do:
```
% cd ${ZIM_HOME}
% zimfw clean-compiled 
% rmdir archive autosuggestions completion custom debug directory environment fasd git-info git history-substring-search history input pacman prompt ssh syntax-highlighting utility
% zimfw install
```
as the upgrade from the previous version will leave empty directories behind if they still contain the .zwc files in there.
