### ISSUE TITLE
git alias partially conflicts with coreutils on macOS

### ISSUE THREAD

**Issue by cattyhouse** [zimfw/zimfw#361]
- GNU coreutils is installed by brew on macOS, with prefix g and linked to /usr/local/bin, to generate a list of commands:

`find /usr/local/bin/g* | cut -d '/' -f5 | sort | uniq > coreutils.link`
- zimfw git module is a bunch of git command aliases, to generate a list of alias:

`alias | grep git | cut -d= -f1 | sort | uniq > git.alias`

- then get the common lines:

`comm -12 coreutils.link git.alias`:

- conflicts are:

````
gcp
gdu
gid
gls
gmv
gwc
````

**Comment by ericbn** [comment]
This was reported in https://github.com/zimfw/git/issues/2. Let me close this ticket so the discussion can continue on the other one.
