### ISSUE TITLE
zimfw uninstall does not do unalias

### ISSUE THREAD

**Issue by cattyhouse** [zimfw/zimfw#362]
1. `vim ~/.zimrc` to comment out `zmodule git`
2. `zimfw uninstall`
3. `source ~/.zshrc`
4. `command -v gmv` :  `alias gmv='git merge --verify-signatures'`

has to quit the current terminal and start a new terminal to take effect, it would be nice to do unalias after uninstallation, if that's not trivial, then ignore this issue :)

**Comment by ericbn** [comment]
I don't see how to do this in a trivial way. Suggestions are welcome.

I focused the development of the new version of Zim on the assumption that adding, changing or removing a module is not a everyday thing, but opening a shell session is. So startup time for a new shell session is as fast as possible, but it does not try to be more awesome than averagely expected for these module maintenance tasks.

**Comment by cattyhouse** [comment]
agreed thanks, it is not trivial indeed. close for good :)
