### ISSUE TITLE
feature: Pre-/post module init scripts

### ISSUE THREAD

**Issue by lnicola** [zimfw/zimfw#364]
There's a bunch of stuff in `.zshrc` that I don't really care about:

```sh
# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Bind up and down keys
zmodload -F zsh/terminfo +p:terminfo
if [[ -n ${terminfo[kcuu1]} && -n ${terminfo[kcud1]} ]]; then
  bindkey ${terminfo[kcuu1]} history-substring-search-up
  bindkey ${terminfo[kcud1]} history-substring-search-down
fi
  
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
```

I imagine it's there so that the user can remove it in case they don't want to use `zsh-history-substring-search`. Maybe `zim` could include a bunch of these "patches" that are automatically sourced if the corresponding module is enabled.

**Comment by ericbn** [comment]
I love the idea. Straightforward to implement if done as parameters in `zmodule` whose given arguments are executed before or after all modules are initialized. First name that comes to my mind to these parameters are `--beforeall` and `--afterall` respectively.

**Comment by lnicola** [comment]
I'm not sure that pasting that chunk above as a `zmodule` argument is really better (it would have to be a heredoc or an unreadable mess, right?).

My idea was to ship some customizations in `zim`, where if you have `zmodule foo/bar`, a `.zim/patches/foo/bar.after` would be sourced (compiled) if present.

**Comment by lnicola** [comment]
It's a bit of a hack, though. Maybe we should rather upstream that thing if possible?

**Comment by ericbn** [comment]
Considering all users of zsh-history-substring-search have to run that code to make it work, it would make sense to make that code part of the plugin itself. It would be great if it could be upstreamed!

**Comment by lnicola** [comment]
I'm not sure they'd be too keen on the idea: https://github.com/zsh-users/zsh-history-substring-search/issues/92#issuecomment-491643574.

**Comment by ericbn** [comment]
Yeah, very hard to set it up. On the other hand if you look at dotfiles and Zsh frameworks around, the configuration code does not vary much from the one we included. Plus, there are currently no complains about that configuration not working. 

I would propose that the challenge to come up with a code that works in every environment should be part of the upstream project.

**Comment by lnicola** [comment]
I filed https://github.com/zsh-users/zsh-history-substring-search/issues/107.

**Comment by ericbn** [comment]
Created https://github.com/zsh-users/zsh-history-substring-search/pull/123
