### ISSUE TITLE
.zshenv doesn't get sourced on a tty

### ISSUE THREAD

**Issue by kronikpillow** [zimfw/zimfw#365]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zimfw info` and paste the output below:

```
kronikpillow at susanoo in ~
$ zimfw info
Zim version:  1.0.1 (previous commit is 28e4345)
ZIM_HOME:     /home/kronikpillow/.config/zsh/.zim
Zsh version:  5.7.1
System info:  Linux susanoo 5.4.10-1-ck-ivybridge #1 SMP PREEMPT Thu, 09 Jan 2020 21:32:48 +0000 x86_64 GNU/Linux

```

- gist of .zimrc: the default one, no modifications
- gist of .zshrc: the default one, no modifications

Description
-----------
I installed the latest zimfw by running 
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh

when i switch to tty prompt (ctrl+alt+F2) I get the following error

```
[1] 1759
/home/kronikpillow/.config/zsh/.zshrc:source:90: no such file or directory: /init.zsh
/home/kronikpillow/.config/zsh/.zlogin:source:6: no such file or directory: /login_init.zsh
```

Steps to reproduce
------------------
install latest zimfw and switch to tty, login to your standard user

Images or other information
---------------------------
when I manually source .zshenv from ~/.config/zsh/.zshenv
and then manually source .zlogin and .zshrc it starts to work ... so I come to the following
for some reason, when I go to a tty, it doesn't source .zshenv even thou on my PC it sources it with no problems ...

**Comment by Konfekt** [comment]
By the error messages, it seems that `$ZDOTDIR` was not set in `.zshenv` as indicated at https://github.com/zimfw/install/blob/d4d894bbe8d67633dcdd2b1924759a272d78cb9e/src/templates/zshenv#L7

When you say that yout `.zshenv` lies at `~/.config/zsh/.zshenv`, how is ZSH supposed to find it? It must be `~/.zshenv`. Then all other files may lie inside `~/.config` by setting `$ZDOTDIR` in `.zshenv`.

**Comment by kronikpillow** [comment]
$ZDOTDIR was defined in my .zprofile

**Comment by Konfekt** [comment]
[This thread](https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout) explains the load order of the various configuration files.

**Comment by PatTheMav** [comment]
I guess this can be closed? Everything mentioned in https://github.com/zimfw/zimfw/issues/365#issuecomment-619112635 is correct and explains why `$ZDOTDIR` needs to be set in a `.zshenv` file auto-loaded by zsh.
