### ISSUE TITLE
Website, zimfw.sh

### ISSUE THREAD

**Issue by Eriner** [zimfw/zimfw#367]
Just purchased `zimfw.sh`. Would be nice to have a small static site (https://gohugo.io/) that encapsulates the important information like installation, and with tabs that showcase features. I'll cover hosting and associated costs. Ideally, we create a new repo that contains the hugo site and uses Github actions to build and publish an nginx+alpine Docker container. That would make things simple from my end.

Could 301 zimfw.sh/install to the installation file, making the installation instructions a tad cleaner.

**Comment by Eriner** [comment]
It's also fine if this just redirects to the github.io site, though there's nothing there right now beyond the images AFAIK

**Comment by ericbn** [comment]
Having a website will be great!

Yeah, currently the github.io one only has the images used by the markdown files and wikis. To have the best of both worlds I suggest we keep the site in GitHub Pages, but configure it to use the zimfw.sh domain. https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by Eriner** [comment]
Also, not necessary, but it would be nice if zim performed an asynchronous lookup of a TXT record on that domain to determine the latest version and prompt the user to update if there is a new release. Nothing about the update process or mechanism would need to change, and we wouldn't be pinging out to a webserver so there is little security concern. Could even start https://github.com/zimfw/zimfw/issues/351 by automating the record update when a new release is cut. Ideally, this check would occur in `zlogin` to reduce spam, though I think in OS X at least this would still occur on every terminal invocation. An alternative would be to call the check on every invocation of `$ zimfw`

**Comment by lnicola** [comment]
Bit off-topic, but I've seen a nice trick for image hosting: file a GitHub issue, close it, then paste the images in the comments there and link to them.

The `TXT` record thing is also nifty, I've never thought of it.

**Comment by Brottweiler** [comment]
> Bit off-topic, but I've seen a nice trick for image hosting: file a GitHub issue, close it, then paste the images in the comments there and link to them.
> 
> The `TXT` record thing is also nifty, I've never thought of it.

Or you just host the image in the github pages repo?

**Comment by lnicola** [comment]
> Or you just host the image in the github pages repo?

The advantage is that you don't need another repo or branch, and in the latter case, people won't have to download your screenshot history when cloning the repo (of course, you can clone a single branch, but how often do you do that). It's also easier to manage (take screenshot, paste in a comment, edit your docs).

**Comment by ericbn** [comment]
> it would be nice if zim performed an asynchronous lookup of a TXT record on that domain to determine the latest version and prompt the user to update if there is a new release

On this topic, I've made a change that is ready to be released that checks the latest version directly in the GitHub repo using `git ls-remote`, having the advantage of not requiring any extra tool besides `git`, which we already require, and having the repo as the single source of truth. Code is [here](https://github.com/zimfw/zimfw/blob/1341afe5254530daacf1332dc0faf6c53c280089/src/stage2/40_zimfw_version_check.zsh.erb). It's asynchronous and runs only periodically (every 30 days), and because of that I had to use an additional `${ZIM_HOME}/.latest_version` file that stores the latest version.

**Comment by Eriner** [comment]
> having the advantage of not requiring any extra tool besides `git`

`host` (`$ host -t TXT example.com`) should be available on just about every system, FWIW. Not saying anything needs to change, only that it would be a more lightweight system, albeit it would rely on having a CI system in place to automatically update the record.

**Comment by ericbn** [comment]
Cool, I didn't know about `host`.

**Comment by sQVe** [comment]
I'd love to help out with `zimfw` but I'm not well versed in `zsh`. I do work with making web applications though so please just ping me if I'm able to help out in some way. :+1:

**Comment by ericbn** [comment]
Hi @sQVe. I would say helping us with the website will be great help!

The idea is to have a static website hosted via GitHub pages, and with the new zimfw.sh domain. The repo is https://github.com/zimfw/zimfw.github.io and it currently only contains the images we use in README.md files and wikis. The [zimfw README.md](https://github.com/zimfw/zimfw/blob/master/README.md) can be a good starting point, but I feel it also needs some polishing.

What do you say?

**Comment by sQVe** [comment]
@ericbn That sounds awesome. I'll have to read up and play around a bit with https://gohugo.io/ first.

I would guess that a basic first site would be possible with:
  - Setup Hugo with a basic theme.
  - Add information from the README. Preferably more detailed with information about the modular nature of `zimfw`. How to install our plugins but also external ones etc.
  - Pick a fitting colorscheme and customize theme.
  - Tweak and polish assets. Mainly looking at the logo here. It's confusing that it's named "Zim" there and not "zimfw".
  - Wire CI to build and publish etc.

**Comment by ericbn** [comment]
@Eriner, any special reason to use https://gohugo.io/? Is https://jekyllrb.com/ also an option? @sQVe if you already have experience with another static site generator please let us know.

**Comment by ericbn** [comment]
Regarding **Zim** vs. **zimfw**, this is something that also needs to be decided. I still kept the name Zim as much as I can around, since I still consider that to be the project name. (And I see most of the external references still calling it Zim too.)

@Eriner, are we rebranding it to zimfw? Thoughts?

**Comment by sQVe** [comment]
I want to be transparent and clear that I do not have a huge amount of time for this currently. I have another project that I need to get done before even thinking about diving into zimfw.sh. 

So, please do not wait for my sake. I'll help out as soon as I can! :pray:

**Comment by Eriner** [comment]
I'm fine with things staying the way they are. The original reason for the `zimfw` was to prevent the CLI configuration utility from clobbering the zim wiki binary name. I don't have a problem with the names clashing a bit (as both projects are distinctly different, I don't think it's at all confusing), but I think we should maintain external references as `zimfw`, and internal references as `zim`. That said, I'd be okay with moving to `zimfw` everywhere if that's what others want. I have no strong feelings about it.

**Comment by maxdevjs** [comment]
> `host` (`$ host -t TXT example.com`) should be available on just about every system

@Eriner I checked on [Void](https://voidlinux.org/) and there is no `host` (not even as optional install).

**Comment by Eriner** [comment]
@maxdevjs `host` IS available on every platform. https://man.voidlinux.org/host.1

**Comment by bgrrtt** [comment]
I like the consistency of `zimfw` everywhere. I still say "zim" out loud though. Just my 2 cents.

**Comment by maxdevjs** [comment]
@Eriner correct, `host` is available also for `Void` (included in `bind-utils` package), BUT not installed by default. I am currently trying to find out if this affects specific cases or all the images.

**Comment by michaelhthomas** [comment]
I love the idea of having a website for zim and came across this issue. I went ahead and created a basic landing page with links to the wiki for documentation, though integrating these into the website might be a better approach long-term. Here it is if you'd like to check it out: https://michaelhthomas.github.io/zimfw.sh/. I'd love to do a basic jekyll or hugo implementation for the docs as well.

**Comment by ericbn** [comment]
Hi @michaelhthomas. That's an awesome contribution! Can you [transfer you repo](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository) to the zimfw organization? I've sent you an invite to the organization as well.

I think this is a great website for Zim. @Eriner, would you be willing to have the zimfw.sh domain pointing to it?

**Comment by michaelhthomas** [comment]
Done! Thanks for the invite. It looks like it should be pretty trivial to get the domain pointed property, just need to add a CNAME to the repo. Also, the install links currently point to https://zimfw.sh/install.zsh, so if those could 301 to the proper location that'd be great.

**Comment by Eriner** [comment]
Sure, I'll set this up.

**Comment by Eriner** [comment]
Done, site available at https://zimfw.sh and https://www.zimfw.sh

Thanks for your contribution @michaelhthomas, the site looks great! Much better than I could have hacked together 👍 

Cheers!

**Comment by michaelhthomas** [comment]
Awesome, thanks @Eriner!

**Comment by ericbn** [comment]
Thanks @Eriner! What do you think about we also having https://zimfw.sh/install.zsh redirect to https://raw.githubusercontent.com/zimfw/install/master/install.zsh ? This is something you even mentioned in your opening comment, and it's being already assumed in the web page.
