### ISSUE TITLE
Guide to migrate from oh-my-zsh or zplug to zimfw

### ISSUE THREAD

**Issue by danielporto** [zimfw/zimfw#374]
Is there a guide to help migrating from oh-my-zsh or zplug to zimfw?

In particular I have a few plugins I cannot find in zimfw defaults that I wish to use,
for instance, I can't live without https://github.com/mfaerevaag/wd. use it a thousand times per day. 
I read [here](https://github.com/zimfw/zimfw/issues/350) that is possible to use other plugins but I could not find a guide and the last comment on the text says there is a new and easier way to do it.

Thanks for the super great work!

edit: fixed the link

**Comment by ericbn** [comment]
Olá @danielporto.

As @sorin-ionescu [previously](https://github.com/sorin-ionescu/prezto/issues/617#issuecomment-44769004) [stated](https://github.com/sorin-ionescu/prezto/issues/860#issuecomment-97928452) -- and I agree with him -- it's the "Wild West" out there.

In this case, the https://github.com/mfaerevaag/wd repo is missing the https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/wd/wd.plugin.zsh file in the root directory, so it would work with most Zsh plugin managers. The file must be named `wd.plugin.zsh`. Oh-My-Zsh has that file on the root of the plugin subdirectory, and that's it works there out of the box.

**Comment by danielporto** [comment]
Thanks for the quick reply @ericbn and also for the warm greeting in "pt".

Sorry but I stupid about framework configurations and stuff. Must of you said sounded like Klingon to me. 
If I got it right, there is no point in supporting all existing plugins out there. I totally understand. 
It would be great for sure, but compromises has to be made.
Let's suppose that a plugin exists and is officially supported by ohmyzsh. My question is if is there a recipe for a total noob (with regard to shell frameworks) despite of being a fan, that I can pick up and make it work? For instance, I have no idea where to place the wd.plugin.zsh file.
Do you recommend forking zimfw and including it? (and perhaps if it works suggest as a PR?)

**Comment by lnicola** [comment]
Is it enough to set up `wd` using `zmodule`, then manually place that `wd.plugin.zsh` after `zimfw install`?

**Comment by danielporto** [comment]
Just notice [this](https://github.com/zimfw/custom) 
A little facepalm moment...

**Comment by ericbn** [comment]
A PR to the https://github.com/mfaerevaag/wd repo adding the https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/wd/wd.plugin.zsh should be enough. Then add `zmodule mfaerevaag/wd` to your .zimrc and run `zimfw install` (or `zimfw update` if you already installed the module) after the PR is merged to master.

Everything else is a workaround, and will just contribute to the Wild West out there.

**Comment by danielporto** [comment]
> A PR to the https://github.com/mfaerevaag/wd repo adding the https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/wd/wd.plugin.zsh file should be enough. Then add `zmodule mfaerevaag/wd` to your .zimrc and run `zimfw install` (or `zimfw update` if you already installed the module) after the PR is merged to master.
> 
> Everything else is a workaround, and will just contribute to the Wild West out there.

It didn't work very well.
1. added zmodule mfaerevaag/wd
2. zimfw install
3. added wd.plugin.zsh to .zim/modules/wd
4. run zimfw update

exit, back
lots of errors "no such directory name" for all paths with spaces in the name. All my "Google Drive" dirs.
:-/

**Comment by ericbn** [comment]
@danielporto please try with `zmodule mfaerevaag/wd -s 'wd.plugin.zsh` in your .zimrc and restart your shell.

As there's a `wd.sh` file too, by default Zim tries to source that file instead. I told you it's the Wild West out there!  :- )

**Comment by danielporto** [comment]
Good, it worked almost perfectly.

> As there's a wd.sh file too, by default Zim tries to source that file instead. I told you it's the Wild West out there! :- )
Oh man.. that's crazy.

I can warp into dirs and it autocompletes but every command outputs lots of erros like:
wd_export_static_named_directories:hash:4: no such directory name: Drive/Juniper
where "Drive/Juniper" actually is part of the path ~/Google Drive/Juniper that was split in the space char for some reason.
:-)

**Comment by danielporto** [comment]
it seems that the version at https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/wd is more recent than the one in mfaerevaag/wd. 
chances are that are bug fixes.

**Comment by danielporto** [comment]
Yes, that was it. wd is working now. 
Thus, all files in https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/wd/ works once imported into zimrc.
Question is, can we make this process easy enough to deploy via dotbot/dotfiles?

**Comment by ericbn** [comment]
The idea is that having '${ZIM_HOME}/zimfw.zsh`, a `${ZDOTDIR:-${HOME}}/.zimrc` file with your modules definition, and running `source ${ZIM_HOME}/zimfw.zsh install` should be enough to give you a fresh install on a new machine.

If you have broken modules because there are issues upstream, then I suggest submitting a PR there.

Alternatively, you can load plugin from Oh-My-Zsh with Zim using:
```
zmodule ohmyzsh/ohmyzsh -f 'plugins/wd' -s 'plugins/wd/wd.plugin.zsh' -f 'plugins/another_one' -s 'plugins/another_one/another_one.plugin.zsh'

```
although Zim was not build to support loading plugins directly from Oh-My-Zsh (becasue we don't want to encourage taht), it's flexible enough to allow that.

**Comment by danielporto** [comment]
I fixed it.
zmodule danielporto/wd -s 'wd.plugin.zsh' -f '.'
works with zimfw out of the box.

**Comment by danielporto** [comment]
> The idea is that having `${ZIM_HOME}/zimfw.zsh`, a `${ZDOTDIR:-${HOME}}/.zimrc` file with your modules definition, and running `source ${ZIM_HOME}/zimfw.zsh install` should be enough to give you a fresh install on a new machine.
> 
> If you have broken modules because there are issues upstream, then I suggest submitting a PR there.
> 
> Alternatively, you can load plugin from Oh-My-Zsh with Zim using:
> 
> ```
> zmodule ohmyzsh/ohmyzsh -f 'plugins/wd' -s 'plugins/wd/wd.plugin.zsh' -f 'plugins/another_one' -s 'plugins/another_one/another_one.plugin.zsh'
> ```
> 
> although Zim was not build to support loading plugins directly from Oh-My-Zsh (becasue we don't want to encourage taht), it's flexible enough to allow that.

let's hope that for most of plugins I use it works :-)
Thanks a lot!!
