### ISSUE TITLE
Pure theme - new installation instructions

### ISSUE THREAD

**Issue by maxdevjs** [zimfw/zimfw#375]
Edit: I was missing something :) 
After pulling the new version, I had a merge conflict (Unmerged paths: (...) `deleted by them: tools/zim_update`) and zimfw was not accessible. 

------------------
[Pure](https://github.com/sindresorhus/pure) README has been updated with the following instructions:

`Add zmodule sindresorhus/pure --source async.zsh --source pure.zsh to your .zimrc and run zimfw install`

I probably miss something, because I have no idea how that `zimfw install` should work.

Nonetheless, [Zim](https://github.com/zimfw/zimfw) README instructions `source ~/.zim/zimfw.zsh install` work like a charm.

Should [Pure](https://github.com/sindresorhus/pure) README show the same instructions?

**Comment by ericbn** [comment]
Pulling the latest version with git is not the recommended way to upgrade from the previous version, as ZIM_HOME does not need to be a git repo anymore, and you just need the zimfw.zsh script there. Check the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md). Also [beware of empty module subdirectories](https://github.com/zimfw/zimfw/issues/359#issuecomment-572190743) when try to upgrade pulling with git.

Do a [fresh install](https://github.com/zimfw/zimfw/blob/master/README.md#installation) instead.

PRs with suggestions on how to make the upgrade process clearer and easier for users coming from the previous master version are welcome.

**Comment by maxdevjs** [comment]
Of course I read the Changelog. Rigorously **after** upgrading :D
I do not use `Zim` on my main box, then I am not sure about anything so far. In fact, I started checking instruction in [Pure](https://github.com/sindresorhus/pure) README.

Only suggestions I have right now is, perhaps, to make explicit wherever relevant (theme repos, installation notes,...) what should be the recommended way to upgrade from previous version. 

Probably, it is cleaner (easier) solution than trying to cope with every possible drawback. Personal example: I have a highly customized (call it messy) `$ZDOTDIR` configuration. After upgrading, I still have `history` and `tty` support broken. 

Anyway, as I enjoy `Zim` and the new architecture sounds amazing, I am going to check what is happening in my test box. Finding something relevant, I will comment here.

**Comment by ericbn** [comment]
@maxdevjs, can we close this?

**Comment by maxdevjs** [comment]
@ericbn sure :)
