### ISSUE TITLE
It's impossible to use eriner theme

### ISSUE THREAD

**Issue by rylandg** [zimfw/zimfw#379]
I installed on ubuntu:19.04 after having not updated and am just so confused. It feels like zim themes have honestly been broken quite badly with the changes. I would really appreciate some help:

* Where are themes installed now? I've gone crazy `grep`ing, searching github and I don't understand where they are installed. I understand they are separate repos, but they aren't in my `~/.zim/modules` and they aren't in the `prompt` module source code.
* Why is eriner theme (the one used for every screenshot and example) no longer included in the default install. Doesn't this seem very odd?
* How is it possible to use eriner even if you do manually install? It will never show up in `prompt -l` (even after adding to `~/.zimrc` and calling `zimfw install`) and there seems to be 0 way of calling it directly.

What I've tried
```
#prompt eriner white white white
zprompt_theme='eriner black blue'
ZSH_THEME='eriner'
```

Also tried sourcing the file directly which also did not work.

**Comment by ericbn** [comment]
Hi @rylandg, did you try reading the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md)?

**Comment by rylandg** [comment]
Thanks for the quick reply. I did read the changes but I now re-read and understand that standalone themes are sourced directly. I still don't fully understand where or how I'm supposed to configure the theme (i used to use `zprompt_theme='eriner white white white white`), but that's more off a best practices question. I'm also still unsure of where the "built-in" themes are located. Also, why is the prompt module maintained if external themes don't integrate with it?

I'm not trying to come off as critical, I use zim because I love it.

**Comment by rjcoelho** [comment]
@rylandg you zmodule your theme like anyother plugin, eg: add 'zmodule zimfw/eriner' to zimrc
See https://github.com/zimfw for old themes

**Comment by ericbn** [comment]
The zimfw organization is the default one, if none is given with the module name. So you can add `zmodule eriner` to your .zimrc and run `zimfw install` to install the theme. The list of themes is in the [Themes](https://github.com/zimfw/zimfw/wiki/Themes) wiki.

Also, as promptinit is not supported anymore, the themes are configured with environment variables. This is mentioned in the Changelog. See the [eriner theme README.md](https://github.com/zimfw/eriner/blob/master/README.md#settings).

**Comment by ericbn** [comment]
@rylandg, were you able to setup the theme to your needs? Suggestions on how to improve our documentation are more than welcome.

**Comment by sebastianst** [comment]
I just upgraded my pre-v1.0 zim to the latest version v1.3.2 (complete reinstallation) and then added `zmodule eriner` to my `.zimrc` and ran `zimfw install`. It also successfully installs eriner, but in a new shell, eriner is still not used as a theme. Is there anything else that has to be set to enable a particular theme?

**Comment by ericbn** [comment]
@sebastianst, maybe you're overriding the prompt with another module or by sourcing something else in your [startup files](http://zsh.sourceforge.net/Intro/intro_3.html)?

When I do a clean install of Zim, I get the steeef prompt as expected, and replacing `zmodule steeef` by `zmodule eriner` in the ~/.zimrc file, then running `zimfw install`, and then restarting the shell works as expected too, and I get the eriner prompt.

**Comment by Vash63** [comment]
I'm also duplicating this. I had a couple year old version installed and just wiped all of my configs (including the files you listed above) for both zim and zsh and started fresh. After adding `zmodule eriner` to the bottom of my ~/.zimrc file and running `zimfw install` it installs it, but then the theme is not active for new shells.

**Comment by ericbn** [comment]
Hi @Vash63. Thanks for tracking down your issue.

Not sure if there's an OS out there not following the standard or sourcing the startup files in /etc files first, and then the startup files in ZDOTDIR or HOME. It's very unlikely. Care to share your `zimfw info` and your startup files (.zshenv .zprofile .zshrc .zlogin .zlogout)?

Also, the only change we did regarding the order of how Zim starts up from the previous to the new version is setting ZIM_HOME in .zshenv (in the new version) instead of in .zshrc (in the previous version).

**Comment by Vash63** [comment]
zimfw info is:
```

zimfw info   
zimfw version: 1.4.3 (built at 2021-03-19 23:42:38 UTC, previous commit is 163d36b)
ZIM_HOME:      /home/vash/.zim
Zsh version:   5.8
System info:   Linux vashnix 5.11.10-142-tkg-cfs #1 TKG SMP PREEMPT Fri, 26 Mar 2021 10:18:24 +0000 x86_64 GNU/Linux
```

[zsh startup files.tar.xz.zip](https://github.com/zimfw/zimfw/files/6217412/zsh.startup.files.tar.xz.zip)
^Above is actually a .tar.xz, for some reason github wouldn't let me upload that (or the dotfiles directly) so I appended .zip. I don't have a `.zprofile` or `.zlogout` in my home dir. I removed the offending zsh config in /etc already.

**Comment by sebastianst** [comment]
> @sebastianst, maybe you're overriding the prompt with another module or by sourcing something else in your [startup files](http://zsh.sourceforge.net/Intro/intro_3.html)?
> 
> When I do a clean install of Zim, I get the steeef prompt as expected. Replacing `zmodule steeef` by `zmodule eriner` in the ~/.zimrc file, then running `zimfw install`, and then restarting the shell works as expected too, and I get the eriner prompt.

I finally solved this issue locally. I had a conflicting system-wide installation of `grml` messing with zim...

**Comment by ericbn** [comment]
@sebastianst, is the system-wide installation of grml something we can detect in our installation script? We could add a warning there, as we already do for when other zsh frameworks are detected to be installed. See https://github.com/zimfw/install/blob/master/src/steps/40_other_frameworks.zsh.erb

**Comment by sebastianst** [comment]
@ericbn that would be fantastic! I'm running Arch and had [`grml-zsh-config`](https://archlinux.org/packages/extra/any/grml-zsh-config/) installed, the package link contains the file list and content.
