### ISSUE TITLE
Install external theme

### ISSUE THREAD

**Issue by APakrohk** [zimfw/zimfw#381]
How do I install this theme.
I followed the wiki instructions, but it didn't work.
[ThemeURL](https://github.com/Saleh7/igeek-zsh-theme)
[ZimRc](https://gist.github.com/APakrohk/44a85355c36678e92e151a4eae9471f9)
[ZSHrc](https://gist.github.com/APakrohk/20281f1f0e541b4f2c4e40239ee837a9)

**Comment by ericbn** [comment]
As the [README.md](https://github.com/zimfw/zimfw/blob/master/README.md#zmodule) explains, by default the following file is sourced from each module: the file with largest size matching `{init.zsh|module_name.{zsh|plugin.zsh|zsh-theme|sh}}`, if any exists.

In the case of Saleh7/igeek-zsh-theme, the module name is igeek-zsh-theme, but it contains a file named `igeek.zsh-theme`, so you might want to change the module name with `zmodule Saleh7/igeek-zsh-theme -n igeek`.

**Comment by ericbn** [comment]
@APakrohk, can we close this?

**Comment by APakrohk** [comment]
> @APakrohk, can we close this?

Yes, thank you for helping and reminding me.
