### ISSUE TITLE
Complex aliases does not appear to be highlighted properly

### ISSUE THREAD

**Issue by intivemark** [zimfw/zimfw#382]
```
➜ ~ zimfw info
zimfw version: 1.1.1 (previous commit is 6129062)
ZIM_HOME:      /Users/mark.dziewit/.zim
Zsh version:   5.7.1
System info:   Darwin SpaceRocketLauncher 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan 9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

- gist of .zimrc:
https://github.com/marek2901/config_files/blob/master/.zimrc
- gist of .zshrc:
https://github.com/marek2901/config_files/blob/master/.zshrc

Description
-----------
Some of my aliases appear to be broken when they keep working. Autocomplete works too. This issue seems to be only with highlighting.

Steps to reproduce
------------------
Start zsh
make an alias like:
```
➜ ~ alias upmymaster="gco master && g pull origin master && gco -"
```
then type without exec
```
➜ ~ upmymaster
```

Notice the color of `upmymaster` command. It works perfectly fine but appear to be highlighted as broken for some reason.

Images or other information
---------------------------
![image](https://user-images.githubusercontent.com/32266567/78163396-a13fc600-7448-11ea-847a-264ad37b4fb0.png)

**Comment by rjcoelho** [comment]
So syntax highlighting has a bug ? maybe its then zsh-users/zsh-syntax-highlighting module

**Comment by intivemark** [comment]
Thank you soo much for pointing out. So sorry for causing unnecessary problems. Closing that issue as it appears to be related to https://github.com/zsh-users/zsh-syntax-highlighting/pull/696 (there seem to bo lotsa issues in zsh-users/zsh-syntax-highlighting module with alias highlighting).

Thanks for the help :).

**Comment by danielshahaf** [comment]
Hi, z-sy-h maintainer here.  Sorry to raise a long-inactive thread but the referenced issue, https://github.com/zsh-users/zsh-syntax-highlighting/pull/696, only affects aliases with _literal newlines_ or _literal semicolons_ in their definitions' right-hand sides.  Your example wouldn't be affected unless either `g` or `gco` is itself such an alias.  Feel free to open an issue over at z-sy-h to discuss further, if needed.  Cheers!
