### ISSUE TITLE
Garbage printed on the terminal at startup

### ISSUE THREAD

**Issue by jeevatattva** [zimfw/zimfw#384]
$ zimfw info
```
zimfw version: 1.1.1 (previous commit is 6129062)
ZIM_HOME:      /data/data/com.termux/files/home/.zim
Zsh version:   5.8
System info:   Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Tue Mar 10 20:18:08 WIB 2020 aarch64 Android
```
Gist of `.zshrc` and `.zimrc`:
https://gist.github.com/jeevatattva/e22f48973f71732e5374d15fb149804e

Description
-----------
I'm using Termux on Android. On shell startup, seems like, internal functions are being printed on to the terminal. Also, zsh completion is not working when this happens. I have tried clean install multiple times, and this happens unexpectedly. 

Steps to reproduce
------------------

Images or other information
---------------------------
![GIF-200407_142653](https://user-images.githubusercontent.com/26855245/78651109-83a5ad00-78dd-11ea-9a3f-593f5d56eff1.gif)

**Comment by ericbn** [comment]
Hi @jeevatattva. Does the issue still persist if you comment out or remove the following line that was added to the end of .zshrc? 

```
[ -r ~/.allias ] && source ~/.allias
```

**Comment by jeevatattva** [comment]
> Hi @jeevatattva. Does the issue still persist if you comment out or remove the following line that was added to the end of .zshrc?
> 
> ```
> [ -r ~/.allias ] && source ~/.allias
> ```

Thanks for your response.

Yes, those messages at startup are printed even though I comment out the `alias` file - `~/.allias`, the contents of which are - 

```
$ cat ~/.allias
alias extcard="cd /storage/8A02-18F9"
alias inshot="cd ~/storage/shared/inshot"
alias snapseed="cd ~/storage/shared/Snapseed"
alias joey="cd ~/storage/shared/Pictures/Joey"
alias friendly="cd ~/storage/shared/storage/8A02-18F9/Photos/friendly"
alias deck="cd /storage/8A02-18F9/Photos/DeckTheWalls"
alias utube=~/.local/bin/youtube-dl
alias -g GG=google.com

alias -g SUS="| curl -F 'sponge=<-' http://sponge.in"
```

**Comment by ericbn** [comment]
![Screenshot_20200407-080352_Termux](https://user-images.githubusercontent.com/4120606/78672594-7de0a500-78a6-11ea-9c79-bed5675a7c6e.jpg)

I used the same .zimrc and .zshrc from your gist and could not reproduce your issue. Maybe some other [startup file](http://zsh.sourceforge.net/Intro/intro_3.html) is causing it?

**Comment by jeevatattva** [comment]
I understand some startup file maybe be causing it to print those messages, but wonder why that would print those function definitions out on to the terminal. Is it some kind of debug mode which I have entered? Now that I have commented out the `utility` module, I see some function definitions - `mkcd`, `mkpw`, are not printed anymore.

How to turn off debug mode? Thank you.

**Comment by jeevatattva** [comment]
Out of all the startup files mentioned at the URL - `$ZDOTDIR/.zshenv`, `$ZDOTDIR/.zprofile`, `$ZDOTDIR/.zshrc`, `$ZDOTDIR/.zlogin`, `$ZDOTDIR/.zlogout`; I only have `.zshenv`, `.zprofile`, `.zshrc` and `.zlogin` from the installation instructions, and none of them are the suspects.

**Comment by jeevatattva** [comment]
This issue doesn't happen on clean install but springs up unexpectedly. As I've no method to reproduce this issue, I've moved on to other alternatives for the time being. 

Thank you for your time.

**Comment by jeevatattva** [comment]
Currently using `zplug` with a few modules added from `zimfw` - `input`, `utility`, `environment`. Everything worked well, until, I added `zimfw/completion`, it started printing out function definitions at startup again.

P.S. - This only happens on the mobile device and not on my macs.
