### ISSUE TITLE
Install error with xargs skips installing login_init in .zim directory

### ISSUE THREAD

**Issue by gabeos** [zimfw/zimfw#385]
Install output:
```
gsch@gsch~% curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
) Git is installed.
) Using Zsh version 5.7.1
) ZIM_HOME not set, using the default one.
) Zsh is your default shell.
) No other Zsh frameworks detected.
) Downloaded the Zim script to /home/gsch/.config/zsh/.zim/zimfw.zsh
) Copied Zim template to /home/gsch/.config/zsh/.zimrc
) Prepended Zim template to /home/gsch/.config/zsh/.zshrc
) Prepended Zim template to /home/gsch/.config/zsh/.zshenv
) Prepended Zim template to /home/gsch/.config/zsh/.zlogin
xargs: zsh: Required key not available
x Could not install modules.
Initializing Zim .../tmp/zsh21YDPb:source:98: no such file or directory: /home/gsch/.config/zsh/.zim/init.zsh
/tmp/zshF03l8m:source:7: no such file or directory: 
/home/gsch/.config/zsh/.zim/login_init.zsh
All done. Enjoy your Zsh IMproved! Restart your terminal for changes to take effect.
```

In a terminal, run `zimfw info` and paste the output below:

```
gsch@gsch~% zimfw info
zsh: required key not available: zimfw
```

- gist of .zimrc: default
- gist of .zshrc: default

Description
-----------

Steps to reproduce
------------------
1. Clean zsh init files
2. run installation via curl command

**Comment by ericbn** [comment]
It failed because of the "Required key not available" error. I'm not familiar with this error, but it seems to be related to [UEFI systems with enabled Secure Boot](https://askubuntu.com/q/762254). @gabeos, can you please check that?

**Comment by gabeos** [comment]
I saw that link as well, but it refers to adding kernel modules, which is restricted by UEFI/Secure Boot for security reasons. AFAIK there's no reason zimfw should be doing anything at all with the kernel, and should really only be checking out git repos and filling out templates, and if it is installing a kernel module that feels like a security issue.

The install script seems a bit hard to debug. Is there an easy way to increase the logging level or otherwise get better error messages?

**Comment by gabeos** [comment]
Tried again by downloading the install script directly and then `cat`'ing it to zsh rather than `curl`'ing it to zsh and... it worked? 

I honestly have no clue what could be different about the two methods.. maybe it was a kernel security thing that disallowed executing downloaded code, but i can't imagine how.. anyway, i'll close the bug for now. thanks for your response!

**Comment by ericbn** [comment]
@gabeos, if you find a way to improve our installl script so it at least gives users a more friendly error, it will be really helpful. PRs are more than welcome in https://github.com/zimfw/install
