### ISSUE TITLE
Where were the themes in the previous version？

### ISSUE THREAD

**Issue by daxinnan** [zimfw/zimfw#389]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zimfw info` and paste the output below:

```
zimfw version: 1.1.1 (previous commit is 6129062)
ZIM_HOME:      /home/lxc/.zim
Zsh version:   5.8
System info:   Linux lxc-PC 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- gist of .zimrc:
- gist of .zshrc:
Description
-----------
I used the **liquidprompt** theme for a long time. 
Today I reinstall the latest zimfw in the  `~/.zim` directory by running
`curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`.
    I use `prompt -l` to check the available themes list, however, I don't see the themes in the wiki like **eriner** in the result, either.
    I just want the python virtual environment name and computer name are in the same line.

Steps to reproduce
------------------

Images or other information
---------------------------
![image](https://user-images.githubusercontent.com/26436171/80303012-1bf9c800-87e0-11ea-8feb-19cf488ff4ac.png)

**Comment by ericbn** [comment]
Hi @daxinnan. Please read the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md#100---2020-01-07).

The prompt module now only contains the Zsh default prompts, which are the ones you see listed. Other prompts need to be initialized separately using zmodule. For liquidprompt, it's `zmodule nojhan/liquidprompt`, as that repository does not belong to the zimfw organization and its not maintened by us.

**Comment by daxinnan** [comment]
Thanks, I find the `restore` theme great too. :smile:
