### ISSUE TITLE
How do I adjust color?

### ISSUE THREAD

**Issue by DoTheEvo** [zimfw/zimfw#391]
I am getting really annoyed on how dark blue color is

![blue](https://i.imgur.com/00B5z0u.png)

Any way to easily change it, adjust it?

Sorry for picking brain if its not part of zim
I realize it could be part of the terminal application or some core zsh setting or something else, but maybe some direction?

**Comment by lnicola** [comment]
That's the terminal color scheme, you should be able to change it from there.

**Comment by DoTheEvo** [comment]
lol I was just writing how i use termite on one machine and the other I ssh to is running just virtual console...

well me dumb, what do I use to ssh in to that machine.... termite!

thnx
