### ISSUE TITLE
At what point are the ZIM files executed on a tty?

### ISSUE THREAD

**Issue by Viroide** [zimfw/zimfw#392]
```
zimfw version: 1.1.1 (previous commit is 6129062)
ZIM_HOME:      /Users/jon.eguiluz/.zim
Zsh version:   5.7.1
System info:   Darwin Jons-MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar 4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

```

Description
-----------
Probably not a bug, I just don't know the modules loading logic.

In order to use GPG in my shell, I need to `export GPG_TTY=$(tty)` I have try to put that line in ` .zshenv` and in `.zshrc` in both cases if I get 

```
~ > echo $GPG_TTY
not a tty
```

At what point is the code executed in a tty? so I can make the export?

Steps to reproduce
------------------
- put `export GPG_TTY=$(tty)` on ` .zshenv`
- start a new shell
- `echo $GPG_TTY` tells `not a tty`

**Comment by Viroide** [comment]
After I while I discovered that was an issue with powerlevel10K, sorry to bother you. 
If this can be useful to someone, I will leave it here.

Just replace `export GPG_TTY=$(tty)` by `export GPG_TTY=$TTY`

https://unix.stackexchange.com/a/608921

**Comment by ericbn** [comment]
Hi @Viroide. Thanks for the heads up.

If you're using something like a "instant prompt", know that Zim is generally so fast that you don't even need something like that. It's even faster than zinit with "turbo" mode (which is similar, but maybe not exactly the same as p10k's "instant prompt"). See our [latest benchmark runs](https://github.com/zimfw/zsh-framework-benchmark/actions).

![Screen Shot 2021-06-09 at 08 09 51 o](https://user-images.githubusercontent.com/4120606/121360738-4df1bf00-c8fa-11eb-9d3b-723e056b1b89.png)

This benchmark uses Zim's default installation modules. Of course the times will greatly vary depending on your configuration.

**Comment by Konfekt** [comment]
Since it seems relatively recent, I am curious wheter [zi's turbo mode](https://wiki.zshell.dev/docs/getting_started/overview#turbo-mode-zsh--53) is similar to zinit's turbo?
