### ISSUE TITLE
Upgrade to 1.2.0 has broken zimfw/utility module on macOS

### ISSUE THREAD

**Issue by jeevatattva** [zimfw/zimfw#394]
```
zimfw version: 1.2.0 (previous commit is 8724686)
ZIM_HOME:      /Users/javi/.zim
Zsh version:   5.7.1
System info:   Darwin ABAR.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar 4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

- gist of `.zimrc` and `.zshrc`: https://gist.github.com/jeevatattva/b46ec41f880c76ccc2ede3b070795929

Description
-----------
After upgrading from `1.1.1` to `1.2.0`, aliases in`utility` are broken.
e.g. output of `ls` command,
```
$ ls
ls: illegal option -- -
usage: ls [-@ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1%] [file ...]
```
and similarly, `chmod +x <file>` is failing too.
```
chmod: illegal option -- -
usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...
```

Steps to reproduce
------------------
1. Current version `1.1.1`.
2. `zimfw upgrade`
3. Open terminal, type `ls` or use `chmod`.
4. Error
 
Haven't tested this using a vanilla install yet. I'll update this issue when I get to try it.

Images or other information
---------------------------
N.A.

**Comment by ericbn** [comment]
Not sure how the changes in version 1.2.0 would cause this. What do you get when you run

    print ${+commands[dircolors]}

? In BSD or macOS, you should get 0.

**Comment by jeevatattva** [comment]
Thank you for the input. 

In my current work environment,
```
$ print ${+commands[dircolors]}
1
```
When I get a chance to check this on my other macOS machine, which still has version `1.1.1`, I'll report it here.

**Comment by ericbn** [comment]
If you installed the GNU coreutils in your MacOS, but you're still using the BSD ls, then this kind of conflict can happen. The Homebrew coreutils was once broken, as it was symlinking dircolors (but not ls), and that was quickly fixed back then.

**Comment by ericbn** [comment]
The changes in this Pull Request might fix your issue:  https://github.com/zimfw/utility/pull/1

**Comment by jeevatattva** [comment]
@ericbn You're spot on. I recently installed GNU coreutils but haven't symlink'd those utilities to `/usr/bin/local`. But have them added in `$PATH` but with lesser precedence to `/bin`.

```
 $ printenv PATH|awk -F: '{for(i=1; i<=NF; i++) print $i}'
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/Wireshark.app/Contents/MacOS
/usr/local/opt/coreutils/libexec/gnu bin
/Users/javi/Development/Go/bin
/Users/javi/Library/Python/3.8/bin
```
And `ls` and `chmod` were working in a sub shell.

I'll check out your changes and report back.
