### ISSUE TITLE
bd.plugin.zsh is not sourced in init.zsh

### ISSUE THREAD

**Issue by babba22** [zimfw/zimfw#395]
For bug reports, please provide the following information:

```
zimfw version: 1.2.0 (previous commit is 8724686)
ZIM_HOME:      /home/babba/.dotfiles/zsh/.zim
Zsh version:   5.8
System info:   Linux babba-xps 5.6.13-153.current #1 SMP PREEMPT Thu May 14 20:38:48 UTC 2020 x86_64 GNU/Linux
```

- gist of .zimrc: https://gist.github.com/babba22/ec27d940ea03c2381e75e277a4f9055f
- gist of .zshrc: https://gist.github.com/babba22/ff4c29771cad147f43dc98d5806ce744

Description
-----------
When installing [`zsh-bd`](https://github.com/Tarrasch/zsh-bd) plugin, after I add the line
```
zmodule Tarrasch/zsh-bd
```
to my .zimrc file and I run `zimfw install`, the repository is downloaded but no new entry is added in init.zsh (should be `source /home/babba/.dotfiles/zsh/.zim/modules/zsh-bd/bd.plugin.zsh`)

Steps to reproduce
------------------
Just try to install the plugin

**Comment by ericbn** [comment]
Hi @babba22. Check the [zmodule usage](https://github.com/zimfw/zimfw/blob/7e369ef9cf3fbdc334bc2baa01f093bd6ceee10a/README.md#zmodule):

<pre>
<strong>-n</strong>|<strong>--name</strong> &lt;module_name&gt;        Set a custom module name. Default: the last component in the &lt;url&gt;.

...

<strong>-s</strong>|<strong>--source</strong> &lt;file_path&gt;        Source specified file. The file path is relative to the module root
                               directory. Default: the file with largest size matching
                               <strong>{init.zsh,module_name.{zsh,plugin.zsh,zsh-theme,sh}}</strong>, if any exist.
</pre>

So in this case, by default, the name of the module is **zsh-bd**, and zimfw will look for one of these files: 
* init.zsh
* **zsh-bd**.zsh
* **zsh-bd**.plugin.zsh
* **zsh-bd**.zsh-theme
* **zsh-bd**.sh

You can either pass `--name db` or `--source bd.plugin.zsh` to achieve the desired effect.

**Comment by babba22** [comment]
Thank you very much! As usual, when I read I don't pay attention :facepalm:

**Comment by ericbn** [comment]
@babba22, what do you think about having a warning message for when nothing is being initialized for a module. I'm thinking of:


<pre>
! /Users/eric/.zimrc:42:zsh-bd: Nothing found to be initialized. Customize the module initialization with zmodule options.

Usage: zmodule <url> [-n|--name <module_name>] [options]

Add zmodule calls to your /Users/eric/.zimrc file to define the modules to be initialized.
The modules are initialized in the same order they are defined.

  <url>                          Required repository URL or path. The following formats are
                                 equivalent: name, zimfw/name, https://github.com/zimfw/name.git.
  -n|--name <module_name>        Set a custom module name. Default: the last component in the <url>.

Repository options:
  -b|--branch <branch_name>      Use specified branch when installing and updating the module.
                                 Overrides the tag option. Default: master.
  -t|--tag <tag_name>            Use specified tag when installing and updating the module.
                                 Overrides the branch option.
  -z|--frozen                    Don't install or update the module.

Initialization options:
  -f|--fpath <path>              Add specified path to fpath. The path is relative to the module
                                 root directory. Default: functions, if the subdirectory exists.
  -a|--autoload <function_name>  Autoload specified function. Default: all valid names inside the
                                 module's specified fpath paths.
  -s|--source <file_path>        Source specified file. The file path is relative to the module root
                                 directory. Default: the file with largest size matching
                                 {init.zsh,module_name.{zsh,plugin.zsh,zsh-theme,sh}}, if any exist.
  -d|--disabled                  Don't initialize or uninstall the module.
</pre>

Is the warning clear enough? Thoughts?

**Comment by babba22** [comment]
The idea of the warning is very good, what about a message like this:
```
! /Users/babba22/.zimrc:42:zsh-bd: Nothing found to be initialized.
Remember: only the file with largest size matching {init.zsh,module_name.{zsh,plugin.zsh,zsh-theme,sh}} is sourced, **if any exist**.
Please, customize the module initialization with zmodule options (either -n|--name or -s|--source):

Usage: zmodule  [-n|--name ] [options]

Add zmodule calls to your /Users/eric/.zimrc file to define the modules to be initialized.
The modules are initialized in the same order they are defined.

                            Required repository URL or path. The following formats are
                                 equivalent: name, zimfw/name, https://github.com/zimfw/name.git.
  -n|--name         Set a custom module name. Default: the last component in the .

Repository options:
  -b|--branch       Use specified branch when installing and updating the module.
                                 Overrides the tag option. Default: master.
  -t|--tag             Use specified tag when installing and updating the module.
                                 Overrides the branch option.
  -z|--frozen                    Don't install or update the module.

Initialization options:
  -f|--fpath               Add specified path to fpath. The path is relative to the module
                                 root directory. Default: functions, if the subdirectory exists.
  -a|--autoload   Autoload specified function. Default: all valid names inside the
                                 module's specified fpath paths.
  -s|--source         Source specified file. The file path is relative to the module root
                                 directory. Default: the file with largest size matching
                                 {init.zsh,module_name.{zsh,plugin.zsh,zsh-theme,sh}}, if any exist.
  -d|--disabled                  Don't initialize or uninstall the module.
```

Maybe too much?

**Comment by ericbn** [comment]
Maybe the simpler warning message will force the user to read the whole zmodule usage?  :- )

**Comment by babba22** [comment]
Yeah, the idea was to give an hint, but "forcing" the user to read the usage makes sense :D
Anyway, what is important is to let the user know that zimfw actually tried to add a file from the new plugin, but couldn't.
