### ISSUE TITLE
systemctl complete issue and fix

### ISSUE THREAD

**Issue by cattyhouse** [zimfw/zimfw#396]
command : 

`systemctl enable/disable ServiceName[press Tab here]`

result: 
````
_systemctl_unit_state: bad set of key/value pairs for associative array
_systemctl_unit_state: bad set of key/value pairs for associative array
_systemctl_unit_state: bad set of key/value pairs for associative array
````

fix:

add this code to ~/.zshrc

````
_systemctl_unit_state() {
  typeset -gA _sys_unit_state
  _sys_unit_state=( $(__systemctl list-unit-files "$PREFIX*" | awk '{print $1, $2}') ) }
````

compared with the one zimfw ships:

````
_systemctl_unit_state () {
        typeset -gA _sys_unit_state
        _sys_unit_state=($(__systemctl list-unit-files "$PREFIX*" ))
}
````

Request:

Could you possible include this fix in zimfw? thanks 

[reference](https://github.com/ohmyzsh/ohmyzsh/issues/8751)

**Comment by ericbn** [comment]
Hi @cattyhouse. Zim does not ship with any `_systemctl_unit_state` function, not even in one of our modules. Not sure where the one you have came from.

**Comment by cattyhouse** [comment]
thanks for the info, looks like the function is  from systemd, i will close this and just add the working function to my ~/.zshrc
