### ISSUE TITLE
what happened to vi mode?

### ISSUE THREAD

**Issue by Rckss** [zimfw/zimfw#397]
hellow
how can i configure zim to vi mode like old times?
i can't find anywhere in documentation :(

**Comment by ericbn** [comment]
Hi @Rckss. This was previously in the .zimrc file, and now all Zsh configuration moved to `.zshrc`. Check the [template file](https://github.com/zimfw/install/blob/55582b96249ccd25ac239c862b1b7e98dbc3b3dd/src/templates/zshrc#L22).

**Comment by Rckss** [comment]
Thank you so much @ericbn
