### ISSUE TITLE
Install script should be idempotent

### ISSUE THREAD

**Issue by danielporto** [zimfw/zimfw#398]
Description
-----------
Running install script more than once multiply the installation snippets in .zshrc and .zshenv and .zlogin
The result is that the zsh gets slower and slower.

It would be nice if nothing happens in case of a second attempt to install, or a warning shows up and asks for skip/reinstall (with a flag to force the choice)

Steps to reproduce
------------------
Just run the install script multiple times and check the content of the files
Images or other information
---------------------------
![image](https://user-images.githubusercontent.com/1652891/83604400-03629780-a56e-11ea-90e1-0a92a8d25db6.png)

**Comment by ericbn** [comment]
Hi @danielporto. Yeah, this would be a good improvement in the install scripts. And I wonder: Why do you want to run the install script multiple times?

**Comment by danielporto** [comment]
Hi @ericbn , I'm actually updating my deployment scripts similar to dotbot but written in python with most of my configuration for the daily use (still very much a work in progress). Most of it is idempotent (I use ansible a lot and come to appreciate this approach).

A reason is that in use many machines in my usual day routine. Connect to remote nodes, spawn Vms, containers etc... using zshell inside them makes my workflow smoother. Therefore i find myself reinstalling zsh a lot. 

Oftentimes when I update my environment and call a bunch of scripts and noticed that the shell was getting slower and slower, even worse than before using zimfw. with nothing installed.
Dug a little bit and found a dozen of installation entries.

**Comment by ericbn** [comment]
Updated it to fail if Zim is already installed. Actually there was a regression that I fixed in https://github.com/zimfw/install/commit/29586b7dacc8f77b3e9963409ea198a212d2658a, and I've also added an extra check in https://github.com/zimfw/install/commit/3f995b3445770b8ab341ccd2a52d58a0b2dc731f.
