### ISSUE TITLE
local modules?

### ISSUE THREAD

**Issue by colinxs** [zimfw/zimfw#399]
Perhaps this feature already exists but I couldn't find it.

Is it possible to specify a *local* path in `.zimrc`? I have a custom module that looks like:
```
~/.zmodules/mymodule/functions/
~/.zmodules/mymodule/init.zsh
```
and I'd like to be able to add an entry in `.zimrc` like:
```
zmodule "${HOME}/.zmodules/mymodule"
```
and still get the conveniences of `zimfw` (namely the handling of the completion cache/`.zwc` compilation).

Is this possible?

**Comment by ericbn** [comment]
Hi @colinxs,very good point! The implementation for local modules is actually incomplete, as it will force you to run `zimfw install` to have the local module copied to `${ZIM_HOME}/modules`. That does not make much sense, and the local module should be used directly from its original path, as you pointed out. Let me fix that.

**Comment by ericbn** [comment]
Change still unreleased. To use the HEAD version of zimfw.zsh, manually download it from https://raw.githubusercontent.com/zimfw/zimfw/master/zimfw.zsh.

**Comment by ericbn** [comment]
New version 1.2.2 released with this change.

**Comment by colinxs** [comment]
Hi @ericbn! I just wanted to thank you for getting this done, it's been great. I have a question about the "absolute path" requirement outlined in the docs. Shouldn't any path be valid so long as it _expands_ to an absolute path? E.g. `~/mymodule` works just fine because `~` is expanded when `.zimrc` is sourced.

Thanks!

**Comment by colinxs** [comment]
Found a bug, unfortunately: `zimfw clean` ignores modules specified with an absolute path. `zimfw compile` works, however, since it just relies on `login_init.zsh`.

**Comment by ericbn** [comment]
@colinxs, I don't think zimfw should clean modules that were not installed by it. I'm assuming absolute path modules are all installed externally, not installed by zimfw.

**Comment by colinxs** [comment]
@ericbn Currently, `zimfw compile` will generate `.zwc` files for local modules (e.g. `zmodule ~/path/to/module`). Given that, it makes sense that `zimfw clean` should reverse that action. So it seems like there's two valid options:
1) `compile`/`clean` work for local modules
2) `compile`/`clean` ignore local modules

I would prefer option (1) so that local/remote plugins are treated the same (and selfishly because compilation was the main reason I opened this PR initially :) )

**Comment by ericbn** [comment]
@colinxs, sorry, I misunderstood what you meant by "clean". I was thinking of "uninstalling", but I see you mean cleaning the the Zsh compiled files. You used the right term!  :- )

Sure, "zimfw clean" should clean all the Zsh compiled files generated by "zimfw compile", and that includes the ones in the absolute path modules. I'll work on that. Thanks for reporting the issue.
