### ISSUE TITLE
Installing zim with .zimrc already there

### ISSUE THREAD

**Issue by PierreMarchand20** [zimfw/zimfw#400]
Description
-----------

I am using zim with [yadm](https://yadm.io), that I would describe as git, but for your home repository. The issue I have is that I put my `.zimrc` and `.zshrc` files in my repo yadm/git, but then, when I try to install zim, it fails because it considers there is already a zim installation.

Is there a way to circumvent this ? Do I need to use the install script if I put zim as a submodule and I run `zimfw install` instead for example ?

By the way, I guess it is something you just added from #398, but I am not sure that failing is the right call. For example, yadm has a bootstrap function (see [here](https://yadm.io/docs/bootstrap#)), kind of a script that installs everything, in my CI I test it to be idempotent. But then it will automatically fail. For me the idea that it must be idempotent comes from the fact that if you just change one thing in you installation script, you can run it and it will only update the part you changed without breaking the rest (because it is idempotent). 

To quote yadm documentation: "It is best to make the logic of your bootstrap idempotent—allowing it to be re-run in the future when you merge changes made on other hosts." Note that it can apply to any installation script for dotfiles, it is not specific to yadm I think.

Steps to reproduce
------------------

1. Have a `.zimrc` or a `.zshrc` with some zim options before installing zim.

Images or other information
---------------------------

You can find my CI where the issue appears [here](https://travis-ci.com/github/PierreMarchand20/dotfiles/jobs/344424831)

**Comment by ericbn** [comment]
Hi @PierreMarchand20. If you already have your .zimrc and .zshrc files, then it would also not make sense to have the install prepending the Zim configuration to these files, as I imagine you already have it there, right? In this sense, your issue is similar to #398.

Maybe a solution is to skip the step of prepending the Zim configuration when the install detects that Zim is already configured, instead of aborting. Does this make sense and solve your issue? Any different suggestion?

**Comment by PierreMarchand20** [comment]
If the install process does something else than prepending the Zim configuration to these files, then yesI agree! But may be someone will want the current behaviour (be warned that there are still some Zim configuration to delete to get a fresh install). So may be a flag in the install script to not prepend these files ? 

So may be there could be some default behaviour (prepending or not) and a flag to do the opposite.

**Comment by PierreMarchand20** [comment]
So I just struggled with a bug in my configuration (see #401) trying to overcome this issue in the meantime, and I understood that `.zshrc` will need to be compiled. Is this something that the install process will do, even if it does not prepend the the files ?

**Comment by ericbn** [comment]
I'm getting the impression you don't need the install at all, since you have an external software managing your dotfiles, and you already have your Zsh startup files configured to your liking. The last piece you need is the zimfw.zsh script downloaded to your ZIM_HOME, and then running `zimfw install`. Check the (manual installation steps)[https://github.com/zimfw/zimfw/blob/master/README.md#manual-installation].

**Comment by PierreMarchand20** [comment]
So instead of calling the installation script, I can download `zimfw.zsh`, `.zshenv` and `.zlogin`. And then `source ~/.zim/zimfw.zsh install`. The only issue I have with that is that I need to do the last step in a `zsh` shell, but since I already have my `.zshrc` ready, it tries to run `.zim/.init.sh` and I get an error when starting a `zsh` shell. 

Another possibility is to do what I am doing now, just rename my `.zshrc` and `.zimrc`, install `zim` using the script, replace the default `.zshrc` and `.zimrc` (and not forget to delete `.zshrc.zwc` ^^).

**Comment by PierreMarchand20** [comment]
Thank you for your answer, It works fine! (I did not know about `-c` flag) do you think I should also commit `zimfw.zsh`, or download it each time on a fresh install ?

**Comment by ericbn** [comment]
The `zimfw.zsh` should be small enough so you can commit it, and commit future upgrades too, but it's up to you and to how you're organizing your provisioning script.

**Comment by PierreMarchand20** [comment]
Thank you for your answers! I think I have enough information to deal with my issue now so I am closing it.

Again thank you for taking the time to think about this.

**Comment by ericbn** [comment]
You're welcome. I'm considering updating the manual installation instructions to be more independent of Zsh, so user can learn about `zsh -c "source ~/.zim/zimfw.zsh install"` or `zsh ~/.zim/zimfw.zsh install` (which actually might me simpler). @Eriner, what do you think?
