### ISSUE TITLE
Issue modyfing .zshrc

### ISSUE THREAD

**Issue by PierreMarchand20** [zimfw/zimfw#401]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zimfw info` and paste the output below:

```
zimfw version: 1.2.1 (previous commit is c0d7862)
ZIM_HOME:      /root/.zim
Zsh version:   5.7.1
System info:   Linux 4c825c3f4874 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
```

- gist of .zimrc: https://github.com/PierreMarchand20/dotfiles/blob/master/.zimrc
- gist of .zshrc: https://github.com/PierreMarchand20/dotfiles/blob/master/.zshrc

Description
-----------

I am using zim with yadm, that I would describe as git, but for your home repository, and I have `.p10k` file with my configuration saved in a repo. The issue I have is that after installing it with zim, when starting again zsh, the configuration wizard of p10k is triggered while it should not since I already have a `.p10k` file.

I raised the issue on the p10k repo romkatv/powerlevel10k#807 and it seems that there is an issue about race condition that makes the `.zshrc` not sourced. TBH I know nothing about all these things, and I did not really understand... but I think it is an issue coming from zim, for sure if I install p10k without zim, I do not have any issue.

Steps to reproduce
------------------

1. You can use my `.p10k` file https://github.com/PierreMarchand20/dotfiles/blob/master/.p10k.zsh put it in your ${HOME} folder and install p10k with zim.

**Comment by lnicola** [comment]
I don't use `yadm`, but `p10k` works fine for me with a `.p10k.zsh` symlink to my dotfiles repo.

**Comment by romkatv** [comment]
Powerlevel10k is a red herring here. You can remove it from your setup and will still have this problem. Try it.

1. Remove powerlevel10k from zimrc.
2. Add `echo hello` to `zshrc`.
3. Commit everything.
4. Install everything like you usually do.
5. Start zsh.
6. Observe that `hello` is not printed on the screen.

This is because you zshrc is not used when you start zsh.

**Comment by PierreMarchand20** [comment]
I can confirm that. Thank you for weighing in @romkatv, as I said, I am a newbie in all these things so your words make things more clear for sure. I will update the title accordingly.

But then, what I do not understand is, why the configuration wizard is only triggered the first time ? It should be always triggered if the `.zshrc` is not used no ? (again newbie here) and which `.zshrc` is used then ?

**Comment by romkatv** [comment]
> But then, what I do not understand is, why the configuration wizard is only triggered the first time ?

When you start zsh for the first time, it does not use your zshrc. When you start it for the second time, it does use your zshrc.

When your zshrc is not used, p10k.zsh is not used either (because it's sourced from zshrc), so no powerlevel10k parameters are defined. When no powerlevel10k parameters are defined, configuration wizard starts automatically.

As I mentioned in the other issues, this problem might be caused by zshenv created by zimfw. I'd put about 30% confidence in this prediction.

**Comment by PierreMarchand20** [comment]
Actually I made a mistake when I tried what you suggested. I do get `hello` the first time.

**Comment by romkatv** [comment]
Maybe it's timing-dependent. Or maybe it's something else. You can reproduce it, so you can debug it. I understand it's not the area of your expertise but you can add `echo` here and there to figure out what executes and what doesn't, right? You also can remove things from your setup one-by-one until you are down to something that you *can* understand.

**Comment by PierreMarchand20** [comment]
I did remove everything except zim and p10k, and as soon as I put something new somewhere in `.zshrc`, it works. 

In the meantime, I learned that `.zwc` are compiled versions of zsh files, and deleting `.zshrc.zwc` makes everything work. My guess is that it is related to #400, the compiled file is not updated and so, it does not look for `.p10k.zsh`

**Comment by romkatv** [comment]
> In the meantime, I learned that `.zwc` are compiled versions of zsh files, and deleting `.zshrc.zwc` makes everything work. My guess is that it is related to #400, the compiled file is not updated and so, it does not look for `.p10k.zsh`

Yep, that's my guess. zimfw calls zcompile from `.zlogin`. To make things worse, it calls it in the background. This introduces races even when the user is only employing one shell.

**Comment by romkatv** [comment]
> I did remove everything except zim and p10k, and as soon as I put something new somewhere in `.zshrc`, it works.

That's not minimal enough though. You can also remove p10k.

**Comment by PierreMarchand20** [comment]
Yes you are right, I could remove `p10k` and reproduce the issue. But I am not sure it is due to some race condition.

To update `.zshrc` with my configuration, I was doing `mv .my_zshrc .zshrc`, and it seems that it does not trigger the compilation of `.zshrc.zwc`, but if I just modify the `.zshrc` after the installation of `zim`, it does.

So to reproduce, 
1. create `.my_zshrc` with `echo Hello`
2. install zim
3. `mv my_zshrc .zshrc`
4. start a shell and you should not see `Hello`.

**Comment by romkatv** [comment]
> To update `.zshrc` with my configuration, I was doing `mv .my_zshrc .zshrc`

Oh, I see. That explains it. When you `mv` a file, its `mtime` doesn't change. So `mtime` of `.zshrc.zwc` is newer than that of your file.

In general it's a bad idea to zcompile anything that users can modify/copy/move. Zimfw shouldn't be zcompiling your zshrc.

**Comment by romkatv** [comment]
If you `touch` that file after moving, it'll work.

**Comment by PierreMarchand20** [comment]
Thank you for your time, sorry that it was not related to p10k at all at the end. I learned something today ^^

**Comment by romkatv** [comment]
> Thank you for your time, sorry that it was not related to p10k at all at the end.

No worries.

**Comment by ericbn** [comment]
If you have a newer .zsh file than the correspondent .zsh.zwc compiled file, Zsh will use the newer .zsh file. So I don't think the issue here is related to compiled files. We try to keep things simple at Zim, and suggestions to make it simpler are always welcome.

Simple test on how Zsh picks the newer file:

![Screen Shot 2020-06-08 at 14 46 40](https://user-images.githubusercontent.com/4120606/84077451-f5ad7780-a99c-11ea-9e9b-d42790559478.png)

**Comment by PierreMarchand20** [comment]
The difference in my case was that I did not directly modify the .zshrc, but I was replacing it by another file. Following what @romkatv said:

> When you mv a file, its mtime doesn't change. So mtime of .zshrc.zwc is newer than that of your file.

But it is a very particular case, and I am not sure anything can be done anyway. I also like when things are simple, that is why I like to use zim ^^

**Comment by romkatv** [comment]
> We try to keep things simple at Zim, and suggestions to make it simpler are always welcome.

What do you think about not zcompiling user's rc files?

**Comment by ericbn** [comment]
I see a ~3% increase in startup time for the default Zim installation when we don't compile the Zsh startup files. Not a significant increase. It might grow as the startup files get more complex. Not sure how much the case of using mv to override these files (thus preserving the modification time and making Zsh still look at the compiled .zwc file instead) can be considered an edge case. @Eriner, thoughts?
