### ISSUE TITLE
Feature request: async or lazy-load plugins

### ISSUE THREAD

**Issue by sodiumjoe** [zimfw/zimfw#403]
Hi, first off, thanks for the great framework!

I've been profiling my zsh startup time and most of it is in plugin initialization. However, for many plugins, I don't really need the functionality immediately, it's fine if it's asynchronous or even lazy loaded, when I use a command. The specific plugin I'm thinking of is https://github.com/skywind3000/z.lua, which adds ~30ms to my shell startup, but there are others, too.

**Comment by rjcoelho** [comment]
Use zsh defer

**Comment by sodiumjoe** [comment]
@rjcoelho do you mean `zsh-defer zmodule some/module`? When I tried this, it seems to interfere with installation of modules, like zim doesn't understand that they need to be installed. Also `zimfw uninstall` removes all modules prefixed with `zsh-defer`.

**Comment by ericbn** [comment]
The .zimrc file is not loaded during the startup, so calling zmodule with zsh-defer will not defer the startup of the modules.

**Comment by rjcoelho** [comment]
I mean git submodule include z.lua and zsh-defer eval "$(lua /path/to/z.lua --init posix)"
