### ISSUE TITLE
feature request: run command to initialize a module instead of sourcing a file

### ISSUE THREAD

**Issue by sodiumjoe** [zimfw/zimfw#405]
The plugin under question is: https://github.com/skywind3000/z.lua#install

Currently I just have the following in my `.zshrc`:
```
eval "$(lua ${ZIM_HOME}/modules/z.lua/z.lua --init zsh enhanced once fzf)"
```

But it'd be nice to be able to add that to the `zmodule` invocation.

**Comment by ericbn** [comment]
I was thinking of having a generic `--run` option that uses `{}` as a placeholder for the module root directory. So you could use something like:

```
zmodule skywind3000/z.lua --run 'eval "$(lua {}/z.lua --init zsh enhanced once fzf)"'
```

Maybe it should override the default values of the other initialization options (`-f|--fpath`, `-a|--autoload`, `-s|--source`) when defined.
                     

@Eriner, what do you think?

**Comment by ericbn** [comment]
New version was released with this change. The `-c|--cmd` option in `zmodule` should work as in the [comment above](https://github.com/zimfw/zimfw/issues/405#issuecomment-650685028).
