### ISSUE TITLE
How do I extend/customise ZSH after installing zimfw

### ISSUE THREAD

**Issue by spankme** [zimfw/zimfw#408]
I'm pretty happy with zimfw but I can't find some basic information on how to further customise ZSH after zimfw is installed: where do I put my personal exports or aliases, to avoid any update and upgrade conflicts? Would it be ~/.zshrc or ~/.zimrc? Any other place?

**Comment by lnicola** [comment]
I put them into `.zshrc` and `.pam_environment`, e.g. https://github.com/lnicola/dotfiles/blob/master/.zshrc.

**Comment by ericbn** [comment]
The files sourced by Zsh during the startup are [documented here](http://zsh.sourceforge.net/Intro/intro_3.html). The ~/.zimrc file is not sourced during startup. It should only be used to set the zimfw modules.
