### ISSUE TITLE
Request: New repository option for zmodule to disable cloning of a plugin's submodules

### ISSUE THREAD

**Issue by AndydeCleyre** [zimfw/zimfw#409]
Description
-----------

A plugin/repo's submodules are not always needed for regular use, and in those cases, refraining from cloning them can save the user some space and bandwidth. A new repository option to `zmodule`, something like `--no-submodules`, could be handy.

**Comment by ericbn** [comment]
Hi @AndydeCleyre. Can you give some examples of plugins for which it does not make sense to install/update with is submodules?

**Comment by AndydeCleyre** [comment]
I don't know offhand if there are many. What brought this to my attention was a plugin of my own; in the development version, I'm using a [third party project](https://mcss.mosra.cz/) to build documentation, and it makes sense to include that third party project as a submodule for use in development and CI, but not for regular users.

FWIW, I looked at some alternative methods for installing Zsh plugins to see how submodules are generally handled. I don't use any of the frameworks full time, so misunderstandings are possible. The issues linked are created by me.

Manager  |  Submodules cloned by default?  |  If so, how to disable?
-------  |  -----------------------------  |  ----------------------
`git clone` |  ❌  |  -
`git submodule add` (dotfiles manager like `yadm`)  |  ❌  |  -
antibody  |  ✅  |  None; getantibody/antibody#366
antigen  |  ✅  |  None; zsh-users/antigen#711
oh my zsh (`git clone`)  |  ❌  |  -
prezto (`git clone`)  |  ❌  |  -
zgen  |  ✅  |  None; tarjoilija/zgen#129
zim  |  ✅  |  None; zimfw/zimfw#409
zinit  |  ❌ (install); ✅ (update)  |  `zinit ice cloneopts` before loading
zplug  |  ❌  |  -

**Comment by ericbn** [comment]
> I'm using a third party project to build documentation, and it makes sense to include that third party project as a submodule for use in development and CI, but not for regular users.

If you're using a submodule to build documentation, and the submodule is not intended to be used by regular users, then the solution is almost implied in there: don't include the submodule in the branch that is intended for the regular users.

Anyway, this looks like an edge case to me, and I'm not in favor of adding an option in Zim to cover this (and I hope other framework developers do the same). The main issue with Zsh plugins is that there is no real standard for them. Most of the "standard" is abstracted from how most of the frameworks or plugin managers work, so I strongly think the simpler they are, the better for everyone.

**Comment by AndydeCleyre** [comment]
I respect your decision for your project, and will not continue the discussion if/when you close the issue.

My perspective here is that submodules by their (very useful) nature are *already* excluding their content "by default" -- a `git clone`, that is; and that "simple" in this context would be working similarly to `git clone`.

Do you know offhand of any Zsh plugins with submodules that *do* want them included during user installs?

**Comment by ericbn** [comment]
@AndydeCleyre, good question. I checked all themes and plugins listed under [unixorn's awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins/blob/d1017468c99ecd6fe3c3fa96481f65b396584976/README.md), and here are the ones that use submodules:

### Themes

* [alien-minimal](https://github.com/eendroroy/alien-minimal)
* [alien](https://github.com/eendroroy/alien)
* [dissonance](https://github.com/RyanScottLewis/theme-dissonance-zsh)
* [geometry](https://github.com/geometry-zsh/geometry)
* [minimal (glsorre)](https://github.com/glsorre/minimal/)
* [powerlevel9k](https://github.com/bhilburn/powerlevel9k)
* [powerline (jeremy)](https://github.com/jeremyFreeAgent/oh-my-zsh-powerline-theme)
* [powerline-hs](https://github.com/rdnetto/powerline-hs)
* [prompt_j2](https://github.com/malinoskj2/prompt_j2)
* [slimline](https://github.com/mengelbrecht/slimline)
* [spaceship](https://github.com/denysdovhan/spaceship-prompt)
* [theta](https://github.com/eendroroy/theta)

### Plugins

* [diff-so-fancy](https://github.com/zdharma/zsh-diff-so-fancy)
* [dircolors-solarized](https://github.com/joel-porquet/zsh-dircolors-solarized)
* [dirrc](https://github.com/gmatheu/shell-plugins)
* [docker-machine](https://github.com/asuran/zsh-docker-machine)
* [dropbox](https://github.com/zpm-zsh/dropbox)
* [explain-shell](https://github.com/gmatheu/shell-plugins)
* [git-add-remote](https://github.com/caarlos0/git-add-remote)
* [git-sync](https://github.com/caarlos0/zsh-git-sync)
* [gitignore](https://github.com/voronkovich/gitignore.plugin.zsh)
* [kubectx (unixorn)](https://github.com/unixorn/kubectx-zshplugin)
* [open-pr](https://github.com/caarlos0/zsh-open-pr)
* [pg](https://github.com/caarlos0-graveyard/zsh-pg)
* [profile-secrets](https://github.com/gmatheu/shell-plugins)
* [project (gko)](https://github.com/gko/project)
* [safe-rm](https://github.com/mattmc3/zsh-safe-rm)
* [ssh-connect](https://github.com/gko/ssh-connect)
* [z-a-man](https://github.com/zinit-zsh/z-a-man)
* [zed](https://github.com/eendroroy/zed-zsh)

### Submodules

And here are all the submodules used in the repositories above:

* https://github.com/Lokaltog/powerline-fonts
* https://github.com/RyanScottLewis/theme-dissonance-tools
* https://github.com/ahmetb/kubectx
* https://github.com/andreafabrizi/Dropbox-Uploader
* https://github.com/caarlos0/shell-ci-build
* https://github.com/caarlos0/shell-travis-build
* https://github.com/chrissicool/zsh-256color
* https://github.com/eendroroy/promptlib-zsh
* https://github.com/github/gitignore
* https://github.com/gko/listbox
* https://github.com/kaelzhang/shell-safe-rm
* https://github.com/kward/shunit2
* https://github.com/mafredri/zsh-async
* https://github.com/mgee/gitline
* https://github.com/powerline/powerline
* https://github.com/rtomayko/ronn
* https://github.com/rupa/z
* https://github.com/seebi/dircolors-solarized
* https://github.com/so-fancy/diff-so-fancy
* https://github.com/wallyhall/shini
* https://github.com/zdharma/zshelldoc

Do you see any repository above where you would not want the submodules installed too?

**Comment by AndydeCleyre** [comment]
Yes, thanks for doing the research. I tried testing a few with `zplug`, and not only are the submodules desired for general use, but they are pulled in by `zplug` despite my earlier test indicating it wouldn't do so. I don't know if my test was off because I was specifying a branch manually or what, but:

Yes, if you're not going to add an option to enable/disable submodules, pulling them in (as you already do) is the right thing to do. I think it would be handy to be able to disable that per-plugin (wild west and all that), so I'll leave closing this issue to you.

Thanks again for gathering all this info, for writing out the design rationale, and for this project altogether.

**Comment by ericbn** [comment]
@AndydeCleyre, now we have a `--use degit` option in `zmodule` that will use `curl` or `wget` to install the module. As a "feature"/limitation of this, submodules will not be installed when Zim's degit is in use. Do you think this is a solution for the issue you raised here?

Or maybe I should add one more option to `zmodule` to disable submodules. Something like `-S|--no-submodules`.

**Comment by AndydeCleyre** [comment]
The degit method does look good to me!
