### ISSUE TITLE
Installation script fails if file .zlogin not present

### ISSUE THREAD

**Issue by sebastianst** [zimfw/zimfw#410]
Description
-----------

If file `.zlogin` is not present, the installation script fails.

Steps to reproduce
------------------
```
wget -nv -O - https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
2020-08-12 11:07:40 URL:https://raw.githubusercontent.com/zimfw/install/master/install.zsh [11384/11384] -> "-" [1]
) Git is installed.
) Using Zsh version 5.8
) Your ZIM_HOME is the default one.
) Zsh is your default shell.
) No other Zsh frameworks detected.
) Downloaded the Zim script to /home/seb/.zim/zimfw.zsh
) Copied Zim template to /home/seb/.zimrc
) Prepended Zim template to /home/seb/.dotfiles/zshrc
) Prepended Zim template to /home/seb/.dotfiles/zshenv
zsh: no such file or directory: /home/seb/.zlogin
x Error copying Zim template to /home/seb/.zlogin
```

Can probably be fixed by letting zim create the file, if not present.

**Comment by ericbn** [comment]
Not sure what was the issue here, as the install script was already creating missing files even before this was reported. See [here](https://github.com/zimfw/install/blob/08e5bf9608b4c027c8407bf5ace3318028c0fa47/install.zsh#L323-L341).

@sebastianst, can you still reproduce it?

**Comment by sebastianst** [comment]
I cannot reproduce it right now. I don't know why the installation script _shouldn't_ have write-access to `.zlogin` though... I'll close this issue and if anyone else is reporting this (or I happen to accidentally reproduce it on another machine), we can reopen it.
