### ISSUE TITLE
vim command resuming the background process instead of starting a new one

### ISSUE THREAD

**Issue by in42** [zimfw/zimfw#411]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zimfw info` and paste the output below:

```
#Paste the output here
Latest zimfw version is 1.3.2. You're using version 1.2.1. Run zimfw upgrade to upgrade.

zimfw version: 1.2.1 (previous commit is c0d7862)
ZIM_HOME:      /Users/vikrampal/.zim
Zsh version:   5.7.1
System info:   Darwin Vikrams-MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

- gist of .zimrc:
Default
- gist of .zshrc:
Default

Description
-----------
If there is a vim process suspended in the background like this:
[1]  + 1184 suspended  vim

On entering the `vim` command again, the background process is resumed instead of starting a new process.

Steps to reproduce
------------------
Open a vim process. Suspend it using Ctrl-Z. Then again type `vim` at the prompt. The background process is resumed instead of starting a new one.

Images or other information
---------------------------

**Comment by Plloi** [comment]
Can you confirm disable zim to ensure it is what's doing this. I don't think it does anything that should case this behavior.

**Comment by ericbn** [comment]
This is a feature of Zsh that we enable in the[environment](https://github.com/zimfw/environment#job-control) module:

> * `AUTO_RESUME` resumes an existing job before creating a new one.

You can add `setopt NO_AUTO_RESUME` at the end of your .zshrc file to disable this.

**Comment by in42** [comment]
Thanks, it worked.

**Comment by ericbn** [comment]
@Eriner, what do you think about removing the `AUTO_RESUME` option from the environment module? I never used this one (was doing fg instead), and I'm not sure how intuitive it is to be considered a "sane default".

**Comment by Eriner** [comment]
I too always use `fg` but agree that the default should be changed to make the foregrounding an explicit operation (vs an implicit same-binary `fg`).
