### ISSUE TITLE
bug: _zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by znedw** [zimfw/zimfw#413]
Any commands returns `_zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?`

> zsh -df
_zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?
nas% source .zim/modules/zsh-autosuggestions/zsh-autosuggestions.zsh
nas% ls

no problem manually sourcing zsh-autosuggestions

```
❯ zimfw info
_zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?
zimfw info
zimfw version: 1.3.2 (previous commit is ccace0c)
ZIM_HOME:      /home/zach/.zim
Zsh version:   5.8
System info:   Linux nas 5.8.17_1 #1 SMP Fri Oct 30 12:13:24 UTC 2020 x86_64 GNU/Linux
```

- gist of .zimrc:
- gist of .zshrc:
https://gist.github.com/znedw/159e7c215522c74f859cd8ffa2d4c572

**Comment by znedw** [comment]
Clean install resolved the issue

**Comment by amitbha** [comment]
After upgrade, the '~/.zlogin', '~/.zshenv' are wrongly configed, sourcing '${ZIM_HOME}/login_init.zsh' twice.

**Comment by amitbha** [comment]
source `pure` theme: `zmodule sindresorhus/pure --source async.zsh --source pure.zsh` will lead to this problem.

**Comment by ericbn** [comment]
If you upgraded from Zim pre-1.x to Zim 1.x, you need to manually edit your startup files to remove or rewrite the lines from the pre-1.x installation. If you're sourcing login_init.zsh twice, then you still have pre-1.x lines around.

**Comment by andrius** [comment]
> source `pure` theme: `zmodule sindresorhus/pure --source async.zsh --source pure.zsh` will lead to this problem.

I have been using `zim` and pure for very long time, but recently have updated `zim` and having same issue

**Comment by antoineco** [comment]
Same issue on a fresh installation with `zmodule sindresorhus/pure -s async.zsh -s pure.zsh -t v1.16.0` inside `.zimrc`.

**Comment by sebastianst** [comment]
I'm having this issue after a fresh reinstallation, even when using the default theme `asciiship` or `eriner`. I never used `pure` and didn't change the order of any `zmodule` invocations. I also checked for remnants of an old installation but couldn't find any...

What's the root cause of this problem?

**Comment by sebastianst** [comment]
Found the culprit. I had the following in my `.zshrc` after zim's config:
```zsh
# vi mode status
# Add hooks instead of overwriting zle-line-init etc.
function vim-mode-prompt {
  VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
  RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}$EPS1"
  zle reset-prompt
}

autoload -Uz add-zle-hook-widget
add-zle-hook-widget line-init vim-mode-prompt
add-zle-hook-widget keymap-select vim-mode-prompt
```

**Comment by ericbn** [comment]
Thanks for the update, @sebastianst. Is this related to #379 (meaning this comes from grml-zsh-config or anything that grml adds to your startup files)?

**Comment by sebastianst** [comment]
No, those were two unrelated issues I was facing after upgrading zim a while ago 😅 I don't remember when and why I put those lines there.
