### ISSUE TITLE
Issue installing from arch linux AUR.

### ISSUE THREAD

**Issue by Magnusm94** [zimfw/zimfw#414]
Sorry for not following template.

While installing I get this error:
```
==> Updated version: zsh-zim-git r541.c6f0720-1
==> Sources are ready.
==> Making package: zsh-zim-git r541.c6f0720-1 (Sat 14 Nov 2020 03:04:05 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Entering fakeroot environment...
==> Starting package()...
cp: cannot create regular file '/home/magnus/.cache/yay/zsh-zim-git/pkg/zsh-zim-git/usr/lib/zim/templates/zshrc': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error making: zsh-zim-git
```

I did make an attempt to create the missing file before installing again, and the issue is that it deletes the files before it is supposed to use them. 
Installing with curl still works great :+1:

**Comment by ericbn** [comment]
Hey @Magnusm94. AFAIK, the arch package is outdated. Please check #368. Officially, we currently support [these installation methods](https://github.com/zimfw/zimfw/blob/master/README.md#installation).

**Comment by Magnusm94** [comment]
Thanks for clearing that up :)
