### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by Spriithy** [zimfw/zimfw#416]
Hi

I would like to use ZIM in a closed network without access to internet. For this, I have installed ZIM on a machine, configured it as I wished and bundled it in a zipped file, uncompressed it onto non-connected machine and had to rename all occurences of names, paths and links that were not suitable.

I wish there was a bundled version of ZIM I could just stick somewhere and install could work offline.

Thanks in advance !

**Comment by Plloi** [comment]
once setup  all you should need is the  `.zim` directory and your configs/loading code from `.zshenv`, `.zshrc`,  `.zlogin`, and `.zimrc`...  think you made bundling your install harder than it needed to be....

**Comment by Spriithy** [comment]
Nah, I need to use it for different users. And it needs some grepping....

**Comment by Plloi** [comment]
but nothing should have a username hard pathed...

**Comment by ericbn** [comment]
@Spriithy, just don't include your `${ZIM_HOME}/login_init.zsh` and `${ZIM_HOME}/init.zsh` files, which should be the only ones containing the hardcoded path to your `ZIM_HOME`. All other files inside `ZIM_HOME` should work when copying the whole directory around for other users. And make sure you're using the last version of the [zimrc template](https://github.com/zimfw/install/blob/master/src/templates/zimrc) as a fix was done [on Jan 4](https://github.com/zimfw/install/commit/c9dd5ee6e08f0884abcd267318768f7412e1a936) to create the scripts I mentioned above the first time you start a shell session.

More details on our [Announcements](https://github.com/zimfw/zimfw/discussions/426) discussion topic.
