### ISSUE TITLE
Zim[fw] logo?

### ISSUE THREAD

**Issue by OneMohrTime** [zimfw/zimfw#418]
Hey! Hopefully opening a new issue for non-code isn't an...issue. But, I was following #367 earlier this year with the intent of helping (then, 2020) – and I saw that it was recently completed (looks great too!).

But being a fan, I wanted to contribute in some way – and saw that #183 was opened years ago and never finished.

I took some time last night and this morning to iterate, and came out with a couple groups of ideas that might be worth discussing. I tried to leave color out for now, other than some red, thinking the maintainers may want to pick a color to associate **zimfw** with. If none of these float the boat, absolutely no worries 🤘 

![zim-fw-ideas](https://user-images.githubusercontent.com/11075805/99885005-fa3eb300-2bff-11eb-85db-99d77ba7bc8b.png)

**Comment by michaelhthomas** [comment]
Thanks for working on this! I love the look of #1 personally.

**Comment by ericbn** [comment]
Hey @OneMohrTime, thanks for expressing your love to Zim!  :- )

I like the style of 3 more than the others!

**Comment by michaelhthomas** [comment]
Number 3 has grown on me as well. Already trying it out on the dev build of the site.

**Comment by OneMohrTime** [comment]
@michaelhthomas @ericbn awesome! I'll leave this here a bit longer for the admins to look at and consider, and I can refine and finish it over some Thanksgiving time off.

**Comment by OneMohrTime** [comment]
I tried to tow the line between options 1 & 3 – here's where I landed

![logos](https://user-images.githubusercontent.com/11075805/100563809-5606dd00-328d-11eb-90e9-b2d3a587dcf1.png)
[logo-sample.zip](https://github.com/zimfw/zimfw/files/5613531/logo-sample.zip)

**Comment by ericbn** [comment]
Hi @OneMohrTime. I like how you kept the eyes as some inspiration from the original logo @Eriner designed!

**Comment by michaelhthomas** [comment]
Thanks @OneMohrTime! Is there any way I could get the logos in svg (or high res png)? Looks great!

**Comment by OneMohrTime** [comment]
@michaelhthomas Got em attached in a `.zip`!

The lettering is based on [Halogen](https://www.pixelsurplus.com/freebies/halogen) which has a free variation, if interested.
The red color is `#DC143C`, which is also the CSS color code for `crimson`

SVG, PNG Files
[Logo-Bundle.zip](https://github.com/zimfw/zimfw/files/5626679/Logo-Bundle.zip)

_optional banner using original green & red_
![banner](https://user-images.githubusercontent.com/11075805/100823287-eece6180-3421-11eb-9487-13c25751c5d5.jpg)

Enjoy! Feel free to close this out when you've got what you need

**Comment by OneMohrTime** [comment]
![z-icon](https://user-images.githubusercontent.com/11075805/101272052-b945b300-3756-11eb-9fe1-c49f5821b2fe.jpg)
![zim-icon](https://user-images.githubusercontent.com/11075805/101272053-ba76e000-3756-11eb-9dd5-32d12e7b22e5.jpg)

Forgot some usable favicons 🤦 rusty designer

**Comment by ericbn** [comment]
@OneMohrTime, do you happen to have the above rusty logos in a non-lossy format (png)? It would be cool to have them in a zip file too, if you have the files still around! Thanks!

**Comment by OneMohrTime** [comment]
@ericbn definitely! Should I attach them here, or email them to someone?

**Comment by ericbn** [comment]
@OneMohrTime, cool! If it's possible to attach the archive here, so it's publicly available, maybe better. Otherwise, you can find my email address [here](https://github.com/zimfw/zimfw/blob/master/CODE_OF_CONDUCT.md#enforcement).

**Comment by OneMohrTime** [comment]
@ericbn this `.zip` has some PNG versions of the rusty logos. I've also added the `.psd`, in case there are small cases for modifications.

I'll close this out, as it's not an active project anymore. I'm not sure how you want this accessible, so feel free to reopen it if that's what you had in mind. Thank you for the project!

[Logo-Bundle.zip](https://github.com/zimfw/zimfw/files/5793057/Logo-Bundle.zip)

**Comment by ericbn** [comment]
Great! That you for your contribution, @OneMohrTime!
