### ISSUE TITLE
add date to zimfw info [feature request]

### ISSUE THREAD

**Issue by cattyhouse** [zimfw/zimfw#421]
Current zimfw info shows: `zimfw version: 1.3.2 (previous commit is ccace0c)` , is it possible to append the release date after the commit id? for instance `zimfw version: 1.3.2 (previous commit is ccace0c on Aug 1, 2020)`

just a thought, thanks

**Comment by ericbn** [comment]
Hi @cattyhouse. Good idea, I'll include the compilation date in next releases.

Merry Christmas!
