### ISSUE TITLE
Custom completions in Zim

### ISSUE THREAD

**Issue by zaiste** [zimfw/zimfw#428]
What would be the idiomatic way to add custom completions in Zim?

For example, I want to enable `deno` completions. These are the steps for the vanilla Zsh installation

```
mkdir ~/.zsh # create a folder to save your completions. it can be anywhere
deno completions zsh > ~/.zsh/_deno
```

and in `.zshrc`

```
fpath=(~/.zsh $fpath)
autoload -Uz compinit
compinit -u
```

Is this the right way in Zim?

**Comment by ericbn** [comment]
Hi @zaiste. Zim already does `autoload -Uz compinit && compinit -C -d ${zdumpfile}` in the `completion` module. So all you need to do is add

    fpath=(~/.zsh $fpath)

to your .zshrc file anywhere before the
```
# ------------------
# Initialize modules
# ------------------
```
section.

**Comment by zaiste** [comment]
@ericbn Thanks for a quick reply!
