### ISSUE TITLE
zsh: command not found: zmodule

### ISSUE THREAD

**Issue by fengzhao** [zimfw/zimfw#430]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zimfw info` and paste the output below:

```
zimfw version: 1.4.3 (built at 2021-03-19 23:42:38 UTC, previous commit is 163d36b)
ZIM_HOME:      /root/.zim
Zsh version:   5.8
System info:   Linux VM-4-10-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- gist of .zimrc:
- gist of .zshrc:

Description
-----------

I install zimfw on my  ubuntu follow the readme.md file ， but  when i want to install some module on it , it reports 
```
zsh: command not found: zmodule
```

Steps to reproduce
------------------

Images or other information
---------------------------

**Comment by lnicola** [comment]
`zmodule` isn't a command you should type in a shell, you need to put it in your `~/..zimrc`.
