### ISSUE TITLE
it is getting slower and slower repeating "source .zshrc"

### ISSUE THREAD

**Issue by cattyhouse** [zimfw/zimfw#431]
a fresh installation of zimfw.

test code

```sh
for i in {1..25} ; do echo "the ${i}th source of .zshrc" ; source ~/.zshrc ; done
```

wonder if that can be improved?

**Comment by lnicola** [comment]
Does this actually matter? Are there any cases when `
.zshrc` gets sourced multiple times in the same shell?

**Comment by cattyhouse** [comment]
> Does this actually matter? Are there any cases when ` .zshrc` gets sourced multiple times in the same shell?

Yes, there are use cases like that, some people run tmux on a server for a long time, i mean, months or years without exiting the shell. And during the time, .zshrc settings gets changed, needs sourced. My test shows that after the 15th source, it is getting pretty slow.

**Comment by ericbn** [comment]
Here's the time, in seconds, each module takes to be sourced the 1st and 25th times that `.zshrc` gets sourced:

module | 1st | 25th
-- | -- | --
environment | 0.0002 | 0.0003
git | 0.0137 | 0.0010
input | 0.0032 | 0.0013
termtitle | 0.0007 | 0.0004
utility | 0.0045 | 0.0011
duration-info | 0.0001 | 0.0002
asciiship | 0.0006 | 0.0007
zsh-users/zsh-completions | 0.0001 | 0.0002
completion | 0.0059 | 0.0112
zsh-users/zsh-autosuggestions | 0.0007 | 0.0019
zsh-users/zsh-syntax-highlighting | 0.0134 | **4.3373**
zsh-users/zsh-history-substring-search | 0.0003 | 0.0003

As you can see zsh-users/zsh-syntax-highlighting takes most of the time. Could do a nice line graph over time if I had time to do so.  :- )

@cattyhouse, I strongly suggest you disable zsh-users/zsh-syntax-highlighting in your specific case.

**Comment by cattyhouse** [comment]
@ericbn  thanks a lot for the test, i will disable it for now.
