### ISSUE TITLE
[QUESTION] Are there module like zprezto gnu-utility module

### ISSUE THREAD

**Issue by robsonpeixoto** [zimfw/zimfw#432]
The [gnu-utility](https://github.com/sorin-ionescu/prezto/tree/master/modules/gnu-utility) is a really useful for macOS user that would like to use gnu-tools.

Are there a module that do the same thing?

**Comment by ericbn** [comment]
Oie @robsonpeixoto!

Why not just add
```
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```
to your .zshrc if you installed coreutils with homebrew?

Check the Caveats of `brew info --formula coreutils`:
```
==> Caveats
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```

**Comment by robsonpeixoto** [comment]
To not broke scripts. From zprezto readme:
![image](https://user-images.githubusercontent.com/124390/124845056-43aff880-df6c-11eb-9056-bf4dca19b8e4.png)

**Comment by ericbn** [comment]
Oh, got it. Yeah, we could have a similar one. Not even sure why this module is using functions instead of just aliases...

**Comment by robsonpeixoto** [comment]
Because it will not override the user alias. For example:
```
ls () {
	'/usr/local/bin/gls' "$@"
}

alias ls='ls --color'
```

**Comment by ericbn** [comment]
Oh, okay.

@robsonpeixoto, you can source the module directly from prezto using:
```
zmodule sorin-ionescu/prezto -s 'modules/gnu-utility/init.zsh' -s 'modules/another-module-if-you-want/init.zsh'
```
or I'm more than happy to add you as a contributor in the zimfw organization, and also as an admin of a new zimfw/gnu-utility repository if you're willing to maintain a new module here! Let me know what do you think.

**Comment by robsonpeixoto** [comment]
@ericbn use `sorin-ionescu/prezto` is enough. Your tip help-me a lot. Thanks. I love this project ❤️
