### ISSUE TITLE
SSH tab completion not including known_hosts

### ISSUE THREAD

**Issue by AndreasNasman** [zimfw/zimfw#433]
```
zimfw version: 1.4.3 (built at 2021-03-19 23:42:38 UTC, previous commit is 163d36b)
ZIM_HOME:      /Users/andreasnasman/.config/zsh/.zim
Zsh version:   5.8
System info:   Darwin Andreass-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```

Description
-----------
At work, my MacBook has a username other than my SSH username. Since we have lots of servers and my SSH username is the same for all of them, I've modified my `~/.ssh/config` file accordingly (this all of the content in the file):

```shell
HOST *
    USER username
```

When running `ssh <TAB>` I receive no `-- remote host name --` list. If I remove/rename my `ssh/config` file, all of my known hosts are listed.

How can I list all known hosts while keeping the configurations in the `ssh/config` file above? Should I add or modify it in some way? I've read through #46 but couldn't figure out from that issue how to solve the problem I'm having.

**Comment by ericbn** [comment]
@AndreasNasman, not sure what's going on, but FYI this is configured in the [completion](https://github.com/zimfw/completion) module, here: https://github.com/zimfw/completion/blob/db079f405397a9dc9af93883e47d8adff817e3b1/init.zsh#L78-L81

**Comment by AndreasNasman** [comment]
If I comment out that bit of code, it works! Don't really understand why though...🤔

**Comment by ericbn** [comment]
This should be fixed by https://github.com/zimfw/completion/commit/d4557de71723a22e67ae790fbca2d9167c836e67

**Comment by AndreasNasman** [comment]
Nice, thanks! 👍
