### ISSUE TITLE
https://github.com/zimfw/history-substring-search has disappeared

### ISSUE THREAD

**Issue by timepigeon** [zimfw/zimfw#434]
My zim build process is failing over the history-substring-search module being unavailable. The repository https://github.com/zimfw/history-substring-search seems to has been taken offline. Will it return or is there are replacement?

**Comment by lnicola** [comment]
Maybe try reinstalling Zim from scratch. It's now using the upstream, https://github.com/zsh-users/zsh-history-substring-search.

**Comment by ericbn** [comment]
replace `zmodule zimfw/history-substring-search` by `zmodule zsh-users/zsh-history-substring-search`, and add the following to your .zshrc file: https://github.com/zimfw/install/blob/4d11eb529f7fe987b48535616af1ba89820f6f61/src/templates/zshrc#L110-L128
