### ISSUE TITLE
Pure prompt doesn't display git info (async)

### ISSUE THREAD

**Issue by timkelty** [zimfw/zimfw#436]
In a terminal, run `zimfw info` and paste the output below:

```
❯ zimfw info
zimfw version: 1.5.0 (built at 2021-08-10 14:52:54 UTC, previous commit is 35cd6f5)
ZIM_HOME:      /Users/timkelty/.zim
Zsh version:   5.8
System info:   Darwin Timothys-MacBook-Air.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64```
```

- gist of .zimrc, .zshrc: https://gist.github.com/timkelty/04c2dc93db712b985a929c48022cb425

Description
-----------
Installing the https://github.com/sindresorhus/pure prompt as instructed, does not show git branch/status.

```
zmodule sindresorhus/pure --source async.zsh --source pure.zsh
```

If I install via `brew`, with this in .zshrc, it works as expected:

```
autoload -U promptinit; promptinit
prompt pure
```

Images or other information
---------------------------
Via zimrc/zmodule instructions:
<img width="237" alt="CleanShot 2021-08-24 at 22 04 46@2x" src="https://user-images.githubusercontent.com/18329/130714276-078e3875-bcd8-47ff-a3b6-10f38eaf51f8.png">

Via brew:
<img width="274" alt="CleanShot 2021-08-24 at 22 03 50@2x" src="https://user-images.githubusercontent.com/18329/130714206-9e4a3b9a-b7a5-4ae6-ab91-575974b40bb6.png">

**Comment by ericbn** [comment]
Add `zmodule sindresorhus/pure --source async.zsh --source pure.zsh` to your `.zimrc` file.

Don't add anything related to this prompt in your `.zshrc` file, as nothing is needed. Don't do `autoload -U promptinit; promptinit; prompt pure` as this is not needed.

Run `zimfw install` and restart your shell and you should be good.

**Comment by timkelty** [comment]
@ericbn yep, that's what I'm doing (sorry my initial message got mangled…updated that and my gist).

No git info:
![CleanShot 2021-08-25 at 10 25 26](https://user-images.githubusercontent.com/18329/130808987-cd226449-4781-4f53-ba63-04fbb32e46f9.png)

**Comment by ericbn** [comment]
I cannot reproduce your issue with a clean Zim installation, so it's likely related to your individual setup:

1. `cd $(mktemp -d)`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | ZDOTDIR=${PWD} HOME=${PWD} zsh`
5. `ZDOTDIR=${PWD} HOME=${PWD} zsh`
6. Edit .zimrc and replace `zmodule asciiship` by `zmodule sindresorhus/pure --source async.zsh --source pure.zsh`
7. `zimfw install`
8. `exec zsh`
9. `cd .zim/modules/pure`
10. main branch shows as expected
