### ISSUE TITLE
Error on installing due to new github authentication requirements

### ISSUE THREAD

**Issue by danitome24** [zimfw/zimfw#438]
**Describe the bug**
When I run `zsh ./modules/zimfw/zimfw.zsh install` this asks for username and password github account. But github has removed password authentication from 13th August.

**Steps to reproduce**
1. Clone the repository
2. Execute `zsh ./modules/zimfw/zimfw.zsh install`
3. You'll see the following message after typing your github account details:

```
{▸} ~/.dotfiles zsh ./modules/zimfw/zimfw.zsh install
Installing history ...Username for 'https://github.com': XXXXXXXX
Password for 'https://XXXXXXXX@github.com': 
 history: Error during git clone
  git: 'credential-osxkeychain'no es un comando de git. Mira 'git --help'.
  git: 'credential-osxkeychain'no es un comando de git. Mira 'git --help'.
  remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
  remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
  fatal: Autenticación falló para 'https://github.com/zimfw/history.git/'
Done with install. Restart your terminal for any changes to take effect.
```

**Expected behavior**
Correct installation process

**Comment by lnicola** [comment]
Strange, GitHub shouldn't request authentication for `git clone`.

**Comment by ericbn** [comment]
Hola @danitome24.

You didn't follow the clean install steps from our issue template. You don't need to clone the zimfw repo, although cloning it does not cause the problem you describe. Check the complete manual installation instructions in our [install docs](https://zimfw.sh/docs/install/).

You can even use Zim without git, in case you don't have git installed or if your git configuration is broken. That's in our [settings docs](https://zimfw.sh/docs/settings/).
