### ISSUE TITLE
prompt now requires the module prompt-pwd

### ISSUE THREAD

**Issue by Konfekt** [zimfw/zimfw#439]
It would help the user after the latest update of his modules to have a short note that prompt now requires the module prompt-pwd, instead of the error message that the prompt-pwd command is missing.

**Comment by ericbn** [comment]
Hi @Konfekt. Check discussion in https://github.com/zimfw/magicmace/issues/3.

**TL;DR** I'm announcing these changes in the  [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) discussion channel, and changes are also being shown in the git log in `zimfw update`:

```
) magicmace: Updating 9fc8e39..7386964
  * 7386964 Require prompt-pwd module (18 hours ago)
```

**Comment by ericbn** [comment]
Also, I've included:

- [ ] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426) and I'm not being affected by announced changes.

in the template of the bug request here.

**Comment by Konfekt** [comment]
Okay, thank you and pardon the noise, this is then more or less a duplicate.
