### ISSUE TITLE
Prompt displays [!] in a clean git repository

### ISSUE THREAD

**Issue by romkatv** [zimfw/zimfw#441]
- [ ] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [ ] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [ ] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [ ] I've pasted the output of `zimfw info` below.

---

When using zim with the default rc files prompt displays `[!]` in a clean git repository.

To reproduce, run this command (requires `docker`):

```zsh
docker run -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 -w /root -it --rm alpine sh -uexc '
  apk add git zsh curl
  curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh >/dev/null
  touch foo
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
  git config --global init.defaultBranch master
  git init
  git add foo
  git commit --allow-empty --allow-empty-message -m ""
  sleep 1
  touch foo
  exec zsh -l'
```

Expected prompt:

```text
(2) root in ~ on master
#
```

Actual prompt:

```text
(2) root in ~ on master [!]
#
```

**Comment by ericbn** [comment]
Thanks for reporting this!
