### ISSUE TITLE
powerlevel10k not working on startup

### ISSUE THREAD

**Issue by burg1ar** [zimfw/zimfw#445]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
OS: ubuntu 18.04
powerlevel10k not working on startup, while this problem won't happen using oh my zsh

**Steps to reproduce**  
open a new terminal -> powerlevel10k not working

**Screenshots**  
![image](https://user-images.githubusercontent.com/3461895/145765219-89bae0e2-db47-4579-b6ca-a7ee19fa5c2f.png)
powerlevel10k works fine after hitting "enter"

**zimfw info**  
```
zimfw version: 1.6.2 (built at 2021-11-21 19:40:05 UTC, previous commit is a5fb148)
ZIM_HOME:      /home/test/.zim
Zsh version:   5.4.2
System info:   Linux AiUbuntu 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ericbn** [comment]
Can you please provide steps on how to reproduce it in a clean Zim installation?

I've tried the following and it worked for me:
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. Edit the .zimrc file, commenting out these lines:
    ```
    #zmodule duration-info
    #zmodule git-info
    #zmodule asciiship
    ```
    and adding this line:
    ```
    zmodule romkatv/powerlevel10k --use degit
    ```
6. `zimfw install`
7. `exec zsh`
8. Follow the P10K configuration wizard, enabling instant prompt, and choosing to update the .zshrc file at the end.
9. `exec zsh`

Then the prompt appears as expected.

**Comment by burg1ar** [comment]
thank you for your reply.
I created a virtual machine installed ubuntu 18.04 to produce the bug, but everything went well, powerlevel10k works fine.
then I copied the `.zshrc` to my original system, and no bug occurs.
I found out the following lines caused the problem:
```bash
# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
```
what are these codes for ?

**Comment by ericbn** [comment]
These lines are setting up the "adam1" prompt that is bundled with Zsh. You don't need this since you're not using this prompt.

See these previously reported issues in the powerlevel10k repository: [here](https://github.com/romkatv/powerlevel10k/issues/1152#issuecomment-741868925) and [here](https://github.com/romkatv/powerlevel10k/issues/877#issuecomment-657013521)
