### ISSUE TITLE
Permission error when executing zimfw install

### ISSUE THREAD

**Issue by clarg18** [zimfw/zimfw#451]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [ x I've pasted the output of `zimfw info` below.

```
zimfw version: 1.8.0 (built at 2022-01-25 22:16:46 UTC, previous commit is 72fe20c)
ZIM_HOME:      /usr/lib/zim
Zsh version:   5.8
System info:   Linux chakotay 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux
```
**Describe the bug**  
`zimfw install` requires root privilege but `sudo zimfw install` states no command found.

**Steps to reproduce**  
The fist 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. Other steps to reproduce the behavior
```zsh
~
% zimfw install
x pacman: Error during git clone
  fatal: could not create work tree dir '/usr/lib/zim/modules/pacman': Permission denied
Done with install. Restart your terminal for changes to take effect.
x /home/clarg/.zimrc:2:pacman: Not installed. Run zimfw install to install.
Failed to source /home/clarg/.zimrc
```
~
1 % sudo zimfw install
sudo: zimfw: command not found

**Comment by ericbn** [comment]
Hi. Did you really install Zim using our installer script (via curl or wget), or using an archlinux package manager?

**Comment by clarg18** [comment]
Sorry, I installed it via arch aur package Zsh-zim-git

**Comment by ericbn** [comment]
I believe the arch package is being maintained by @carbolymer.

I'm only officially maintaining the [automatic or manual installations described in our README.md](https://github.com/zimfw/zimfw/blob/master/README.md#installation), which you can also find in our website, at https://zimfw.sh/docs/install/.

**Comment by carbolymer** [comment]
`zimfw` is a `zsh` function provided by zim. `sudo zimfw install` tries to run `zimfw` binary which does not exist. The correct form is to:
1.  `sudo zsh`
2.  `zimfw install`

**Comment by clarg18** [comment]
> `zimfw` is a `zsh` function provided by zim. `sudo zimfw install` tries to run `zimfw` binary which does not exist. The correct way for AUR package is to:
> 
>     1. `sudo zsh`
> 
>     2. `zimfw install`

Many thanks, should I have known this? If not perhaps a small note on the docs might be useful.

**Comment by carbolymer** [comment]
@clarg18 there's a pinned comment in AUR: https://aur.archlinux.org/packages/zsh-zim-git/#pinned-785673
