### ISSUE TITLE
hook-build command

### ISSUE THREAD

**Issue by pdufour** [zimfw/zimfw#456]
**Is your feature request related to a problem? Please describe.**  
In order to install fzf I have to run another command rather than have it in my zsh config (i.e. I have to run the git checkout commands manually)

**Describe the solution you'd like**  
In zplug you can add something like the following which will download and build fzf when you run zplug install

````
zplug 'junegunn/fzf', \
      as:command, \
      use:'bin/{fzf,fzf-tmux}', \
      if:"[[ $OSTYPE == linux* || $OSTYPE == darwin* ]]", \
      hook-build:'./install --key-bindings --completion --no-update-rc'
````

**Additional context**  
Having a functionality like hook-build would be nice to enable us to have install commands for our modules

**Comment by ericbn** [comment]
Does having it as the following zmodule option: `--on-pull <command>`, and triggering it after the install and update actions makes sense?

**Comment by pdufour** [comment]
Yes! That sounds slick @ericbn

**Comment by ericbn** [comment]
[Version 1.9.0](https://github.com/zimfw/zimfw/releases/tag/v1.9.0) released with this addition.

**Comment by pdufour** [comment]
Oh wow thank you @ericbn !! That's amazing
