### ISSUE TITLE
Completion highlight colour same as normal colour

### ISSUE THREAD

**Issue by jtroeth1** [zimfw/zimfw#457]
Hi There,

After recently upgrading to 1.9.0, my completion colour is white, the same as my normal font colour:
![image](https://user-images.githubusercontent.com/37925036/168422863-b81bca80-5752-48ac-a3d4-7c5d7c07fa06.png)

How can I change it back to grey?

Thanks

**Comment by vitkin** [comment]
On my end, I've fixed the highlighting by updating the modules folders `~/.zim/modules/zsh-*` which can be done by either running `git pull` in each folder or by just running `zimfw update` to update all the modules.
I've also edited my `~/.zshrc` and set `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'` (i.e., I've just uncommented the line).

### References
- [How to change zsh-autosuggestions color](https://stackoverflow.com/questions/47310537/how-to-change-zsh-autosuggestions-color)
- [conflict with syntax-highlighting plug #673](https://github.com/zsh-users/zsh-autosuggestions/issues/673)

**Comment by jtroeth1** [comment]
This worked, thanks @vitkin
