### ISSUE TITLE
Duplicating commands  after pressing tab in eriner theme

### ISSUE THREAD

**Issue by vizakenjack** [zimfw/zimfw#471]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [ x I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

First of all, thank you for your project. I moved from zprezto about 2 years ago and never had any issues with zimfw. However, I got one today on my new Debian 11 server 

**Describe the bug**  
There is something strange with eriner theme. When I type something like "cd" and press tab, it moves cursor to the right, making a duplicate of "cd" command, like "cd  cd", and I can't delete the first one. 

**Steps to reproduce**  
1. Install latest version of zimfw
2. Add "zmodule eriner" to a Prompt section of .zimrc
3. type "cd" and press tab 2-3 times

**Current behavior**  
"cd" or other commands are being duplicated after pressing "tab"

**Expected behavior**  
It should not duplicated

**Video**  

https://user-images.githubusercontent.com/91447/190837022-b18966b5-a020-4250-981a-474643e3f710.mov

**zimfw info**  
```
zimfw version: 1.9.1 (built at 2022-05-24 21:25:10 UTC, previous commit is 5bcfb8c)
ZIM_HOME:      /home/user/.zim
Zsh version:   5.9
System info:   Linux hetzner 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
```

**Additional context**  

Also tried:
- Commented out "zmodule asciiship"
- Turned off all other modules
- Tried to use zmodule zimfw/eriner
- Removed .zim, .zimrc and reinstalled
- Added new linux user

**Comment by ericbn** [comment]
Hi. Try commenting lines [95] (https://github.com/zimfw/input/blob/bcff8c8504ea7efd0fc8c696dfdc8762e4bfbbb6/init.zsh#L95) and [104](https://github.com/zimfw/input/blob/bcff8c8504ea7efd0fc8c696dfdc8762e4bfbbb6/init.zsh#L104) from the init.zsh file in the input module and let us know if that fixes it.

**Comment by vizakenjack** [comment]
> Hi. Try commenting lines [95](https://github.com/zimfw/input/blob/bcff8c8504ea7efd0fc8c696dfdc8762e4bfbbb6/init.zsh#L95) and [104](https://github.com/zimfw/input/blob/bcff8c8504ea7efd0fc8c696dfdc8762e4bfbbb6/init.zsh#L104) from the init.zsh file in the input module and let us know if that fixes it.

Thanks, just did it and restarted shell, but the problem is still here

**Comment by ericbn** [comment]
What do you have bind to the tab key? Check running `bindkey "^I"` in your command prompt.

**Comment by vizakenjack** [comment]
I tried to update zim and plugins to the latest version, looks like this issue is resolved now. Thanks!
