### ISSUE TITLE
use LESS to replace LESS_TERMCAP_xy

### ISSUE THREAD

**Issue by cattyhouse** [zimfw/zimfw#476]
**Is your feature request related to a problem? Please describe.**  
current settings are:

```sh
export LESS_TERMCAP_mb=$'\E[1;31m'   # Begins blinking.
export LESS_TERMCAP_md=$'\E[1;31m'   # Begins bold.
export LESS_TERMCAP_me=$'\E[0m'      # Ends mode.

export LESS_TERMCAP_se=$'\E[27m'     # Ends standout-mode.
export LESS_TERMCAP_so=$'\E[7m'      # Begins standout-mode.

export LESS_TERMCAP_ue=$'\E[0m'      # Ends underline.
export LESS_TERMCAP_us=$'\E[1;32m'   # Begins underline.

```

but these settings may cause **some problems** :
- use iOS Termius app, when `use brighter color for bold texts` enabled, `man something` , the search highlights completely covers the red colored text, make it unseen. 
- $'string' may get expanded in terminal, in some cases.

**Describe the solution you'd like**
consider this one line solution?
```sh
export LESS+=' --use-color -Dd+r$ -Dk+r$ -Du+g$ -DSkw$ -DPkw$' # man less, search '-Dxcolor'
```
or we can use 8bit color to cover both black and white backgrounded terminal theme for search hightlight and prompt:
```sh
export LESS+=' --use-color -Dd+r$ -Dk+r$ -Du+g$ -DS15.8$ -DP15.8$' # 15 means white, 8 means dark grey, . is a separator
```

**Comment by ericbn** [comment]
Hi @cattyhouse. Can you send a screenshot of how it looks like in your terminal?

In which circumstances do you see the "$'string' get expanded in terminal"? The Zsh @'string' syntax will properly quote to \E to an escape character, and should not be an issue.

The issue I see when using the -D options, although a much cleaner solution, is that it does not allow setting "red bold without blinking" to blinking or "yellow bold without underline" to underline (specifically the "bold" part in these cases), unless I'm missing something.

I just noticed these two lines are redundant:
```
export LESS_TERMCAP_se=$'\E[27m'     # Ends standout-mode.
export LESS_TERMCAP_so=$'\E[7m'      # Begins standout-mode.
```
and we can actually remove them.

**Comment by cattyhouse** [comment]
Case 1 : iOS Termius app, ssh into a zimfw installed local server

![image](https://user-images.githubusercontent.com/3365320/193698135-1ebf06aa-d6fd-4157-bfcb-0ca9c2f959f8.jpeg)

![image](https://user-images.githubusercontent.com/3365320/193698158-a9524900-5a21-448f-ac96-c5679898a7e9.jpeg)

Case 2 : the expansion happened in Bash with the exact 7 lines of LESS_TERMCAP in .bashrc , and then source .bashrc and then run plain 'export', terminal becomes all green. ( sorry this is not zsh related. )

**Comment by cattyhouse** [comment]
my LESS solution:
![image](https://user-images.githubusercontent.com/3365320/193699618-5fee1243-f40b-4322-a0b3-d9409273a48d.jpeg)

**Comment by cattyhouse** [comment]
_The issue I see when using the -D options, although a much cleaner solution, is that it does not allow setting "red bold without blinking" to blinking or "yellow bold without underline" to underline (specifically the "bold" part in these cases), unless I'm missing something._

  A lowercase letter may be followed by a + to  in‐
              dicate  that  the  normal  format  change and the
              specified color should both be used.   For  exam‐
              ple, **-Dug displays underlined text as green with‐
              out underlining**; the green color has replaced the
              usual  underline  formatting.  But -Du+g displays
              underlined text as both green and  in  underlined
              format.

 corresponding  upper-case  letter  denotes a
              brighter shade of the color.  **For example,  -DNGk
              displays  line  numbers as bright green text** on a
              black background,

**Comment by ericbn** [comment]
This might be a problem with Termius itself.

Can you try running this command in your prompt?
```
print -P '%F{red}%SH%sello %SW%sorld%f'
```
This is what I get in iTerm 2:
![Screen Shot 2022-10-03 at 18 19 03](https://user-images.githubusercontent.com/4120606/193702715-d65b5ef0-9ce8-407e-ad35-04b15591c421.png)

**Comment by ericbn** [comment]
> For example, **-Dug displays underlined text as green with‐ out underlining**; the green color has replaced the usual underline formatting.

Yep, I've read that documentation. I didn't find a way to do "the green **bold** color has replaced the usual underline formatting."

**Comment by cattyhouse** [comment]
![image](https://user-images.githubusercontent.com/3365320/193703209-3a3de2d5-eea3-4b8c-9cf9-c703f5838e29.jpeg)

**Comment by ericbn** [comment]
Or
```
print -P '%F{red}%B%SH%sello %SW%sorld%b%f'
```
In iTerm2 it looks like this:
![Screen Shot 2022-10-03 at 18 25 15](https://user-images.githubusercontent.com/4120606/193703356-0ccc163c-fade-4564-ab47-b611297467d8.png)

**Comment by cattyhouse** [comment]
Yep, I've read that documentation. I didn't find a way to do "the green bold color has replaced the usual underline formatting."

-DuG i think is close to Bold Green foreground color and also removes underline. G is brighter green to g

**Comment by cattyhouse** [comment]
![image](https://user-images.githubusercontent.com/3365320/193703872-83840fb9-a0bf-46c4-9d05-33707cf43838.jpeg)

can't see the H and W . lol.

**Comment by ericbn** [comment]
> -DuG i think is close to Bold Green foreground color and also removes underline. G is brighter green to g

Using bright colors instead of bold has undesired outcomes in some cases. E.g. the solarized color themes don't have bright colors equivalent to the non-bright ones -- the bright green color is actually a grey reserved for other purposes.

From the experience with different scenarios, I've found that the safe color options are:
* safe: all non-bold color except for non-bold blue
* safe: all bold colors

The bright colors and the non-bold blue can be poorly rendered in some cases.

**Comment by ericbn** [comment]
> can't see the H and W . lol.

Cool. Now you can report this upstream to the Termius project!  :- )

**Comment by cattyhouse** [comment]
i have to turn off ' use bright colors for bold text' to make the 2nd print command output the same as yours.

**Comment by ericbn** [comment]
This option should not break the output in either the on or off state. I've left the "Brighten bold colors" option in iTerm2 on while making the screenshots above. Looks like a bug in Termius, that's why I'm suggesting you report it back the them.

**Comment by cattyhouse** [comment]
> 

will find a way to do that, thanks! i think then there is no other issues with LESS_TERMCAP for now (except for BASH expanding $'\E' when running plain `export` which is not ZSH related)
