### ISSUE TITLE
Customizable `.zimrc` filename

### ISSUE THREAD

**Issue by blatobi** [zimfw/zimfw#479]
My whole zsh configuration is located in "$XDG_CONFIG_HOME/zsh" and therefore not littering my home folder. Usually I have all files configured without the prefixed dot to hide them. With `.zimrc` this seems not to be possible as `zimfw.sh` seems to rely on the static filename.
I would like to configure a environment-variable with `ZIMRC_LOCATION="$ZSH_CONF/zsh/zimrc"` or `ZIM[RC]="$ZSH_CONF/zsh/zimrc"` that allows me to configure individual location of the zimrc file.

**Comment by ericbn** [comment]
Hi @blatobi. Sure, I can add the option to configure the whole file path.

@Eriner, any thoughts on the environment variable name?

I'm thinking `ZIM_CONFIG_PATH`.

**Comment by ericbn** [comment]
Released version 1.11.0 with this change.
