### ISSUE TITLE
zsh-syntax-highlighting could not work on termux

### ISSUE THREAD

**Issue by TTsdzb** [zimfw/zimfw#482]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
In Termux, zsh-syntax-highlighting could not load highlighters, thus does not work.

**Steps to reproduce**  
The first 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. That's it. You'll see an error during loading as shown below.
6. Try to type a letter, and zsh-syntax-highlighting will tell you highlighter not loaded as shown below.

**Current behavior**  
zsh-syntax-highlighting does not work.

**Expected behavior**  
The module should work out-of-the box. I was already using it on a Debian and it works fine.

**Screenshots**  
![Screenshot_2022-10-24-15-52-42-274_com termux](https://user-images.githubusercontent.com/62687036/197475373-b5aa4883-17fd-449b-b109-60a3284d4e70.jpg)

**zimfw info**  
```
zimfw version:        1.10.0 (built at 2022-09-27 22:44:10 UTC, previous commit is 05b8e0c)
OSTYPE:               linux-android
TERM:                 xterm-256color
TERM_PROGRAM:
TERM_PROGRAM_VERSION:
ZIM_HOME:             /data/data/com.termux/files/usr/tmp/tmp.H6LTDMqiFK/.zim
ZSH_VERSION:          5.9
```

**Additional context**  
Error occurred during loading:
```
zsh-syntax-highlighting: ')' highlighter should define both required functions '_zsh_highlight_highlighter_)_paint' and '_zsh_highlight_highlighter_)_predicate' in '/data/data/com.termux/files/usr/tmp/tmp.H6LTDMqiFK/.zim/modules/zsh-syntax-highlighting/highlighters/*/(/))-highlighter.zsh'.
```

```
zsh-syntax-highlighting: warning: disabling the 'main' highlighter as it has not been loaded
```

**Comment by ericbn** [comment]
Hi @TTsdzb, an issue with zsh-syntax-highlighting and termux had been reported before [here](https://github.com/termux/termux-packages/issues/1894#issuecomment-451611454).

The workaround at that time was commenting out the `setopt NO_CASE_GLOB` in the ~/.zim/modules/completion/init.zsh file.

**Comment by ericbn** [comment]
This was also reported before in #319.

**Comment by TTsdzb** [comment]
> 

It worked... Sorry for wasting your time

**Comment by TTsdzb** [comment]
@ericbn Maybe mention it somewhere noticeable in the README? I might do that later if i got time.

**Comment by RpxdYTX** [comment]
Just tested it. Completions work in proot even if it is unset.
However,  they won't work for dirs at external storage.
