### ISSUE TITLE
FZF_ALT_C_COMMAND output is faulty

### ISSUE THREAD

**Issue by tjex** [zimfw/zimfw#487]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [ ] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
FZF_ALT_C_COMMAND window output is faulty when using `zmodule fzf`, but with oh-my-zsh via `plugins=(fzf)` it works.

**Steps to reproduce**  
I did not use the temp setup as zim fzf module requires fzf to be installed separately in the first place.

Therefore:
1. install fzf with `zmodule fzf`
2. invoke FZF_ALT_C_COMMAND : this results in faulty output for me (see below)
3. uninstall fzf from zim
4. add to .zshrc `plugins=(fzf)`
5. invoke FZF_ALT_C_COMMAND : results are as expected

**Current behavior**  
When using zim's fzf module, the FZF_ALT_C_COMMAND results in faulty text output.
fzf-file-widget and fzf-history-widget both behave correctly (ie non-faulty text output)

**Expected behavior**  
Non faulty FZF_ALT_C_COMMAND output. 

**Screenshots**  
when using zim fzf module   
![when using zim fzf module](https://user-images.githubusercontent.com/83029642/200366116-19a68951-2df1-409b-8260-a67e77568541.png)

when using oh-my-zsh fzf module
![when using oh-my-zsh fzf module](https://user-images.githubusercontent.com/83029642/200366414-6aa05600-845b-46f6-b95a-e8e48d11d0ca.png)

**zimfw info**  
```
zimfw version:        1.10.0 (built at 2022-09-27 22:44:10 UTC, previous commit is 05b8e0c)
OSTYPE:               darwin21.0
TERM:                 xterm-kitty
TERM_PROGRAM:         
TERM_PROGRAM_VERSION: 
ZIM_HOME:             /Users/tillman/.config/zim
ZSH_VERSION:          5.8.1
```

**Additional context**

**Comment by ericbn** [comment]
Hi @tjex. Do you have `fd` installed? If so, our module should have added `--ansi` to the `FZF_DEFAULT_OPTS`. Or are you overriding `FZF_DEFAULT_OPTS` yourself?

**Comment by tjex** [comment]
I do have `fd` installed and yes, I'm using ohmyzsh. I didn't pickup that it wasn't recommended, sorry. 
I saw others were using zim as a plugin manager and followed suit. Can I ask if you have an appropriate alternative?

I have this in my `zsh-vi-mode.zsh`
```
function myInit () {
    export FZF_BASE=/opt/homebrew/Cellar/fzf/0.33.0 #fzf plugin
    [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    # DISABLE_FZF_AUTO_COMPLETION="true"
    export FZF_DEFAULT_COMMAND='fd --type file' 
    export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --exact'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    bindkey 'ç' fzf-cd-widget
    bindkey '\C-f' fzf-file-widget
    bindkey '\C-h' fzf-history-widget


}
function zvm_config() {
    ZVM_VI_ESCAPE_BINDKEY=kj
    ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE
    ZVM_READKEY_ENGINE=$ZVM_READKEY_ENGINE_ZLE
    zvm_after_init_commands+=(myInit)
}
```
Thanks for your time

**Comment by ericbn** [comment]
You'll have to either source zsh-vi-mode.zsh before Zim's fzf module, or change the script there to:
```diff
-    export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --exact'
+    export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border --exact ${FZF_DEFAULT_OPTS}"
```
so previously defined opts are not lost.

It's also overriding FZF_DEFAULT_COMMAND and FZF_CTRL_T_COMMAND, so it's practically overriding everything that Zim's fzf module sets.

**Comment by tjex** [comment]
Changing the line to suggested returns this error when triggering fzf key commands
```unknown option: ${FZF_DEFAULT_OPTS}```

Having `zmodule jeffreytse/zsh-vi-mode` before `zmodule fzf` in my `.zimrc` also doesn't change any behaviour. 

What you say is true re how I'm implementing fzf. But I'd like to just have it in my mind that zim manages my zsh plugins as a rule, and not part zsh part oh-my-zsh...
Zim also handles bat setup/integration for me 🤓

**Comment by tjex** [comment]
Today I rebuilt my zsh from scratch (as I was having other problems) and am now only using zim, and not oh-my-zsh at all. The ALT_C command is still returning jibberish in the file path outputs... 

Both of your suggestions above still result in the same behaviour as my immediately previous comment.

**Comment by ericbn** [comment]
@tjex, can you please do
```
print -- ${FZF_DEFAULT_OPTS}
```
in your command line and post the result here. It should have `--ansi` in there, which is what tells fzf to parse that "faulty text output". The `--ansi` opt is added by Zim's fzf module. If the `--ansi` is not there, then some other Zsh script is overriding it.

**Comment by tjex** [comment]
I get `--height 40% --layout=reverse --border --exact`, which is what I have set in my `zsh-vi-mode.zsh`. 
As said, I'm now exclusively using a zim install, which is this:
```
# Start configuration added by Zim install {{{
zmodule environment
zmodule git
zmodule input
zmodule utility

#
# Prompt
#

zmodule duration-info
zmodule git-info
zmodule s1ck94
zmodule prompt-pwd
zmodule Aloxaf/fzf-tab
zmodule jeffreytse/zsh-vi-mode
zmodule fzf
#
# Completion
#

zmodule zsh-users/zsh-completions --fpath src
zmodule completion

#
# Modules that must be initialized last
#

# zsh-users/zsh-syntax-highlighting must be sourced after completion
zmodule zsh-users/zsh-syntax-highlighting
# }}}
```

I added the `--ansi` flag and it is indeed fixed!
If you remove the --ansi, then the problem will reoccur for all users then or? 🧐

**Comment by ericbn** [comment]
Started a discussion in fzf: https://github.com/junegunn/fzf/discussions/3043
