### ISSUE TITLE
fzf module fg color not changing

### ISSUE THREAD

**Issue by tjex** [zimfw/zimfw#488]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [ ] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
The foreground color in the fzf module is not changing when set in `$FZF_DEFAULT_OPTS`

`man fzf`:    
```
Display
       --color=[BASE_SCHEME][,COLOR_NAME[:ANSI_COLOR][:ANSI_ATTRIBUTES]]...
              Color configuration. The name of the base color scheme is followed by custom color mappings.

              BASE SCHEME:
                  (default: dark on 256-color terminal, otherwise 16)

                  dark    Color scheme for dark 256-color terminal
                  light   Color scheme for light 256-color terminal
                  16      Color scheme for 16-color terminal
                  bw      No colors (equivalent to --no-color)

              COLOR NAMES:
                  fg         Text
                  bg         Background

              EXAMPLES:

                   # Seoul256 theme with 24-bit colors
                   fzf --color='bg:#4B4B4B,bg+:#3F3F3F,info:#BDBB72,border:#6B6B6B,spinner:#98BC99' \
                       --color='hl:#719872,fg:#D9D9D9,header:#719872,fg+:#D9D9D9' \
                       --color='pointer:#E12672,marker:#E17899,prompt:#98BEDE,hl+:#98BC99'
```

**Steps to reproduce**  
This is related to the fzf module, which needs fzf to be installed separately. 
I did not know how to achieve this when running zim in a temp folder.

**Current behavior**  
setting the `fg` color variable of fzf does not change the text color of the fzf `alt-c` search results.
however, setting other color variables does work.

**Expected behavior**  
setting `  export FZF_DEFAULT_OPTS="--ansi --color=fg:#ff9e64 ${FZF_DEFAULT_OPTS}" `  in `fzf/init.zsh` should set the text to color `#ff9e64`. 

**Screenshots**  
Without extra color settings (ie default):   
![Screen Shot 2022-11-12 at 09 54 03](https://user-images.githubusercontent.com/83029642/201466813-fee4a9bb-9b50-4b69-98df-cd40fd11364d.png)

foreground setting:   
`  export FZF_DEFAULT_OPTS="--ansi --color=fg:#ff9e64 ${FZF_DEFAULT_OPTS}" `   
![Screen Shot 2022-11-12 at 09 54 03](https://user-images.githubusercontent.com/83029642/201466813-fee4a9bb-9b50-4b69-98df-cd40fd11364d.png)

background setting:   
`  export FZF_DEFAULT_OPTS="--ansi --color=bg:#ff9e64 ${FZF_DEFAULT_OPTS}" `   
![Screen Shot 2022-11-12 at 09 53 18](https://user-images.githubusercontent.com/83029642/201466837-2e453986-fe85-49f3-bef9-f3f834f2e2fc.png)

**zimfw info**  
```
zimfw version:        1.10.0 (built at 2022-09-27 22:44:10 UTC, previous commit is 05b8e0c)
OSTYPE:               darwin21.0
TERM:                 xterm-kitty
TERM_PROGRAM:         
TERM_PROGRAM_VERSION: 
ZIM_HOME:             /Users/tillman/.config/zsh/zim
ZSH_VERSION:          5.8.1
```

**Additional context**  
In my [previous issue](https://github.com/zimfw/zimfw/issues/487) I was setting fzf opts in the zsh-vi-mode settings. 
To be clear, I made sure to comment out the `export FZF_DEFAULT_OPTS` call in `zsh-vi-mode.zsh` when testing this issue.

**Comment by yuriaps** [comment]
Its working perfetcly on WSL

![image](https://github.com/zimfw/zimfw/assets/33907201/2e5bd363-6843-4148-8566-dc75f3c492d3)

**Comment by yuriaps** [comment]
For installing fzf on the temporary file follow this:

1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh` then type `0`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. `git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf`
6. `./.fzf/install`, `yes` to all
7. `source ./.zshrc` (don't clone the terminal on any step, always open)
8. add `zmodule zfz` to `.zimrc`
9. `zimfw install`
10. `source ./.zshrc`
11. `mkdir test_folder` `mkdir test_folder2` ...
12. `export FZF_DEFAULT_OPTS="--ansi --color=fg:#ff9e64 ${FZF_DEFAULT_OPTS}"`

zimfw info:
zimfw version:        1.12.0 (built at 2023-07-17 23:54:58 UTC, previous commit is 49386ca)                             LANG:                 C.UTF-8                                                                                           OSTYPE:               linux-gnu                                                                                         TERM:                 xterm-256color                                                                                    TERM_PROGRAM:                                                                                                           TERM_PROGRAM_VERSION:                                                                                                   ZIM_HOME:             /tmp/tmp.TeYkm17wz7/.zim                                                                          ZSH_VERSION:          5.8.1

**Comment by tjex** [comment]
Thanks for adding this imput. I've since wiped my machine and starting my entire config on mac from fresh - after a brief foray into linux. So I've lost track of this 'bug' on my end, which is most likely just bad config practices on my end. 
I'll close for now, if I see the same thing happen with my new config, I'll reopen.
