### ISSUE TITLE
on **Linux** weird tab completion behaviour 

### ISSUE THREAD

**Issue by cattyhouse** [zimfw/zimfw#489]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  

- case 1
```sh
# create test files
touch /tmp/{90-linux.hook,90-mkinitcpio.hook}

# let's tab
ls|less|vim|whatever_command /tmp/90[TAB HERE] 
```

when press TAB, it goes directly to `90-mkinitcpio.hook`

- case 2

```sh
# we have these files
ls -1d /usr/share/li*
/usr/share/libalpm
/usr/share/libgpg-error
/usr/share/libtool
/usr/share/licenses

# let's tab 

ls /usr/share/li[TAB HERE]
```
when press TAB, it goes directly to `/usr/share/licenses`

**Expected behavior**  
it should list the files start with `90` in case 1 and `li` in case 2

**zimfw info**  
```
# In a terminal, run zimfw info, and paste the output here.
zimfw version:        1.10.0 (built at 2022-09-27 22:44:10 UTC, previous commit is 05b8e0c)
OSTYPE:               linux-gnu
TERM:                 tmux-256color
TERM_PROGRAM:         tmux
TERM_PROGRAM_VERSION: 3.3a
ZIM_HOME:             /home/user/.zim
ZSH_VERSION:          5.9
```

**Additional context**  
macOS does not have this issue.

**Comment by ericbn** [comment]
I confirm I cannot reproduce this on macOS. Will try on a linux docker image later.

**Comment by ericbn** [comment]
Thanks for reporting the fix!
