### ISSUE TITLE
Adding pure leads to segfault

### ISSUE THREAD

**Issue by poetaman** [zimfw/zimfw#492]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
``Segmentation fault: 11`` caused by the presence of pure in ``.zimrc``

**Steps to reproduce**  
1. Install zimfw
2. Edit .zimrc to add [pure](https://github.com/sindresorhus/pure) the way it is described on zimfw's homepage.

**Current behavior**  
Pure prompt appears when shell starts, shell exits with segfault when I press enter for the first time (with or without a command like ``ls``).

**Expected behavior**  
Don't segfault!

**Screenshots**  
<img width="472" alt="Screenshot 2022-12-21 at 4 52 49 PM" src="https://user-images.githubusercontent.com/71736629/209032353-82c14b10-40d3-42ca-bc06-c057fd856ec4.png">

**zimfw info**  
NOOOTTTEEEE: This is after removing pure, as keeping pure there doesn't let me do anything in the terminal.
```
# In a terminal, run zimfw info, and paste the output here.
% zimfw info
zimfw version:        1.11.0 (built at 2022-12-18 21:05:25 UTC, previous commit is e54958b)
OSTYPE:               darwin22.0
TERM:                 tmux-256color
TERM_PROGRAM:         tmux
TERM_PROGRAM_VERSION: next-3.4
ZIM_HOME:             /Users/poetaman/.zim
ZSH_VERSION:          5.8.1
```

```
                    c.'          poetaman@macos.local
                 ,xNMM.          ---------------------
               .OMMMMo           OS: macOS 13.1 22C65 arm64
               lMM"              Host: MacBookPro18,2
     .;loddo:.  .olloddol;.      Kernel: 22.2.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 2 hours, 41 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 383 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2056x1329
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: tmux
  'XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1 Max
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1 Max
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 10613MiB / 32768MiB
       "cooc*"    "*coo'"



```

**Additional context**  
I already had zinit, and pure was functioning well in it.

**Comment by yuriaps** [comment]
Please, could you make the `steps to reproduce` completely detailed?

**Comment by poetaman** [comment]
It does not happen anymore on macOS 13.5; also a lot of packages got upgraded in the meanwhile. Closing this issue as it might not be relevant anymore.
