### ISSUE TITLE
How to show single quotes of a directory with spaces？

### ISSUE THREAD

**Issue by wengyk** [zimfw/zimfw#497]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [ ] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [ ] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [ ] I was able to reproduce the issue with a clean installation of Zim.
- [ ] I've pasted the output of `zimfw info` below.

**Describe the bug**  

**Steps to reproduce**  
The fist 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. Other steps to reproduce the behavior

**Current behavior**  
A clear and concise description of what is currently happening.

**Expected behavior**  

**Screenshots**  

**zimfw info**  
```
# In a terminal, run zimfw info, and paste the output here.
```

**Additional context**

**Comment by wengyk** [comment]
zsh defaults to single quotes for directories with spaces, but zimfw removes the single quotes and I want this feature back. But I don't know how to do it?

**Comment by wengyk** [comment]
I tried to export QUOTING_STYLE=shell, but it did not work.

**Comment by ericbn** [comment]
You mean your ZIM_HOME is in a directory with spaces or one of you modules is in a directory with spaces in the name?

**Comment by wengyk** [comment]
> You mean your ZIM_HOME is in a directory with spaces or one of you modules is in a directory with spaces in the name?

I mean any directory, for example, a directory with the name a b. When I have zimfw installed, ls -l shows the directory as a b. If zimfw is not installed, ls -l shows the directory as 'a b'. I want to have zimfw installed so that it can also be displayed as 'a b', how can I do that?

**Comment by ericbn** [comment]
I see the BSD ls shows directory names without quotes, and the GNU ls shows directories with quotes. Our [utility](https://github.com/zimfw/utility) module creates an alias to ls and tries to best guess if you're using the BSD or the GNU ls:

```
if whence dircolors >/dev/null && ls --version &>/dev/null; then print "I'm using GNU"; else print "I'm using BSD"; fi
```

If the command above prints "I'm using BSD", then you won't get quotes.

**Comment by wengyk** [comment]
> I see the BSD ls shows directory names without quotes, and the GNU ls shows directories with quotes. Our [utility](https://github.com/zimfw/utility) module creates an alias to ls and tries to best guess if you're using the BSD or the GNU ls:
> 
> ```
> if whence dircolors >/dev/null && ls --version &>/dev/null; then print "I'm using GNU"; else print "I'm using BSD"; fi
> ```
> 
> If the command above prints "I'm using BSD", then you won't get quotes.

Thank you very much for your patient answer, I found the reason, it turns out that the “alias ls='exa --group-directories-first'” I set caused the problem to happen, I was really stupid, I am ashamed to waste your time.
