### ISSUE TITLE
complete module has problems with starship and spaceship

### ISSUE THREAD

**Issue by Console32** [zimfw/zimfw#504]
- [  x ] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [ x ] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [ x ] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [ x ] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [ x ] I was able to reproduce the issue with a clean installation of Zim.
- [ x ] I've pasted the output of `zimfw info` below.

**Describe the bug**  
The completion module does prepand two characters to my prompt when used with spaceship or starship. 

**Steps to reproduce**  
The fist 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. Install latest version of starship using brew (`brew install starship`)
6. eval "$(starship init zsh)"
7. vi<TAB>

**Current behavior**  
The prompt show the first two characters twice.

**Expected behavior**  
Does not show duplicate characters 

**Screenshots**  
In the following screenshot I typed `vi<TAB>` and the prompt line gets changed to `vivi`
![image](https://user-images.githubusercontent.com/4870099/227187878-19f4b1b0-b81f-4521-85d8-88c6e63b0012.png)

**zimfw info**  
```
❯ zimfw info
zimfw version:        1.11.3 (built at 2023-02-26 00:43:41 UTC, previous commit is 6a24459)
OSTYPE:               darwin22.0
TERM:                 xterm-256color
TERM_PROGRAM:         iTerm.app
TERM_PROGRAM_VERSION: 3.4.19
ZIM_HOME:             /private/var/folders/93/t3qz6s2s7j1gd_pw7f4n108c0000gn/T/tmp.BoD0fVhF/.zim
ZSH_VERSION:          5.8.1

```

**Additional context**  

* Additionally I tried the same with spaceship, 
* And removed all other zmodules from the `~/.zimrc`
Problem persists. I did setup the MAC yesterday, pretty clean slate

**Comment by ericbn** [comment]
Hi. Thanks for reporting this. I've seen it happen once to myself in the past, but I was not able to reproduce and not being able to reproduce with the steps you describe. I've kept only `zmodule completion` in .zimrc.

Can you try to reproduce this in a Docker container maybe?

**Comment by ericbn** [comment]
Are you constantly getting this unexpected behavior, and disabling `zmodule completion` and restarting the terminal constantly removes the issue? You can enable Zsh debugging by running `setopt xtrace`. Disable with `unsetopt xtrace`

**Comment by Console32** [comment]
Yes @ericbn, It occueres 100% of the time. I tried reproducing in docker, had no luck.

When I set `setopt xtrace` I can see the following after pressing the tab key:


```
v+_zsh_autosuggest_async_response:1> emulate -L zsh
+_zsh_autosuggest_async_response:3> local suggestion
+_zsh_autosuggest_async_response:5> [[ -z '' ]]
+_zsh_autosuggest_async_response:7> IFS='' +_zsh_autosuggest_async_response:7> read -rd '' -u 12 suggestion
+_zsh_autosuggest_async_response:8> zle autosuggest-suggest -- vi
v+_zsh_autosuggest_async_response:15> zle -F 12
vi  vi
-- external command --
vi        vifs      vimdiff   vipw      visudo
view      vim       vimtutor  vis
-- alias --
vi                                 vim
-- parameter --
VIRTUAL_ENV_DISABLE_PROMPT
```

If I disable all other modules and only keep `complete` the output becomes huge
[log.txt](https://github.com/zimfw/zimfw/files/11059364/log.txt)

**Comment by ericbn** [comment]
I see this issue being reported here: https://github.com/starship/starship/issues/4669

**Comment by Console32** [comment]
Thanks!

Adding the following export solves this:
```
export LANG=en_US.UTF-8
```
