### ISSUE TITLE
zsh-users/zsh-completions  causes .zcompdump* regenerated when `source ~/.zshrc`

### ISSUE THREAD

**Issue by cattyhouse** [zimfw/zimfw#507]
### issue:

when `zmodule zsh-users/zsh-completions --fpath src` enabled in `.zimrc`, every `source ~/.zshrc` will generate new `.zcompdump*`

### reproduce:

1. uncomment `zmodule zsh-users/zsh-completions --fpath src` in .zimrc
2. exec zsh
3. `for i in 1 2 3 4 5 ; do source ~/.zshrc && ls --full-time ~/.zcompdump* ; sleep 1 ; done`
4. result: `.zcompdump*` timestamps differ in every run

### zimfw info

```
zimfw version:        1.11.3 (built at 2023-02-26 00:43:41 UTC, previous commit is 6a24459)
OSTYPE:               linux-gnu
TERM:                 tmux-256color
TERM_PROGRAM:
TERM_PROGRAM_VERSION:
ZIM_HOME:             /home/^_^/.zim
ZSH_VERSION:          5.9

```

**Comment by ericbn** [comment]
Doing `source ~/.zshrc` is a bad ideia. Zsh's compinit might pick a different fpath value compared to the value it got during start up. I suggest using `exec zsh` if you want to restart your shell.
