### ISSUE TITLE
Plugin "web-search" of Ohmyzsh not working

### ISSUE THREAD

**Issue by yuriaps** [zimfw/zimfw#517]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
The plugin `web-search` from oh-my-zsh doesn't work

**Steps to reproduce**  
The fist 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. add "zmodule ohmyzsh/ohmyzsh --root plugins/web-search" to `.zimrc`
6. `zimfw install`
7.  `. zshrc`
8. `google helloworld`

**Current behavior**  
The terminal recognise `google` as a valid command (green highlight) 
But two error messages are appearing. [plugin page](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/web-search/README.md)

**Expected behavior**  
Expected to open the browser with google page searching for "helloworld"

**Screenshots**  
![image](https://github.com/zimfw/zimfw/assets/33907201/ea5bd252-2682-434f-8ae0-95c37b1e817c)

**zimfw info**  
```
127 % zimfw info                                                                                                        zimfw version:        1.12.0 (built at 2023-07-17 23:54:58 UTC, previous commit is 49386ca)                             LANG:                 C.UTF-8                                                                                           OSTYPE:               linux-gnu                                                                                         TERM:                 xterm-256color                                                                                    TERM_PROGRAM:                                                                                                           TERM_PROGRAM_VERSION:                                                                                                   ZIM_HOME:             /tmp/tmp.s36hkcCN5v/.zim                                                                          ZSH_VERSION:          5.8.1  
```

**Additional context**

**Comment by ericbn** [comment]
As I [have](https://github.com/zimfw/zimfw/discussions/511#discussioncomment-5907202) [mentioned](https://github.com/zimfw/zimfw/discussions/502#discussioncomment-5256679) [before](https://github.com/zimfw/zimfw/discussions/501#discussioncomment-5194078), ohmyzsh is not exactly modular: their plugins also depend on different scripts in their lib subdirectory.

Is this specific case, you'll also need to include:
```
zmodule ohmyzsh/ohmyzsh --source lib/functions.zsh
```
in your .zimrc file.
