### ISSUE TITLE
_zimfw_pull_print_okay needs to escape backticks

### ISSUE THREAD

**Issue by grimm26** [zimfw/zimfw#521]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

I noticed something weird during a `zimfw update`:

```
-b: command not found
Command 'blame' not found, but can be installed with:
sudo apt install rcs-blame
```
I eventually found the problem by rolling back the ohmyzsh module update that had happened and found that the commit message had triggered this issue:
```
+_zimfw_tool_git:89> _zimfw_pull_print_okay 'Updating c74f2a1b..bae577d6' 0 $'* \C-[[33mbae577d6\C-[[m fix(git)!: remove `-b` from `blame` alias (#11864) \C-[[36m(4 hours ago)\C-[[m'                                      
+_zimfw_pull_print_okay:2> [[ -n '' ]]                                                                        
+_zimfw_pull_print_okay:11> _zimfw_print_okay 'Updating c74f2a1b..bae577d6' 0 $'* \C-[[33mbae577d6\C-[[m fix(git)!: remove `-b` from `blame` alias (#11864) \C-[[36m(4 hours ago)\C-[[m'                                    
+_zimfw_print_okay:1> ((  _zprintlevel > 0  ))                                                                +_zimfw_print_okay:1> print -PlR $'\C-[[2K\C-M%F{green})%f %Bohmyzsh:%b Updating c74f2a1b..bae577d6' $'  * \C-[[33mbae577d6\C-[[m fix(git)!: remove `-b` from `blame` alias (#11864) \C-[[36m(4 hours ago)\C-[[m'           
+_zimfw_print_okay:1> -b                                                                                      -b: command not found                                                                                         
+_zimfw_print_okay:1> blame                                                                                   
Command 'blame' not found, but can be installed with:                                                         
sudo apt install rcs-blame                                                      
```

The backticks used in the commit message in bae577d6 of ohmyzsh seem to be interpolated inside that print command. More safety is needed :)

### Steps to reproduce

1. Include a plugin from ohmyzsh in your config.
2. zimfw install
3. go into the `~/.zim/modules/ohmyzsh` directory and `git reset --hard c74f2a1b`
4. `zimfw update`

### Current behavior

text inside backticks in commit messages of modules are executed.

### Expected behavior

Do not execute random commit message text inside of backticks

### zimfw info

```shell
zimfw version:        1.12.0 (built at 2023-07-17 23:54:58 UTC, previous commit is 49386ca)
LANG:                 en_US.UTF-8
LC_COLLATE:           C
OSTYPE:               linux-gnu
TERM:                 xterm-kitty
TERM_PROGRAM:         
TERM_PROGRAM_VERSION: 
ZIM_HOME:             /home/mkeisler/.zim
ZSH_VERSION:          5.8.1
```

**Comment by ericbn** [comment]
Issue is that we use `print -PlR` and the `-P` is used to expand prompt color sequences like `%B`, `%F{green}`, `%b`, `%f`, etc. but now I see it also expands the backtick.

```
❯  print -PlR 'foo `bar` baz'
zsh: command not found: bar
foo  baz

❯  print -lR 'foo `bar` baz'
foo `bar` baz
```

I think the solution is to replace the prompt color sequences by the respective ANSI escape codes and remove the `-P` from the `print` calls.

Thanks for reporting this!

**Comment by ericbn** [comment]
Just released version 1.12.1 with a fix for this. This was potentially a security issue, so thanks again for reporting this. I hope I've improved how print is used to avoid any expansions from now on.

**Comment by grimm26** [comment]
Thanks for your attention!

**Comment by ericbn** [comment]
Working well now :- )

<img width="646" src="https://github.com/zimfw/zimfw/assets/4120606/12c6630c-2eca-4fd0-83fe-6cbf6b25738a"/>
