### ISSUE TITLE
Allow loading binaries and/or plugins from GH release

### ISSUE THREAD

**Issue by hoshsadiq** [zimfw/zimfw#523]
### Is your feature request related to a problem? Please describe.

I'm migrating away from zinit, and one thing that zinit did was give the option to download binaries directly from GitHub releases. This essentially downoaded the binaries and then added a relevant path to the `$PATH`. E.g. I could do:

```
zinit light-mode from'gh-r' as'program' wait'2' silent for pick'shellcheck-*/shellcheck' @koalaman/shellcheck
# or
zinit ice silent wait as"program" from"gh-r" atload'export FZF_DEFAULT_OPTS="--reverse --exit-0 --border --ansi"'
zinit light junegunn/fzf
```
The above are two different ways of doing essentially the same thing, just with different programs, but both would download the latest binary (a version can be specified) release from shellcheck to a plugin dir, and add it to the PATH.

### Describe the solution you'd like

Not sure what it would look like. Zinit's API is quite cumbersome, so I'd love something better. I had a look at `zplug` version of it, and it seems a lot easier to understand, so maybe something like that?

### Describe alternatives you've considered

Thinking I might use zplug just for binary management, and use zim for the rest, if possible.

**Comment by ericbn** [comment]
Hi @hoshsadiq.

Why not use your OS package manager or nix to install binaries? See [here for shellcheck specifically](https://github.com/koalaman/shellcheck#installing). And even if you don't like that solution, there are others, like using [asdf](https://github.com/asdf-vm/asdf) for example. Here's the [asdf plugin for shellcheck](https://github.com/luizm/asdf-shellcheck).

I think it's overkill to have a zsh plugins manager also installing binaries. I prefer having zimfw do one thing and do it well, which is the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Origin) for command line tools.

**Comment by hoshsadiq** [comment]
I think this is fine for some, but not all. Many utilities I use don't have a package in the repos (also not ideal for user binaries anyway), nor an asdf plugin (quite often overkill, as I don't need different versions of e.g. jless or jq). 

You can see a bunch of the tools I use [here](https://github.com/hoshsadiq/dot_files/blob/master/zshrc.d/003-zplugin.zsh) (all configured via zinit). Some come from the repo as a zsh plugin, some from GH releases. I don't believe any of them should be handled by either asdf or the OS's package manager.

> I think it's overkill to have a zsh plugins manager also installing binaries. I prefer having zimfw do one thing and do it well, which is the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Origin) for command line tools.

That's fair. I guess due to me having used zinit for a long time, I kind of assume zsh plugin manager is also able to load things from GH releases (I guess, in theory, a zsh plugin could live in GH releases), but while trying to move away from zinit, I realized there aren't many plugin managers that also handle GH releases.

**Comment by ericbn** [comment]
I agree asdf (or rtx) makes sense specifically to manage multiple versions of the same tool.

Any specific tool you use that cannot be installed via package manager?

Following the unix philosophy, I'd intuitively think there might be a tool to specifically install binaries from GitHub releases. That's not even a shell-specific thing, like zsh plugin managers can be. A quick search and I found https://github.com/warrensbox/hubapp/

**Comment by hoshsadiq** [comment]
Yeah, I've been looking, the current options are not too great. Either way, thanks! :)

**Comment by ericbn** [comment]
Here's another tool that can do this: https://github.com/zyedidia/eget
