### ISSUE TITLE
Add support for including Codeberg-hosted ZSH plugins

### ISSUE THREAD

**Issue by cyrus01337** [zimfw/zimfw#535]
### Is your feature request related to a problem? Please describe.

I'm a big fan of [Zellij](https://github.com/zellij-org/zellij) and had it integrated through OMZ, and have wanted to try out something different to give it a spin.

I love ZimFW so far, though I've hit a snag in being able to include a community-made [Zellij plugin](https://codeberg.org/tranzystorekk/zellij.zsh) as it is not hosted on GitHub/GitLab.

Theoretically, the following should be possible as shown [here](https://github.com/zimfw/zimfw?tab=readme-ov-file#zmodule) (3rd and 6th point, image below):
![ZModule points highlighting the possible implementation of Codeberg-hosted ZSH plugins](https://github.com/zimfw/zimfw/assets/63274991/7e07d747-6103-4eda-91e3-55a0338522ff)

The URL specified could be considered custom as it is not GitHub/GitLab, yet still points to a valid `.git` endpoint that can be viewed/manipulated like any other project hosted on the aforementioned sites:
```sh
zmodule https://codeberg.org/tranzystorekk/zellij.zsh.git --source zellij.plugin.zsh --no-submodules
```

**EDIT**: Hyperlinked to Zellij

### Describe the solution you'd like

For Codeberg-hosted ZSH plugins to be "whitelisted"(?) as a viable means of installing ZSH plugins through `zmodule`.

### Describe alternatives you've considered

Looking into how `zmodule` inserts modules and manually implementing the plugin (hassle to others as well as myself if having to do many times over)

**Comment by ericbn** [comment]
Make sure you don't have `zstyle ':zim:zmodule' use 'degit'` in your .zimrc -- meaning you've set degit as your default zmodule tool --, then the zmodule call you mentioned should work (no need for `--no-submodule` since that repo has no submodule anyway).

If you're using degit as the default zmodulke tool, you can override that for this specific zmodule with:
```
zmodule https://codeberg.org/tranzystorekk/zellij.zsh.git --use git --source zellij.plugin.zsh
```

**Comment by cyrus01337** [comment]
Wow, did not think that Degit would be the problem, you can tell I'm new to that as well. Tried what you sent and it works like a charm now.

This is covered fine in the project also, so unfortunately for me this is a me issue. Great work so far to you and all that have contributed, loving ZimFW so far. :)
