### ISSUE TITLE
Subsequent `source ~/.zshrc` throws error

### ISSUE THREAD

**Issue by samtay** [zimfw/zimfw#539]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

Basically,

```shell
❯ source ~/.zshrc
warning: completion was already initialized before completion module. Will call compinit again. See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
warning: compinit being called again after completion module at /home/sam/.zim/modules/completion/init.zsh:35
```

I followed the instructions at the link and concluded here:

> If there's a "compinit being called at ..." message in the terminal, and it mentions Zim's "modules/completion/init.zsh" file, then you're good.

So, a fresh terminal session works fine without errors, but subsequent `source ~/.zshrc` throws the error. What's the intended way to reload your configuration without starting a new terminal session?

### Steps to reproduce

1. ```
   cd ${$(mktemp -d):A} && \
       ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim && \
       curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh && \
       exec zsh
   ```
2. `source $HOME/.zshrc`


### Current behavior

Current behavior throws an error like:

```shell
% source $HOME/.zshrc              
warning: completion was already initialized before completion module. Will call compinit again. See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
warning: compinit being called again after completion module at /tmp/tmp.ELzioLyKIS/.zim/modules/completion/init.zsh:35
```

### Expected behavior

No errors.

### zimfw info

```shell
zimfw version:        1.14.0 (built at 2024-06-25 17:29:35 UTC, previous commit is 3b7908d)
LANG:                 en_US.UTF-8
OSTYPE:               linux-gnu
TERM:                 xterm-kitty
TERM_PROGRAM:         
TERM_PROGRAM_VERSION: 
ZIM_HOME:             /tmp/tmp.ELzioLyKIS/.zim
ZSH_VERSION:          5.9
```

**Comment by ericbn** [comment]
Hi @samtay

> What's the intended way to reload your configuration without starting a new terminal session?

```
exec zsh
```

See https://unix.stackexchange.com/a/532591/85616

**Comment by samtay** [comment]
Huh, I've never encountered this issue until now, but the info in there all makes sense. Will close as my mistake. Thanks!
