### ISSUE TITLE
Opening a new terminal throw warnings

### ISSUE THREAD

**Issue by assapir** [zimfw/zimfw#540]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

What happens:
When I am either SSHing or just opening a console in my machine, I am getting the following warnings:
```
warning: completion was already initialized before completion module. Will call compinit again. See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
warning: compinit being called again after completion module at /home/assaf/.zim/modules/completion/init.zsh:35
```

### Steps to reproduce

Installed a new machine with zim

### Current behavior

The current behavior show warnings, but the help message say that if the message is from `modules/completion/init.zsh` it should be fine

### Expected behavior

no warnings

### zimfw info

```shell
imfw version:        1.14.0 (built at 2024-06-25 17:29:35 UTC, previous commit is 3b7908d)
LANG:                 en_IL.UTF-8
OSTYPE:               linux-gnu
TERM:                 xterm-256color
TERM_PROGRAM:         
TERM_PROGRAM_VERSION: 
ZIM_HOME:             /home/assaf/.zim
ZSH_VERSION:          5.9
```
```


### Additional context

_No response_

**Comment by ericbn** [comment]
The [troubleshooting wiki](https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working) mentions:

> In case you're getting a "warning: compinit being called again after completion module at .../modules/completion/init.zsh" mentioning Zim's completion module, then possibly this means your `${ZIM_HOME}/init.zsh` script in being sourced twice. Double check your 
`~/.zshrc` file.

This is your case with the second warning. See also https://github.com/zimfw/completion/issues/22

The first warning is also another case you can investigate by reading the wiki carefully and following its instructions.

**Comment by assapir** [comment]
I have no idea what source `${ZIM_HOME}/init.zsh` for the second time, nor where `compinit` is called before. I tried to delete all relevant files, and run `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh` from scratch, and it still happens.

**Comment by assapir** [comment]
Regarding the first warning:  I did what the wiki states - running 
```
>>! ~/.zshenv <<\END
autoload -Uz +X compinit
functions[compinit]=$'print -u2 \'compinit being called at \'${funcfiletrace[1]}
'${functions[compinit]}
END
```
and reopen the terminal. it doesn't have any effect nor a different place it shows where it calls

**Comment by ericbn** [comment]
/etc/zshenv should be the only script sourced during Zsh startup before ~/.zshenv. It’s unlikely that /etc/zshenv is directly or indirectly calling compinit, but you might want to check there too in this case.

Also, be careful about running the zimfw install multiple times, as it will prepend the zimfw setup multiple times to your ~/.zshrc, which includes the `source ${ZIM_HOME}/init.zsh` line that you only want to exist once.

**Comment by assapir** [comment]
I have neither 
``` ls /etc/zshenv                
"/etc/zshenv": No such file or directory (os error 2)
``` 
nor 
``` 
"/home/assaf/.zshenv": No such file or directory (os error 2)
```

my zshrc file:
```
# Start configuration added by Zim install {{{
#
# User configuration sourced by interactive shells
#

# -----------------
# Zsh configuration
# -----------------

#
# History
#

# Remove older command from the history if a duplicate is to be added.
setopt HIST_IGNORE_ALL_DUPS

#
# Input/output
#

# Set editor default keymap to emacs (`-e`) or vi (`-v`)
bindkey -e

# Prompt for spelling correction of commands.
#setopt CORRECT

# Customize spelling correction prompt.
#SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '

# Remove path separator from WORDCHARS.
WORDCHARS=${WORDCHARS//[\/]}

# -----------------
# Zim configuration
# -----------------

# Use degit instead of git as the default tool to install and update modules.
#zstyle ':zim:zmodule' use 'degit'

# --------------------
# Module configuration
# --------------------

#
# git
#

# Set a custom prefix for the generated aliases. The default prefix is 'G'.
#zstyle ':zim:git' aliases-prefix 'g'

#
# input
#

# Append `../` to your input for each `.` you type after an initial `..`
#zstyle ':zim:input' double-dot-expand yes

#
# termtitle
#

# Set a custom terminal title format using prompt expansion escape sequences.
# See http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Simple-Prompt-Escapes
# If none is provided, the default '%n@%m: %~' is used.
#zstyle ':zim:termtitle' format '%1~'

#
# zsh-autosuggestions
#

# Disable automatic widget re-binding on each precmd. This can be set when
# zsh-users/zsh-autosuggestions is the last module in your ~/.zimrc.
ZSH_AUTOSUGGEST_MANUAL_REBIND=1

# Customize the style that the suggestions are shown with.
# See https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#suggestion-highlight-style
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'

#
# zsh-syntax-highlighting
#

# Set what highlighters will be used.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Customize the main highlighter styles.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it
#typeset -A ZSH_HIGHLIGHT_STYLES
#ZSH_HIGHLIGHT_STYLES[comment]='fg=242'

# ------------------
# Initialize modules
# ------------------

ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  if (( ${+commands[curl]} )); then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  else
    mkdir -p ${ZIM_HOME} && wget -nv -O ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  fi
fi
# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
# Initialize modules.
source ${ZIM_HOME}/init.zsh

# ------------------------------
# Post-init module configuration
# ------------------------------

#
# zsh-history-substring-search
#

zmodload -F zsh/terminfo +p:terminfo
# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
for key ('^[[A' '^P' ${terminfo[kcuu1]}) bindkey ${key} history-substring-search-up
for key ('^[[B' '^N' ${terminfo[kcud1]}) bindkey ${key} history-substring-search-down
for key ('k') bindkey -M vicmd ${key} history-substring-search-up
for key ('j') bindkey -M vicmd ${key} history-substring-search-down
unset key
# }}} End configuration added by Zim install

eval "$(starship init zsh)"
alias ls='eza =-lh --icons=auto'
alias cat='bat -p --paging=never'
alias ls='exa -alh --icons'
alias kubectl='kubecolor'
alias k='kubectl'
alias tf='terraform'

source /usr/share/nvm/init-nvm.sh


autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

export EDITOR=nano
export PATH="/usr/share/rvm/bin:$HOME/.cargo/bin:$PATH"
fpath+=~/.zfunc

```
as saod - this also happens with fresh install

**Comment by assapir** [comment]
I installed using https://aur.archlinux.org/packages?O=0&K=zim-git

**Comment by ericbn** [comment]
Not sure what the aur zim-git package does besides changing your zshrc. You might want to contact the maintainers of the package, or clean your startup files from any previous zim-git installation and use our own installation script:
```
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
```

Regardless on how you install Zim, these are the startup files you might want to double check: https://zsh.sourceforge.io/Doc/Release/Files.html#Startup_002fShutdown-Files

Also make sure you don't have any other Zsh framework installed. Our installation script shows warnings in case it identifies some of them.

**Comment by assapir** [comment]
Removing the package solves the problem. Thanks.

**Comment by PatTheMav** [comment]
> /etc/zshenv should be the only script sourced during Zsh startup before ~/.zshenv. It’s unlikely that /etc/zshenv is directly or indirectly calling compinit, but you might want to check there too in this case.

Turns out, that's _precisely_ what's happening on Ubuntu 24.04 but with `/etc/zsh/zshrc`:

```bash
# If you don't want compinit called here, place the line
# skip_global_compinit=1
# in your $ZDOTDIR/.zshenv
if (( ${${(@f)"$(</etc/os-release)"}[(I)ID*=*ubuntu]} )) &&
   [[ -z "$skip_global_compinit" ]]; then
  autoload -U compinit
  compinit
fi
```

Fortunately they spell out explicitly how to fix it, maybe a good idea to add this to the knowledge base as a "known issue".

**Comment by janoka** [comment]
My solution was to reinstall `zsh` on MacOS.

I got the same error message. Thank you for the conversation. I double-checked the file date in the `/opt/homebrew/bin` folder, and I saw it was pretty outdated. I ran the `brew reinstall zsh`, which fixed the issue.
