### ISSUE TITLE
(anon):6: command not found: --zsh on every new shell

### ISSUE THREAD

**Issue by lrosenman** [zimfw/zimfw#541]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

every time I start a new shell I get:
`(anon):6: command not found: --zsh`

ever since these updates:
❯ zimfw upgrade && zimfw update
) /home/ler/.zim/zimfw.zsh: Updated. Restart your terminal for changes to take effect.
Done with upgrade.
) termtitle: Already up to date.
) environment: Already up to date.
) duration-info: Already up to date.
) input: Already up to date.
) zsh-syntax-highlighting: Already up to date.
) zsh-autosuggestions: Already up to date.
) git-info: Updating be665e4..ec87410
  * ec87410 Prefer pipe to process substitution (10 days ago)
) fzf: Updating b0539f5..c793d8d
  * c793d8d Update README.md (4 days ago)
  * 5a76b14 Abort if initializing fzf fails (11 days ago)
  * 50964d3 Handle 'batcat' executable name for bat (APT) (6 weeks ago)
) utility: Updating 2d738fb..6b12446
  * 6b12446 Unset NO_COLOR if colors are available (9 weeks ago)
) zsh-history-substring-search: Updating 8dd05bf..87ce96b
  * 87ce96b Merge pull request #159 from dxrcy/master (8 weeks ago)
  * 3235b88 Fix user input after search, including `space` key (6 months ago)
  * 837d499 Fix user input after search (6 months ago)
) zsh-completions: Updating b1cf651..4145b89
  *   4145b89 Merge pull request #1094 from zsh-users/update-rails (2 days ago)
  |\
  | * f8a220d Update rails completion (2 days ago)
  |/
  *   77005bb Merge pull request #1093 from zsh-users/update-go-completion (2 days ago)
  |\
  | * 2222283 Update environment variable completion (3 days ago)
  | * f036321 Update version (3 days ago)
  | * ef50c3a Update 'go test' completion (3 days ago)
  | * 9380071 Update 'go mod' completion (3 days ago)
  | * 580b096 Update 'go tool trace' completion (4 days ago)
  | * da937c9 Update 'go tool vet' completion (4 days ago)
  | * a8dacc9 Update 'go tool pack' completion (4 days ago)
  | * 238d3b0 Update 'go tool fix' completion (4 days ago)
  | * 13b8ba5 Update 'go tool compile' completion (4 days ago)
  | * 89d7a5e Update 'go list' completion (4 days ago)
  | * 78c0ab5 Update 'go generate' completion (4 days ago)
  | * aac5649 Update 'go fmt' completion (4 days ago)
  | * 61c84a2 Update 'go env' environment list (4 days ago)
  | * 937cd0f Complete package name in 'go doc' (4 days ago)
  | * f475c13 Improve 'go help' completion (4 days ago)
  | * 057d9a9 Update 'go fix' completion (5 days ago)
  | * 5a4bbc1 Update 'go tool cgo' completion (5 days ago)
  | * b4c9706 Add 'go tool buildid' completion (5 days ago)
  | * 91fce88 Update 'go tool asm' completion (5 days ago)
  | * 177fada Update 'go vet' completion (5 days ago)
  | * 4b55f14 Update help and work subcommand completions (5 days ago)
  |/
  *   f8c41db Merge pull request #1092 from zsh-users/refactor_go (5 days ago)
  |\
  | * 499e5be Don't use global variables (5 days ago)
  |/
  *   a50d486 Merge pull request #1091 from zsh-users/update-nano (2 weeks ago)
  |\
  | * 1416083 Update nano complete to version 8.1 (2 weeks ago)
  |/
  *   7a884c7 Merge pull request #1086 from zsh-users/update-node (5 weeks ago)
  |\
  | * 0a66357 Update node.js completion to version 22.3 (6 weeks ago)
  * |   7313f83 Merge pull request #1088 from Mumumu4/fix-nft-type-in-name (5 weeks ago)
  |\ \
  | * | 0bd94fb Fix nftables completion: when object name contains its type name, the completion may mass up (5 weeks ago)
  | |/
  * |   0a8eb1b Merge pull request #1087 from Mumumu4/update-nftable (5 weeks ago)
  |\ \
  | |/
  |/|
  | * 6621b9f Update nftables completion (5 weeks ago)
  |/
  * 978e79e Merge pull request #1084 from zsh-users/update-node (2 months ago)
  * fce3599 Update node completion for version 22.2.0 (3 months ago)
) completion: Updating ef4d8a5..625bdeb
  * 625bdeb Revert "expand-or-complete-or-list-files when TAB is pressed" (4 days ago)
  * 0f5cb95 Show warning on additional compinit calls (7 weeks ago)
  * 0a1d9c7 expand-or-complete-or-list-files when TAB is pressed (7 weeks ago)
) git: Updating 52c6e84..7a57a6e
  * 7a57a6e Add Gbn, GdI, Ghw and GiU aliases (8 weeks ago)
  * d728437 Use git log --date-order (8 weeks ago)
Done with update. Restart your terminal for changes to take effect.

### Steps to reproduce

Update to latest

### Current behavior

get `(anon):6: command not found: --zsh`
on every shell startup

### Expected behavior

no output other than the shell prompt on startup.

### zimfw info

```shell
❯ zimfw info
zimfw version:        1.14.0 (built at 2024-06-25 17:29:35 UTC, previous commit is 3b7908d)
LANG:                 C.UTF-8
OSTYPE:               freebsd13.3
TERM:                 xterm-256color
TERM_PROGRAM:
TERM_PROGRAM_VERSION:
ZIM_HOME:             /home/ler/.zim
ZSH_VERSION:          5.9

ler in thebighonker in doc on  main
❯
```

### Additional context

ler in thebighonker in doc on  main
❯ exec zsh -l

ler in thebighonker in doc on  main
❯ zimfw upgrade && zimfw update
) /home/ler/.zim/zimfw.zsh: Updated. Restart your terminal for changes to take effect.
Done with upgrade.
) termtitle: Already up to date.
) environment: Already up to date.
) duration-info: Already up to date.
) input: Already up to date.
) zsh-syntax-highlighting: Already up to date.
) zsh-autosuggestions: Already up to date.
) git-info: Updating be665e4..ec87410
  * ec87410 Prefer pipe to process substitution (10 days ago)
) fzf: Updating b0539f5..c793d8d
  * c793d8d Update README.md (4 days ago)
  * 5a76b14 Abort if initializing fzf fails (11 days ago)
  * 50964d3 Handle 'batcat' executable name for bat (APT) (6 weeks ago)
) utility: Updating 2d738fb..6b12446
  * 6b12446 Unset NO_COLOR if colors are available (9 weeks ago)
) zsh-history-substring-search: Updating 8dd05bf..87ce96b
  * 87ce96b Merge pull request #159 from dxrcy/master (8 weeks ago)
  * 3235b88 Fix user input after search, including `space` key (6 months ago)
  * 837d499 Fix user input after search (6 months ago)
) zsh-completions: Updating b1cf651..4145b89
  *   4145b89 Merge pull request #1094 from zsh-users/update-rails (2 days ago)
  |\
  | * f8a220d Update rails completion (2 days ago)
  |/
  *   77005bb Merge pull request #1093 from zsh-users/update-go-completion (2 days ago)
  |\
  | * 2222283 Update environment variable completion (3 days ago)
  | * f036321 Update version (3 days ago)
  | * ef50c3a Update 'go test' completion (3 days ago)
  | * 9380071 Update 'go mod' completion (3 days ago)
  | * 580b096 Update 'go tool trace' completion (4 days ago)
  | * da937c9 Update 'go tool vet' completion (4 days ago)
  | * a8dacc9 Update 'go tool pack' completion (4 days ago)
  | * 238d3b0 Update 'go tool fix' completion (4 days ago)
  | * 13b8ba5 Update 'go tool compile' completion (4 days ago)
  | * 89d7a5e Update 'go list' completion (4 days ago)
  | * 78c0ab5 Update 'go generate' completion (4 days ago)
  | * aac5649 Update 'go fmt' completion (4 days ago)
  | * 61c84a2 Update 'go env' environment list (4 days ago)
  | * 937cd0f Complete package name in 'go doc' (4 days ago)
  | * f475c13 Improve 'go help' completion (4 days ago)
  | * 057d9a9 Update 'go fix' completion (5 days ago)
  | * 5a4bbc1 Update 'go tool cgo' completion (5 days ago)
  | * b4c9706 Add 'go tool buildid' completion (5 days ago)
  | * 91fce88 Update 'go tool asm' completion (5 days ago)
  | * 177fada Update 'go vet' completion (5 days ago)
  | * 4b55f14 Update help and work subcommand completions (5 days ago)
  |/
  *   f8c41db Merge pull request #1092 from zsh-users/refactor_go (5 days ago)
  |\
  | * 499e5be Don't use global variables (5 days ago)
  |/
  *   a50d486 Merge pull request #1091 from zsh-users/update-nano (2 weeks ago)
  |\
  | * 1416083 Update nano complete to version 8.1 (2 weeks ago)
  |/
  *   7a884c7 Merge pull request #1086 from zsh-users/update-node (5 weeks ago)
  |\
  | * 0a66357 Update node.js completion to version 22.3 (6 weeks ago)
  * |   7313f83 Merge pull request #1088 from Mumumu4/fix-nft-type-in-name (5 weeks ago)
  |\ \
  | * | 0bd94fb Fix nftables completion: when object name contains its type name, the completion may mass up (5 weeks ago)
  | |/
  * |   0a8eb1b Merge pull request #1087 from Mumumu4/update-nftable (5 weeks ago)
  |\ \
  | |/
  |/|
  | * 6621b9f Update nftables completion (5 weeks ago)
  |/
  * 978e79e Merge pull request #1084 from zsh-users/update-node (2 months ago)
  * fce3599 Update node completion for version 22.2.0 (3 months ago)
) completion: Updating ef4d8a5..625bdeb
  * 625bdeb Revert "expand-or-complete-or-list-files when TAB is pressed" (4 days ago)
  * 0f5cb95 Show warning on additional compinit calls (7 weeks ago)
  * 0a1d9c7 expand-or-complete-or-list-files when TAB is pressed (7 weeks ago)
) git: Updating 52c6e84..7a57a6e
  * 7a57a6e Add Gbn, GdI, Ghw and GiU aliases (8 weeks ago)
  * d728437 Use git log --date-order (8 weeks ago)
Done with update. Restart your terminal for changes to take effect.

ler in thebighonker in doc on  main took 2s
❯ exec zsh -l
(anon):6: command not found: --zsh

ler in thebighonker in doc on  main
❯

**Comment by lrosenman** [comment]
This happens regardless of platform.  I have both FreeBSD and macOS.

**Comment by phoropter** [comment]
This is happening for me as well on a truenas scale system, the only common update I have with you is the update of zimfw itself. I just updated about 15 minutes ago, but it's been a while since I last updated it. 

I have it also installed on an arch system but don't get the error on there.

**Comment by ericbn** [comment]
@lrosenman @phoropter do you have the fzf module enabled, and maybe the fzf command not installed? This might be the issue.

**Comment by lrosenman** [comment]
Installing it on macOS fixed it, but it still fails on FreeBSD after installing it from ports.

**Comment by lrosenman** [comment]
Still fails on FreeBSD even after the above fix:
```
ler in playbox in ~
❯ zimfw upgrade && zimfw update
) /home/ler/.zim/zimfw.zsh: Already up to date
Done with upgrade.
) input: Already up to date.
) termtitle: Already up to date.
) completion: Already up to date.
) zsh-completions: Already up to date.
) zsh-autosuggestions: Already up to date.
) duration-info: Already up to date.
) git: Already up to date.
) utility: Already up to date.
) git-info: Already up to date.
) zsh-syntax-highlighting: Already up to date.
) environment: Already up to date.
) fzf: Updating c793d8d..690321d
  * 690321d Better error message if fzf is not installed (5 minutes ago)
) zsh-history-substring-search: Already up to date.
Done with update. Restart your terminal for changes to take effect.

ler in playbox in ~ took 7s
❯ exec zsh -l
unknown option: --zsh

ler in playbox in ~
❯ fzf --help
usage: fzf [options]

  Search
    -x, --extended         Extended-search mode
                           (enabled by default; +x or --no-extended to disable)
    -e, --exact            Enable Exact-match
    -i                     Case-insensitive match (default: smart-case match)
    +i                     Case-sensitive match
    --scheme=SCHEME        Scoring scheme [default|path|history]
    --literal              Do not normalize latin script letters before matching
    -n, --nth=N[,..]       Comma-separated list of field index expressions
                           for limiting search scope. Each can be a non-zero
                           integer or a range expression ([BEGIN]..[END]).
    --with-nth=N[,..]      Transform the presentation of each line using
                           field index expressions
    -d, --delimiter=STR    Field delimiter regex (default: AWK-style)
    +s, --no-sort          Do not sort the result
    --track                Track the current selection when the result is updated
    --tac                  Reverse the order of the input
    --disabled             Do not perform search
    --tiebreak=CRI[,..]    Comma-separated list of sort criteria to apply
                           when the scores are tied [length|chunk|begin|end|index]
                           (default: length)

  Interface
    -m, --multi[=MAX]      Enable multi-select with tab/shift-tab
    --no-mouse             Disable mouse
    --bind=KEYBINDS        Custom key bindings. Refer to the man page.
    --cycle                Enable cyclic scroll
    --keep-right           Keep the right end of the line visible on overflow
    --scroll-off=LINES     Number of screen lines to keep above or below when
                           scrolling to the top or to the bottom (default: 0)
    --no-hscroll           Disable horizontal scroll
    --hscroll-off=COLS     Number of screen columns to keep to the right of the
                           highlighted substring (default: 10)
    --filepath-word        Make word-wise movements respect path separators
    --jump-labels=CHARS    Label characters for jump and jump-accept

  Layout
    --height=[~]HEIGHT[%]  Display fzf window below the cursor with the given
                           height instead of using fullscreen.
                           If prefixed with '~', fzf will determine the height
                           according to the input size.
    --min-height=HEIGHT    Minimum height when --height is given in percent
                           (default: 10)
    --layout=LAYOUT        Choose layout: [default|reverse|reverse-list]
    --border[=STYLE]       Draw border around the finder
                           [rounded|sharp|bold|block|thinblock|double|horizontal|vertical|
                            top|bottom|left|right|none] (default: rounded)
    --border-label=LABEL   Label to print on the border
    --border-label-pos=COL Position of the border label
                           [POSITIVE_INTEGER: columns from left|
                            NEGATIVE_INTEGER: columns from right][:bottom]
                           (default: 0 or center)
    --margin=MARGIN        Screen margin (TRBL | TB,RL | T,RL,B | T,R,B,L)
    --padding=PADDING      Padding inside border (TRBL | TB,RL | T,RL,B | T,R,B,L)
    --info=STYLE           Finder info style
                           [default|right|hidden|inline[:SEPARATOR]|inline-right]
    --separator=STR        String to form horizontal separator on info line
    --no-separator         Hide info line separator
    --scrollbar[=C1[C2]]   Scrollbar character(s) (each for main and preview window)
    --no-scrollbar         Hide scrollbar
    --prompt=STR           Input prompt (default: '> ')
    --pointer=STR          Pointer to the current line (default: '>')
    --marker=STR           Multi-select marker (default: '>')
    --header=STR           String to print as header
    --header-lines=N       The first N lines of the input are treated as header
    --header-first         Print header before the prompt line
    --ellipsis=STR         Ellipsis to show when line is truncated (default: '..')

  Display
    --ansi                 Enable processing of ANSI color codes
    --tabstop=SPACES       Number of spaces for a tab character (default: 8)
    --color=COLSPEC        Base scheme (dark|light|16|bw) and/or custom colors
    --no-bold              Do not use bold text

  History
    --history=FILE         History file
    --history-size=N       Maximum number of history entries (default: 1000)

  Preview
    --preview=COMMAND      Command to preview highlighted line ({})
    --preview-window=OPT   Preview window layout (default: right:50%)
                           [up|down|left|right][,SIZE[%]]
                           [,[no]wrap][,[no]cycle][,[no]follow][,[no]hidden]
                           [,border-BORDER_OPT]
                           [,+SCROLL[OFFSETS][/DENOM]][,~HEADER_LINES]
                           [,default][,<SIZE_THRESHOLD(ALTERNATIVE_LAYOUT)]
    --preview-label=LABEL
    --preview-label-pos=N  Same as --border-label and --border-label-pos,
                           but for preview window

  Scripting
    -q, --query=STR        Start the finder with the given query
    -1, --select-1         Automatically select the only match
    -0, --exit-0           Exit immediately when there's no match
    -f, --filter=STR       Filter mode. Do not start interactive finder.
    --print-query          Print query as the first line
    --expect=KEYS          Comma-separated list of keys to complete fzf
    --read0                Read input delimited by ASCII NUL characters
    --print0               Print output delimited by ASCII NUL characters
    --sync                 Synchronous search for multi-staged filtering
    --listen[=HTTP_PORT]   Start HTTP server to receive actions (POST /)
    --version              Display version information and exit

  Environment variables
    FZF_DEFAULT_COMMAND    Default command to use when input is tty
    FZF_DEFAULT_OPTS       Default options
                           (e.g. '--layout=reverse --inline-info')


ler in playbox in ~
>
```

**Comment by ericbn** [comment]
This will still fail if fzf version is <[0.48.0](https://github.com/junegunn/fzf/releases/tag/0.48.0)

**Comment by lrosenman** [comment]
```
❯ fzf --version
0.42 (2023012)

ler in playbox in ~
❯
```
I'll get with the FreeBSD port maintainer..... (I'm a ports committer, ler@FreeBSD.org)

**Comment by phoropter** [comment]
Installing fzf via git worked for me. Sorry and thanks. Would have sworn I had it installed on there already.

**Comment by lrosenman** [comment]
There was a PR to update fzf in the FreeBSD Bugzilla that had been sitting for months.  I've pushed that upgrade.
