### ISSUE TITLE
Wiki: Suggest `skip_global_compinit = 1` for ubuntu user

### ISSUE THREAD

**Issue by milanglacier** [zimfw/zimfw#546]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

On Ubuntu system, in `/etc/zsh/zshrc` there are lines:

```bash
if (( ${${(@f)"$(</etc/os-release)"}[(I)ID*=*ubuntu]} )) &&
  [[ -z "$skip_global_compinit" ]]; then
  autoload -U compinit
  compinit
fi
```

which will result in `compinit` always initialized during startup, and `zim` will then yield an error notifying the user that `compinit` has already been called.

The suggestion is to add a section in Wiki [troubleshooting section](https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working) to notify ubuntu user to put 

```bash
skip_global_compinit = 1
```

in the `~/.zshenv`

### Steps to reproduce

.

### Current behavior

.

### Expected behavior

.

**Comment by ericbn** [comment]
Thanks, I'll add this to the Wiki.

SIDE NOTE: Installing zsh with [Homebrew on Linux](https://docs.brew.sh/Homebrew-on-Linux) (aka linuxbrew) instead of apt won't give you this issue. I'm finding Homebrew an awesome experience outside macOS! Highly recommended.
