### ISSUE TITLE
Some modules/input keybinds do not work in urxvt

### ISSUE THREAD

**Issue by Tmplt** [zimfw/zimfw#91]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:
- Zim commit ref: b1d5c00d5f6d3136e5dae74478369f5a770bb237
- gist of .zimrc: https://github.com/Tmplt/dotfiles/blob/desktop/zsh/.zimrc
- Zsh version: `zsh 5.2 (x86_64-unknown-linux-gnu)`
- gist of .zshrc: https://github.com/Tmplt/dotfiles/tree/desktop/zsh
- $(uname -mosr): `Linux 4.7.5-1-zen x86_64 GNU/Linux`
## Description

The keybinds `Up`, `Down`, `Left`, `Right` do not work in `urxvt`.
## Steps to reproduce
- Install `zim` and `rxvt-unicode`
- Start `urxvt`

**Comment by Eriner** [comment]
I'm chalking this up to urxvt being a special snowflake. I'm curious as to if other terminals that have the highlighter issue also are impacted by this.

**Comment by hyshka** [comment]
ArchLinux provides a special terminfo package for urxvt which may be worth investigating for those having issues specifically with this terminal emulator.

See: https://www.archlinux.org/packages/community/x86_64/rxvt-unicode-terminfo/

**Comment by Eriner** [comment]
I'm going to look into tackling this one.

**Comment by Eriner** [comment]
I can no longer reproduce this with urxvt, so I'm assuming it was resolved at some point.
